/-
P1/BlockA_LAIntegration.lean -- paper-level LA-2/LA-3 integration.

This module is intentionally disjoint from the audited foundation modules.  It
combines LA-3's exact family index witness with LA-2's identification of the
canonical XCode representatives with the actual cyclic subgroup generated by X.
-/

import P1.BlockA_LA2
import P1.BlockA_LA3

variable {n : Nat} [NeZero n]

namespace window

/-- The paper-level P1/P3 package for every member of the oddH window family.
The witness is the literal `Fin (2*n)` equivalence with actual left cosets, and
both conclusions refer to the actual cyclic subgroup generated by `Xg`. -/
theorem isSubgroup_P1_P3
    (h3 : 3 <= n) (hn : NatOdd n) (j : J) (alpha beta : Fin n) :
    Exists (fun iw : Index2nWitness (H j alpha beta) =>
      iw = familyIndex2nWitness j alpha beta /\
        CyclicTransitive (H j alpha beta) /\
          CyclicTrivialInter (H j alpha beta)) := by
  refine Exists.intro (familyIndex2nWitness j alpha beta)
    (And.intro rfl (And.intro ?_ ?_))
  · exact (cyclicTransitive_iff_Transitive h3 hn (H j alpha beta)).mpr
      (familyTransitive j alpha beta)
  · exact (cyclicTrivialInter_iff_TrivialInter h3 hn (H j alpha beta)).mpr
      (familyTrivialInter j alpha beta)

end window
