#!/usr/bin/env python3
"""
scratchpad/r4_second_system.py -- ISO-GATE route-2 R4: independent second
enumerator/checker (docs/notes/w6_bottomup_design_v4.md sec.5.4).

Independence discipline (探索器と照合器の分離): this script does NOT import or
read any GAP source file (search/*.g) and does NOT call GAP. Its ONLY input is
search/probe/w6_bu_s0/r4_input_data.json, a plain data dump (permutation images of the
generators x,y on n points for each fixture, plus the GAP driver's claimed
summary numbers to diff against). All group theory below (permutation
multiplication, BFS closure/generation, derived subgroup via commutator
closure, hexagon (3.10)/(3.11) via an independently-verified theta/tau
construction with contradiction detection, settled-check via the same
technique, isolated verdict) is reimplemented from scratch in Python.

GAP convention note: GAP permutations act on the RIGHT (k^(p*q) = (k^p)^q),
so "p*q" means "apply p first, then q" -- our compose(p,q) matches this.
HOWEVER: the GAP side's helper AbstractProd(list) (search/week3-battery-common.g)
does NOT evaluate a list [a,b,c] as a*b*c in that direct order -- its own
docstring says it implements the PAPER's left-to-right notation "f1 f2 ... fk"
via a REVERSAL: AbstractProd([a,b,c]) actually computes c*b*a in GAP semantics
(apply c first, then b, then a). This was found and confirmed by direct GAP
probing (scratchpad/debug_witness3.g) while chasing a witness-verification
mismatch during R4 cross-checking: for AbstractProd([f^-1, Y^u, f]) the actual
GAP-computed permutation is f * Y^u * f^-1 (apply f first, then Y^u, then
f^-1), NOT f^-1 * Y^u * f as the paper notation naively suggests. All uses of
this specific product below are written with that REVERSAL already applied
(compose(compose(f, Y^u), finv)), matching what GAP's AbstractProd([f^-1,Y^u,f])
actually returns. (Aggregate counts -- shadow_total, settled_count -- happen
to be invariant under this reversal since D=[G,G] is closed under inverses, so
this bug was invisible until a SPECIFIC labeled witness was checked; see the
driver-side comment for the parallel bug found in word-evaluation.)
"""
import json
import sys
from itertools import product


def compose(p, q):
    """p then q, matching GAP's k^(p*q) = (k^p)^q (1-indexed tuples)."""
    return tuple(q[p[i] - 1] for i in range(len(p)))


def invert(p):
    n = len(p)
    inv = [0] * n
    for i in range(n):
        inv[p[i] - 1] = i + 1
    return tuple(inv)


def identity(n):
    return tuple(range(1, n + 1))


def power(p, k, n):
    if k == 0:
        return identity(n)
    if k < 0:
        return power(invert(p), -k, n)
    result = identity(n)
    base = p
    while k > 0:
        if k & 1:
            result = compose(result, base)
        base = compose(base, base)
        k >>= 1
    return result


def order(p, n):
    idn = identity(n)
    cur = p
    k = 1
    while cur != idn:
        cur = compose(cur, p)
        k += 1
        if k > 100000:
            raise RuntimeError("order() did not converge")
    return k


def gcd(a, b):
    while b:
        a, b = b, a % b
    return a


def lcm(a, b):
    return a * b // gcd(a, b)


def bfs_closure(gens, n):
    """Standard orbit/closure BFS: all elements of <gens> as a set of tuples."""
    idn = identity(n)
    seen = {idn}
    queue = [idn]
    qi = 0
    while qi < len(queue):
        cur = queue[qi]
        qi += 1
        for g in gens:
            nv = compose(cur, g)
            if nv not in seen:
                seen.add(nv)
                queue.append(nv)
    return seen


def derived_subgroup(G_elements, n):
    """Commutator subgroup: subgroup generated by ALL commutators [g,h],
    g,h in G_elements. g^-1 h^-1 g h in GAP's Comm(g,h) convention; we just
    need SOME generating set of the derived subgroup, and "all commutators of
    all pairs" is a textbook-correct (if brute-force) choice, independent of
    GAP's DerivedSubgroup() algorithm."""
    commutators = set()
    G_list = list(G_elements)
    for g in G_list:
        ginv = invert(g)
        for h in G_list:
            hinv = invert(h)
            # [g,h] = g^-1 h^-1 g h  (standard commutator; any fixed convention
            # generates the same derived subgroup as long as applied to ALL pairs)
            comm = compose(compose(compose(ginv, hinv), g), h)
            commutators.add(comm)
    return bfs_closure(list(commutators), n)


def build_hom_with_check(G_elements, gens_domain, gens_image, n):
    """Independently construct a candidate endomorphism g -> phi(g) by BFS
    over the Cayley graph generated by gens_domain (each with its OWN image in
    gens_image, matched by index, both directions +1/-1), propagating images
    in lockstep, and DETECTING CONTRADICTIONS (same domain element reached via
    two paths with different images => map is NOT well-defined). This is a
    genuine, from-scratch verification, not an assumption.
    Returns (ok, phi_dict_or_reason).
    """
    idn = identity(n)
    phi = {idn: idn}
    queue = [idn]
    qi = 0
    # build the +1/-1 step list: each gens_domain[i] paired with gens_image[i]
    steps = []
    for gd, gi in zip(gens_domain, gens_image):
        steps.append((gd, gi))
        steps.append((invert(gd), invert(gi)))
    while qi < len(queue):
        cur = queue[qi]
        qi += 1
        cur_img = phi[cur]
        for gd, gi in steps:
            nv = compose(cur, gd)
            nv_img = compose(cur_img, gi)
            if nv in phi:
                if phi[nv] != nv_img:
                    return False, "CONTRADICTION: domain element reached with two different images"
            else:
                phi[nv] = nv_img
                queue.append(nv)
    if len(phi) != len(G_elements):
        return False, "INCOMPLETE: BFS from generators did not cover all of G"
    return True, phi


def run_fixture(name, n_points, x_img, y_img, expected):
    print(f"=== {name} ===")
    X = tuple(x_img)
    Y = tuple(y_img)
    idn = identity(n_points)

    # 1. independently enumerate G = <X,Y> via BFS closure
    G = bfs_closure([X, Y], n_points)
    g_size = len(G)
    print(f"  |G| (independent BFS closure) = {g_size}  (GAP claims {expected['expected_g_size']})")
    assert g_size == expected['expected_g_size'], "G size mismatch vs GAP claim"

    # 2. N_ord, charming set (independent: order() via repeated squaring/BFS)
    ordX = order(X, n_points)
    ordY = order(Y, n_points)
    nOrd = lcm(ordX, ordY)
    print(f"  ord(X)={ordX} ord(Y)={ordY} N_ord={nOrd}  (GAP claims {expected['expected_n_ord']})")
    assert nOrd == expected['expected_n_ord'], "N_ord mismatch vs GAP claim"
    charming = [m for m in range(nOrd) if gcd(2 * m + 1, nOrd) == 1]

    # 3. derived subgroup D = [G,G], independent commutator-closure computation
    D = derived_subgroup(G, n_points)
    print(f"  |D|=|[G,G]| (independent commutator closure) = {len(D)}")

    # 4. theta (x->y,y->x) and tau (x->y,y->z=(xy)^-1) via independent
    #    BFS-with-contradiction-detection construction (genuine verification,
    #    not assumed)
    # z := AbstractProd([X,Y])^-1; AbstractProd([X,Y]) reverses to compose(Y,X) -- see module docstring
    z = invert(compose(Y, X))
    theta_ok, theta = build_hom_with_check(G, [X, Y], [Y, X], n_points)
    tau_ok, tau = build_hom_with_check(G, [X, Y], [Y, z], n_points)
    print(f"  theta well-defined (independent BFS check): {theta_ok}")
    print(f"  tau well-defined (independent BFS check): {tau_ok}")
    if not (theta_ok and tau_ok):
        print("  theta/tau not well-defined -- cannot proceed with hexagon enumeration (matches GAP's THETA_TAU_NOT_WELLDEFINED branch)")
        return {"name": name, "theta_tau_ok": False}

    # 5. hexagon (3.10)/(3.11) + generation(SURJ), independently, over D x charming
    shadow_total = 0
    h10_fail = 0
    h11_fail = 0
    generation_fail = 0
    shadows = []
    for f in D:
        thetaf = theta[f]
        # AbstractProd([f, thetaf]) reverses to compose(thetaf, f) -- see module docstring
        hex310 = compose(thetaf, f) == idn
        if not hex310:
            h10_fail += 1
            continue
        for m in charming:
            u = 2 * m + 1
            ym = power(Y, m, n_points)
            # AbstractProd([y^m, f]) reverses to compose(f, y^m) -- see module docstring
            ymf = compose(f, ym)
            tau_ymf = tau[ymf]
            tau2_ymf = tau[tau_ymf]
            # AbstractProd([tau2ymf, tauymf, ymf]) reverses to compose(compose(ymf, tau_ymf), tau2_ymf)
            hex311 = compose(compose(ymf, tau_ymf), tau2_ymf) == idn
            if not hex311:
                h11_fail += 1
                continue
            genA = power(X, u, n_points)
            finv = invert(f)
            # AbstractProd([finv, Y^u, f]) reverses to compose(compose(f, Y^u), finv)
            genB = compose(compose(f, power(Y, u, n_points)), finv)
            gensub = bfs_closure([genA, genB], n_points)
            if len(gensub) != g_size:
                generation_fail += 1
                continue
            shadow_total += 1
            shadows.append((m, f, genA, genB))

    print(f"  candidate structure: h10_fail(distinct f)={h10_fail} (this counts distinct f failing 3.10, "
          f"summed once per f not per (f,m) -- see note below)")
    print(f"  h11_fail(f,m pairs)={h11_fail} generation_fail(f,m pairs)={generation_fail} shadow_total={shadow_total}")
    print(f"  (GAP claims shadow_total={expected['expected_shadow_total']})")
    assert shadow_total == expected['expected_shadow_total'], "shadow_total mismatch vs GAP claim"

    # 6. settled check: independently build T_{m,f} via the same BFS-with-
    #    contradiction-detection technique, check well-defined AND surjective
    #    (=> bijective on the finite set G, by the pigeonhole argument)
    settled_count = 0
    for (m, f, genA, genB) in shadows:
        ok, phi = build_hom_with_check(G, [X, Y], [genA, genB], n_points)
        if not ok:
            continue
        image = set(phi.values())
        if len(image) == g_size:  # surjective on finite G => bijective
            settled_count += 1
    print(f"  settled (independent) = {settled_count}/{shadow_total}  (GAP claims {expected['expected_settled_count']}/{expected['expected_settled_total']})")
    assert settled_count == expected['expected_settled_count'], "settled_count mismatch vs GAP claim"
    assert shadow_total == expected['expected_settled_total'], "settled_total mismatch vs GAP claim"

    verdict = "TRUE" if settled_count == shadow_total and shadow_total > 0 else ("UNKNOWN" if shadow_total == 0 else "FALSE")
    print(f"  independent verdict = {verdict}  (GAP claims {expected['expected_verdict']})")
    assert verdict == expected['expected_verdict'], "verdict mismatch vs GAP claim"
    print(f"  [MATCH] {name}: independent second system agrees with GAP driver on all summary numbers\n")
    return {"name": name, "theta_tau_ok": True, "g_size": g_size, "n_ord": nOrd,
            "shadow_total": shadow_total, "settled_count": settled_count, "verdict": verdict,
            "match_gap": True}


def check_m_iso2_witness(x_img, y_img, n_points, witness):
    """Independently re-derive the M-ISO-2 witness's non-generation fact:
    build genA=x^u, genB=f^-1 y^u f from the SAME (m, f_word) pair the GAP
    driver used, and independently confirm |<genA,genB>| < |G| (the paper
    argument's premise). This is condition (1)/(2) from commander's 2026-08-05
    ruling: R4 must independently confirm the SAME synthetic window is FALSE,
    and the witness's non-settledness must have an out-of-driver check.
    """
    print("=== M-ISO-2 witness independent re-check ===")
    X = tuple(x_img)
    Y = tuple(y_img)
    G = bfs_closure([X, Y], n_points)
    g_size = len(G)
    m = witness['m']
    u = 2 * m + 1
    # NOTE: witness['f_word'] is convention-fragile (BFSWords prepend-storage
    # vs different word evaluators reconstruct DIFFERENT group elements from
    # the SAME word -- a real bug caught during R4 cross-checking, see comment
    # in search/probe/w6_bu_s0/iso_gate_r3r4_driver.g near
    # FindNonGeneratingWitness). We deliberately do NOT re-derive f from the
    # word here; we use the GAP driver's raw f_images dump instead (the
    # authoritative, convention-independent representation of the witness
    # element, on the witness's OWN point set -- which may differ in size
    # from k3_x_img/k3_y_img if the witness source ended up being W-5).
    f = tuple(witness['f_images'])
    genA = power(X, u, n_points)
    finv = invert(f)
    # AbstractProd([finv, Y^u, f]) reverses to compose(compose(f, Y^u), finv) -- see module docstring
    genB = compose(compose(f, power(Y, u, n_points)), finv)
    subgroup = bfs_closure([genA, genB], n_points)
    print(f"  witness m={m} f_word={witness['f_word']}")
    print(f"  independent |<genA,genB>| = {len(subgroup)}  (GAP claims {witness['expected_subgroup_size']}, |G|={g_size})")
    assert len(subgroup) == witness['expected_subgroup_size'], "witness subgroup size mismatch"
    is_proper = len(subgroup) < g_size
    print(f"  proper subgroup (independent)? {is_proper}  (GAP claims {witness['expected_subgroup_size_lt_g']})")
    assert is_proper == witness['expected_subgroup_size_lt_g'], "witness proper-subgroup mismatch"
    print("  paper argument (independently confirmed): image subgroup is PROPER "
          "=> induced map cannot be surjective onto G => cannot be bijective on finite G")
    print("  => this witness is NOT settled, confirmed by a SEPARATE (non-GAP) computation, "
          "satisfying commander's condition (2) (out-of-driver witness check)\n")
    return {"witness_proper_subgroup_independent": is_proper, "subgroup_size": len(subgroup)}


def main():
    with open("search/probe/w6_bu_s0/r4_input_data.json", encoding="utf-8") as f:
        data = json.load(f)

    results = {}
    results['k3'] = run_fixture("K^(3)", data['k3']['n_points'], data['k3']['x_images'],
                                 data['k3']['y_images'], data['k3'])
    results['w5'] = run_fixture("W-5", data['w5']['n_points'], data['w5']['x_images'],
                                 data['w5']['y_images'], data['w5'])
    witness_src = data['m_iso2_witness']['source']
    src_data = data['k3'] if witness_src.startswith("K") else data['w5']
    results['m_iso2_witness'] = check_m_iso2_witness(
        src_data['x_images'], src_data['y_images'], data['m_iso2_witness']['n_points'],
        data['m_iso2_witness'])

    # M-ISO-2's FULL constructed-datum verdict, independently: real K3 shadows
    # (all settled, confirmed above) + 1 injected witness (confirmed non-settled
    # above) => total = shadow_total+1, settled = shadow_total, verdict FALSE.
    k3 = results['k3']
    mIso2_total = k3['shadow_total'] + 1
    mIso2_settled = k3['settled_count']
    mIso2_verdict = "FALSE" if mIso2_settled < mIso2_total else "TRUE"
    print(f"=== M-ISO-2 constructed-datum verdict (independent second system) ===")
    print(f"  total={mIso2_total} settled={mIso2_settled} verdict={mIso2_verdict}  (GAP claims FALSE)")
    assert mIso2_verdict == "FALSE", "R4 second system does NOT confirm M-ISO-2 as FALSE -- MISMATCH with GAP driver"
    print("  [MATCH] R4 second system independently confirms M-ISO-2's constructed negative fixture is FALSE\n")

    print("ALL R4 CROSS-CHECKS PASSED: independent Python second system agrees with the GAP driver "
          "(search/probe/w6_bu_s0/iso_gate_r3r4_driver.g) on K^(3), W-5, and the M-ISO-2 witness.")

    out = {
        "schema": "gtsh-cert/iso-gate-r4-second-system/v1",
        "generated_by": {"tool": "python3 (independent, no GAP)", "script": "scratchpad/r4_second_system.py"},
        "independence_declaration": "does not import/read any search/*.g file or call GAP; only input is search/probe/w6_bu_s0/r4_input_data.json (raw generator permutation images + GAP's claimed summary numbers to diff against); all group theory (BFS closure, derived subgroup via commutator closure, theta/tau construction with contradiction detection, hexagon, generation/SURJ, settled-check, verdict) reimplemented from scratch in Python",
        "k3": {k: v for k, v in results['k3'].items()},
        "w5": {k: v for k, v in results['w5'].items()},
        "m_iso2_witness_independent_check": results['m_iso2_witness'],
        "m_iso2_constructed_datum_independent_verdict": mIso2_verdict,
        "all_crosschecks_pass": True,
    }
    with open("search/probe/w6_bu_s0/r4_second_system_output.json", "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
    print("\nwrote search/probe/w6_bu_s0/r4_second_system_output.json")


if __name__ == "__main__":
    main()
