#############################################################################
## Direct-v4: explicit 20 disjoint 36-point blocks.
## This is a versioned repair of direct-v3's nested DirectProduct/Embedding
## construction.  No GAP factor embedding is used here.
#############################################################################
Read("search/gaplib_common.g");; Read("search/week3-battery-common.g");; Read("search/week3-psl-common.g");;
J4:=function(x)local a,i;if x=true then return "true";fi;if x=false then return "false";fi;if IsInt(x) then return String(x);fi;if IsList(x) and Length(x)=0 then return "[]";fi;if IsString(x) then return Concatenation("\"",x,"\"");fi;if IsList(x) then a:=List([1..Length(x)],i->J4(x[i]));return Concatenation("[",JoinC(a,","),"]");fi;Error("direct v4: json");end;;
P4:=function(p,d)return List([1..d],i->i^p);end;;
Eval4:=function(w,imgs)local z,x,k;z:=One(imgs[1]);for x in w do k:=AbsInt(x);if x=0 or k>Length(imgs) then Error("direct v4: signed word");fi;if x>0 then z:=z*imgs[k];else z:=z*imgs[k]^-1;fi;od;return z;end;;
Block20:=function(v)local a,j,k;a:=[1..20*36];for j in [1..20] do for k in [1..36] do a[(j-1)*36+k]:=(j-1)*36+(k^v[j]);od;od;return PermList(a);end;;

if IsBound(D972_B4_MARITY_PHASEB1_DIRECT_V4_SELFTEST) and D972_B4_MARITY_PHASEB1_DIRECT_V4_SELFTEST=true then
 Print("D972_B4_MARITY_PHASEB1_DIRECT_V4_SELFTEST_PASS blocks=20 degree=720 explicit_blocks=true\n");
else
 if not IsBound(D972_B4_MARITY_PHASEB1_DIRECT_V4_OUTPUT) then D972_B4_MARITY_PHASEB1_DIRECT_V4_OUTPUT:="ci/out/d972_b4_marity_phaseb1_direct_v4.json";;fi;
 F4:=FreeGroup("s1","s2","s3");;s1:=F4.1;;s2:=F4.2;;s3:=F4.3;;B4:=F4/[s1*s3*s1^-1*s3^-1,s1*s2*s1*(s2*s1*s2)^-1,s2*s3*s2*(s3*s2*s3)^-1];;
 b1:=B4.1;;b2:=B4.2;;b3:=B4.3;;X12:=b1^2;;X23:=b2^2;;X34:=b3^2;;X13:=b2*b1^2*b2^-1;;X24:=b3*b2^2*b3^-1;;X14:=b3*X13*b3^-1;;
 pb4Marks:=[X12,X13,X14,X23,X24,X34];;pb4Sub:=Subgroup(B4,pb4Marks);;if Index(B4,pb4Sub)<>24 then Error("direct v4: PB4 index");fi;;iso4:=IsomorphismFpGroupByGenerators(pb4Sub,pb4Marks);;PB4fp:=Image(iso4);;g4:=GeneratorsOfGroup(PB4fp);;if List(pb4Marks,g->Image(iso4,g))<>g4 then Error("direct v4: PB4 marking pin");fi;
 F3:=FreeGroup("t1","t2");;t1:=F3.1;;t2:=F3.2;;B3:=F3/[t1*t2*t1*(t2*t1*t2)^-1];;q1:=B3.1;;q2:=B3.2;;pb3Marks:=[q1^2,q2*q1^2*q2^-1,q2^2];;pb3Sub:=Subgroup(B3,pb3Marks);;if Index(B3,pb3Sub)<>6 then Error("direct v4: PB3 index");fi;;iso3:=IsomorphismFpGroupByGenerators(pb3Sub,pb3Marks);;PB3fp:=Image(iso3);;g3:=GeneratorsOfGroup(PB3fp);;if List(pb3Marks,g->Image(iso3,g))<>g3 then Error("direct v4: PB3 marking pin");fi;;f3:=FreeGroupOfFpGroup(PB3fp);;f3g:=GeneratorsOfGroup(f3);;rels3:=RelatorsOfFpGroup(PB3fp);;if Product(pb3Marks)<>(q1*q2)^3 then Error("direct v4: center replay");fi;
 g9:=MakeGn(9);;CheckGF8();;Smat:=MakeMatGF8(1,0,1,1);;Tmat:=MakeMatGF8(4,3,1,5);;Sperm:=MatToPermGF8(Smat);;Tperm:=MatToPermGF8(Tmat);;Xp:=(Sperm*Tperm^-1)^2;;Yp:=Sperm^-1*Xp*Sperm;;XM:=Sum3(g9.x,27,Xp,9);;YM:=Sum3(g9.y,27,Yp,9);;GM:=Group(XM,YM);;if Size(GM)<>1469664 then Error("direct v4: M order");fi;;mImgs:=[XM,XM^-1*YM^-1,YM];;hM:=GroupHomomorphismByImages(PB3fp,GM,g3,mImgs);;if hM=fail or not ForAll(rels3,w->Image(hM,MappedWord(w,f3g,g3))=One(GM)) then Error("direct v4: target replay");fi;
 rows:=[ [[],[],[],[1],[2],[3]],[[],[1],[2],[],[],[3]],[[1],[],[2],[],[3],[]],[[1],[2],[],[3],[],[]] ];;del:=List(rows,r->List(r,w->Eval4(w,mImgs)));;hdel:=List(del,r->GroupHomomorphismByImages(PB4fp,GM,g4,r));;if ForAny(hdel,h->h=fail) then Error("direct v4: deletion map");fi;
 paper:=[[X12,X23,X13],[X23,X34,X24],[X13*X23,X34,X14*X24],[X12*X13,X24*X34,X14],[X12,X23*X24,X13*X14]];;canon:=List(paper,w->[w[1],w[3],w[2]]);;paperLabels:=[["x12","x23","x13"],["x23","x34","x24"],["x13*x23","x34","x14*x24"],["x12*x13","x24*x34","x14"],["x12","x23*x24","x13*x14"]];;canonLabels:=[["x12","x13","x23"],["x23","x24","x34"],["x13*x23","x14*x24","x34"],["x12*x13","x14","x24*x34"],["x12","x13*x14","x23*x24"]];;
 blocks:=[];;identityCoords:=[];;for k in [1..5] do cfp:=List(canon[k],w->Image(iso4,w));;hc:=GroupHomomorphismByImages(PB3fp,PB4fp,g3,cfp);;if hc=fail or not ForAll(rels3,w->Image(hc,MappedWord(w,f3g,g3))=One(PB4fp)) then Error("direct v4: coface relator ",k);fi;;for i in [1..4] do b:=List([1..3],j->Image(hdel[i],Image(hc,g3[j])));;Add(blocks,b);;if ForAll([1..3],j->b[j]=Image(hM,g3[j])) then Add(identityCoords,[k,i]);fi;;od;;od;
 jointImgs:=List([1..3],j->Block20(List(blocks,b->b[j])));;N3q:=Group(jointImgs);;joint:=GroupHomomorphismByImages(PB3fp,N3q,g3,jointImgs);;if joint=fail or not ForAll(rels3,w->Image(joint,MappedWord(w,f3g,g3))=One(N3q)) then Error("direct v4: joint relator replay");fi;;x12i:=jointImgs[1];;x23i:=jointImgs[3];;ci:=Image(joint,Product(g3));;NOrd:=Lcm(Order(x12i),Order(x23i),Order(ci));;F2ord:=Size(Group(x12i,x23i));;if Size(N3q) mod Size(GM)<>0 then Error("direct v4: ratio");fi;;ratio:=QuoInt(Size(N3q),Size(GM));;splitStatus:="NOT_ESTABLISHED";;if Size(N3q)=1469664*18 and F2ord=1469664 and Order(ci)=18 then splitStatus:="CONDITIONAL_SPLIT_NUMERIC_GATE";fi;
 cert:=Concatenation("{\"schema\":\"d972-b4-marity-phaseb1-direct/v4\",\"status\":\"DIRECT_20_BLOCK_TYPED\",\"explicit_blocks\":true,\"degree\":720,\"block_count\":20,\"block_degree\":36,\"identity_coordinates\":",J4(identityCoords),",\"source_marking\":[\"x12\",\"x13\",\"x23\"],\"target_marking\":[\"X\",\"X^-1Y^-1\",\"Y\"],\"pb3_index\":6,\"pb4_index\":24,\"center\":{\"word\":\"x12*x13*x23\",\"ambient\":\"(s1*s2)^3\",\"image\":",J4(P4(ci,720)),",\"order\":",String(Order(ci)),"},\"N_ord\":",String(NOrd),",\"N3_quotient_order\":",String(Size(N3q)),",\"N3_F2_image_order\":",String(F2ord),",\"M_over_N3_ratio\":",String(ratio),",\"central_split\":{\"status\":\"",splitStatus,"\",\"required_quotient_order\":26453952,\"required_F2_order\":1469664,\"required_center_order\":18},\"generator_arrays\":",J4(List(jointImgs,p->P4(p,720))),",\"coface_labels\":{\"paper\":",J4(paperLabels),",\"canonical\":",J4(canonLabels),"},\"gentle_fiber_gate\":{\"status\":\"BLOCKED_MISSING_TYPED_B3_EXTENSION\",\"expected_targets\":972,\"enumerated\":false},\"typing_boundary\":{\"M_B4_stable\":false,\"GT_descent\":\"UNPROVEN\"}}\n");;WriteFile(D972_B4_MARITY_PHASEB1_DIRECT_V4_OUTPUT,cert);;Print("D972_B4_MARITY_PHASEB1_DIRECT_V4_WRITTEN ",D972_B4_MARITY_PHASEB1_DIRECT_V4_OUTPUT," N3=",Size(N3q)," explicit_blocks=true\n");
fi;
