## p1_build_R.g -- CAL-B4 工程 P1 (docs/notes/b4_direct_adjudication_feasibility_v1_2.md
## sec5.4, sec8): build R := PB4 / V(PB4) = PB4 / (gamma_5(PB4) PB4^7) via
## ANUPQ's Pq with the CORRECTED spec (Exponent:=7 is REQUIRED -- dropping it
## gives a different, wrong group; doc's own footnote: PQuotient(F2,7,2)=7^5
## vs |F2:gamma_3(F2)F2^7)|=7^3, a ClassBound-vs-true-Exponent discrepancy).
##
## Only reachable if anupq_smoke.g PASSED on this runner (workflow gate) --
## the local Windows/Cygwin ANUPQ pq binary is known dead (iostream error),
## this job assumes a working GHA-built pq (verified by the smoke job).
##
## Gated predictions (doc sec8.2, IF-FIRST):
##   B4-EXQ-1: |R| = 7^41
##   B4-EXQ-2: R = C7 x Q, |Q| = 7^40 (Q = K(0,5)/W, established elsewhere)
## B4-EXQ-3 (tilde-N*_PB3 = N0, the PB3-restriction equality) requires
## building the PB3-embedding inside PB4 and computing an intersection with
## ker(PB4fp -> R); NOT implemented in this pass (flagged, not silently
## skipped) -- left for a follow-up script once B4-EXQ-1/2 are confirmed.
##
## NOT included here (by explicit instruction): the actual 117,649-element
## (2.20) measurement using R (工程 P2/P3) -- deferred to a separate dispatch
## pending Sol authorization (便112).
Read("search/gaplib_common.g");
Read("search/probe/wac_v1/gap_output_prelude.g");

if LoadPackage("anupq") <> true then
  Error("anupq LoadPackage failed -- P1 cannot proceed");
fi;

## --- stage1-style PB4fp construction (reused pattern, verbatim from
## search/probe/hsp7_gap_v1/stage1_pb4.g) ---
F := FreeGroup("s1","s2","s3");;
s1 := F.1;; s2 := F.2;; s3 := F.3;;
rels := [ s1*s3*s1^-1*s3^-1,
          s1*s2*s1*(s2*s1*s2)^-1,
          s2*s3*s2*(s3*s2*s3)^-1 ];;
B4 := F / rels;;
b1 := B4.1;; b2 := B4.2;; b3 := B4.3;;

X12 := b1^2;;  X23 := b2^2;;  X34 := b3^2;;
X13 := b2*b1^2*b2^-1;;  X24 := b3*b2^2*b3^-1;;  X14 := b3*X13*b3^-1;;
gensPB4 := [X12,X13,X14,X23,X24,X34];;

PB4sub := Subgroup(B4, gensPB4);;
idx24 := Index(B4, PB4sub);;
Print("[B4:PB4] = ", idx24, " (expect 24)\n");
if idx24 <> 24 then
  Print("STOP -- PB4 construction sanity failed, aborting P1\n");
  QUIT;
fi;

iso := IsomorphismFpGroupByGenerators(PB4sub, gensPB4);;
PB4fp := Image(iso);;
Print("PB4fp built, ", Length(GeneratorsOfGroup(PB4fp)), " generators (expect 6)\n");

## --- B4-EXQ-1/2: R := PB4fp / V(PB4fp), corrected spec (Exponent:=7 REQUIRED) ---
Print("\n=== P1: R := Pq(PB4fp : Prime:=7, ClassBound:=4, Exponent:=7) ===\n");
t0 := GAPLIB_WallElapsedMs();
R := fail;;
if not IsBound(Pq) then
  Error("Pq function not bound -- anupq broken, P1 cannot proceed");
fi;
R := Pq(PB4fp : Prime := 7, ClassBound := 4, Exponent := 7);;
t1 := GAPLIB_WallElapsedMs();

if R = fail then
  Print("STOP -- Pq(PB4fp:...) returned fail. P1 BLOCKED (same failure mode as "
        "the documented local ANUPQ iostream blocker, sec5.4). Report and do "
        "not proceed to P2.\n");
  Print("P1_FAIL\n");
  QUIT;
fi;

sizeR := Size(R);;
Print("Pq computed in ", t1-t0, " ms\n");
Print("|R| = ", sizeR, "  (B4-EXQ-1 predicts 7^41 = ", 7^41, ")\n");
b4exq1 := (sizeR = 7^41);;
Print("B4-EXQ-1: ", b4exq1, "\n");

## --- B4-EXQ-2: R = C7 x Q, |Q| = 7^40 ---
## Center(R) should contain a direct C7 factor (PB4 = Z x K(0,5), the Z part
## being generated by the full twist Delta4^2, central in PB4 hence its image
## in R is central too; V(PB4) contains the 7th powers so the Z-factor's image
## in R has order exactly 7).
Print("\n=== B4-EXQ-2: R = C7 x Q ===\n");
ZR := Center(R);;
Print("|Z(R)| = ", Size(ZR), "\n");
## DirectFactorsOfGroup can be expensive/unavailable for large pc groups;
## a cheaper sufficient check: does R have a NORMAL subgroup of order 7 whose
## quotient has order 7^40 AND R actually splits as a direct product with it?
## We report the factorization attempt and its result plainly (no silent
## pass/fail dressing -- this is the part of P1 NOT yet locally validated).
if sizeR = 7^41 then
  factors := fail;;
  if IsBound(DirectFactorsOfGroup) then
    factors := DirectFactorsOfGroup(R);;
  fi;
  if factors <> fail then
    Print("DirectFactorsOfGroup(R): ", List(factors, Size), "\n");
    b4exq2 := (Length(factors) >= 2 and 7 in List(factors,Size) and (7^40) in List(factors,Size));;
    Print("B4-EXQ-2 (direct factor 7 x 7^40 found among factors): ", b4exq2, "\n");
  else
    Print("DirectFactorsOfGroup not available/applicable -- B4-EXQ-2 NOT independently "
          "confirmed by this script (report as UNKNOWN, not silently PASS).\n");
  fi;
else
  Print("sizeR <> 7^41, skipping B4-EXQ-2 (B4-EXQ-1 already failed)\n");
fi;

Print("\n=== P1 SUMMARY ===\n");
Print("|R|=", sizeR, "  B4-EXQ-1=", b4exq1, "\n");
Print("NOTE: B4-EXQ-3 (tilde-N*_PB3 = N0) is NOT checked by this script -- "
      "deferred, flagged explicitly, not silently skipped.\n");
Print("NOTE: P2/P3 (the actual 117,649-element (2.20) measurement using R) "
      "is deliberately NOT included in this workflow (Sol authorization "
      "pending via 便112, per explicit instruction).\n");

if b4exq1 = true then
  Print("P1_PASS\n");
else
  Print("P1_FAIL\n");
fi;
Print("ALL_DONE\n");
