#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
search/sat/encode_diam20_path21.py

Synthetic diameter boundary fixture requested in
sol/sol_reply_85_math12.md P85-6 point 3 (裁定 214 工程 4), replacing the
"weak" M6_bfs_depth_1off mutant (Sol F85-8.5: M6's instance is disconnected,
so a depth-1-off test is not decisive there -- see mutants_n21.json M6 entry,
kept as a historical row per the delegation instructions).

Builds a 21-vertex PATH graph 1-2-3-...-21 (fixed, not derived from any a/b/u
witness) whose true graph-theoretic diameter from vertex 1 is EXACTLY 20
(the only route to vertex 21 is the 20-edge path). Reuses the E/STEP/R
Tseitin machinery from encode_tail8_n21.py UNCHANGED (full biconditional,
both directions kept -- this is not a mutant of the machinery, only the
fixed edge data differs) with the SAME variable id scheme (X/D/B ids are
declared in `p cnf` but never appear in any clause, which is legal DIMACS)
so this fixture is a faithful drop-in re-use of the exact machinery being
calibrated, not a re-implementation.

Produces two CNFs:
  tail8_diam20_path21_depth19.cnf  -- goal: R[19][v] for all v.
     Expected: UNSAT (vertex 21 is not reachable within 19 hops on a path
     of length 20; this is forced by the (kept, non-mutated) necessary
     direction of the R Tseitin biconditional, so unit propagation alone
     derives R[19][21]=false, directly contradicting the unit goal clause
     [R(19,21)]).
  tail8_diam20_path21_depth20.cnf  -- goal: R[20][v] for all v.
     Expected: SAT (every vertex is within distance 20 of vertex 1 on this
     graph; in fact vertex 21 needs exactly 20, so this is a tight witness
     that the encoder's depth bound is not off-by-one in the other
     direction either).

kissat is NOT invoked here (RAM 8GB; CI dispatch is the commander's job).
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import encode_tail8_n21 as ENC  # noqa: E402  (search-side reuse of the E/STEP/R machinery)

PATH_EDGES = set()
for _i in range(1, ENC.N):
    a, b = _i, _i + 1
    PATH_EDGES.add((min(a, b), max(a, b)))


def group_edge_fixed_path(cs):
    clauses = []
    for (i, j) in ENC.PAIRS:
        e = ENC.E(i, j)
        if (i, j) in PATH_EDGES:
            clauses.append([e])
        else:
            clauses.append([-e])
    cs.add_group("edge_fixed_to_path_1_2_dots_21", clauses)


def build_clauses(goal_depth):
    cs = ENC.ClauseSet()
    group_edge_fixed_path(cs)
    ENC.group_r_base_case(cs)
    ENC.group_step_definition(cs)
    ENC.group_r_step_definition(cs)
    clauses = []
    for v in range(1, ENC.N + 1):
        clauses.append([ENC.R(goal_depth, v)])
    cs.add_group(f"path_reach_goal_depth_{goal_depth}", clauses)
    return cs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", default=os.path.join(os.path.dirname(__file__), "out", "mutants"))
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    results = {}
    for depth, fname, expected in [
        (19, "tail8_diam20_path21_depth19.cnf", "UNSAT"),
        (20, "tail8_diam20_path21_depth20.cnf", "SAT"),
    ]:
        cs = build_clauses(depth)
        path = os.path.join(args.out_dir, fname)
        ENC.write_dimacs(
            path, ENC.TRANS_VAR_COUNT, cs,
            [
                f"Synthetic 21-vertex path diameter fixture, goal depth={depth} "
                "(sol/sol_reply_85_math12.md P85-6 point 3, Ruling 214 step 4).",
                f"Fixed graph: path 1-2-...-21 (edge (i,i+1) for i=1..20). "
                f"True diameter from vertex 1 is 20. Expected verdict: {expected}.",
                "X/D/B variable ids (1..672) are declared but unused (legal DIMACS) "
                "-- reused unchanged from encode_tail8_n21.py's numbering scheme.",
                "Generated by search/sat/encode_diam20_path21.py -- do not hand-edit.",
            ],
        )
        results[f"depth{depth}"] = {
            "path": os.path.relpath(path).replace("\\", "/"),
            "num_vars": ENC.TRANS_VAR_COUNT,
            "num_clauses": cs.nclauses(),
            "sha256": ENC.sha256_of_file(path),
            "groups": cs.groups,
            "expected_verdict": expected,
        }

    print(json.dumps(results, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
