#############################################################################
## search/a18-filter-ledger.g -- A18-filter-ledger/v1 (裁定200 工程1)
##
## Re-runs the W-D-A18-13a Xi-restricted enumeration with a STAGE-BY-STAGE
## survivor counter, per charming m:
##   xi_raw        -- all f = f0*c candidates generated by the Prop 3.1
##                     construction (BEFORE any filter), i.e. the coset scan
##                     itself. This is the "post-Xi" accounting: it already
##                     lives inside the Xi-restricted search space
##                     (|StabG|*|C_P(ybar^u)| per m), NOT the raw legacy
##                     |[P,P]| space.
##   in_derived    -- survivors after the f in [P,P] check
##   theta_inv     -- survivors after (F2)-1 (f*theta~(f)=1 in Bq)
##   r_tau         -- survivors after (F2)-2 (R_tau~(m,f)=c^m)
##   generation    -- survivors after the P_N-generation check
##   bq_settled    -- survivors after the Bq-level settled clause (= final
##                     shadow count for that m)
##
## ACCOUNTING SEPARATION (as instructed, "pre-Xi と post-Xi は別 namespace"):
## the JSON below keeps two clearly separate top-level namespaces:
##   "pre_xi"  -- the THEORETICAL, UN-enumerated legacy candidate space per m
##                (|[P,P]| itself; |[P,P]|=|A18| here since A18 is simple/
##                perfect, so this is the SAME astronomical number for every
##                m -- it is reported as a reference figure only, it is
##                NEVER actually enumerated -- Elements() on it would be the
##                same "memory death" scenario documented elsewhere in this
##                campaign)
##   "post_xi" -- the actual, real, per-stage survivor counts from the
##                Prop-3.1-restricted scan that was really run (the numbers
##                below all come from this namespace; nothing under pre_xi
##                is ever computed by enumeration)
## This split exists so a reader cannot mistake "xi_raw" (already inside the
## restricted space) for "all of [P,P]" (the legacy space) or vice versa.
##
## Output: search/certs/a18_filter_ledger_20260729.json
#############################################################################

JUDGE_LIBRARY_ONLY := true;;
Read("search/kerchi-judge.g");

#############################################################################
## ---------------------- window construction (same as strike-a18.g) --------
#############################################################################
a1 := ( 1,17)( 2, 6)( 3,14)( 5,15)( 7,16)( 8,13)(10,12)(11,18);;
b1 := ( 1,16, 6)( 2, 5,14)( 3,15, 4)( 7,17,13)( 8,12, 9)(10,11,18);;
A18 := AlternatingGroup(18);;
S3 := SymmetricGroup(3);;
Dgrp := DirectProduct(A18, S3);;
embA := Embedding(Dgrp, 1);;  embS := Embedding(Dgrp, 2);;
agen := Image(embA, a1) * Image(embS, (1,3));;
bgen := Image(embA, b1) * Image(embS, (1,3,2));;
s1 := bgen^-1 * agen;;
s2 := agen^-1 * bgen^2;;
W := MakeWindow(s1, s2);;
ch := Filtered([0 .. W.Nord - 1], m -> Gcd(2*m+1, W.Nord) = 1);;
Print("charmingSet=", ch, "  (count=", Length(ch), ")\n");

D := DerivedSubgroup(W.PN);;
legacyPP := Size(D);;
Print("|[P,P]| (pre-Xi reference figure, NOT enumerated) = ", legacyPP, "\n");

#############################################################################
## ---------------------- instrumented per-m stage counter -------------------
## (re-implements the Xi-restricted scan body from CorrectedShadowsXi, adding
## a counter at each filter stage; logic is otherwise IDENTICAL to that
## function -- this is deliberately a parallel instrumented copy, not a
## modification of kerchi-judge.g itself, to keep the ledger driver fully
## separate from the judge library.)
#############################################################################
fastAutN := IsNaturalAlternatingGroup(W.PN) and NrMovedPoints(W.PN) <> 6;;
if fastAutN then
  AutP := SymmetricGroup(MovedPoints(W.PN));;
  StabG := Centralizer(AutP, W.x);;
else
  AutP := AutomorphismGroup(W.PN);;
  actFun := function(pt, g) return Image(g, pt); end;;
  StabG := Stabilizer(AutP, W.x, actFun);;
fi;
stabElts := Elements(StabG);;
Print("|Stab_Aut(P)(xbar)| = ", Length(stabElts), "  fastAutN=", fastAutN, "\n");

LEDGER_ROWS := [];;

for m in ch do
  u := 2*m + 1;;
  Print("--- m=", m, " (u=", u, ") ---\n");
  yu := W.y^u;;
  Cyu := Centralizer(W.PN, yu);;
  cElts := Elements(Cyu);;
  xiRawCount := 0;;  inDerivedCount := 0;;  thetaInvCount := 0;;
  rTauCount := 0;;  genCount := 0;;  bqSettledCount := 0;;

  if fastAutN then
    alpha0 := RepresentativeAction(AutP, W.x, W.x^u);;
  else
    alpha0 := RepresentativeAction(AutP, W.x, W.x^u, actFun);;
  fi;

  if alpha0 <> fail then
    for s in stabElts do
      if fastAutN then
        target := W.y ^ (s * alpha0);;
      else
        target := Image(alpha0, Image(s, W.y));;
      fi;
      hRep := RepresentativeAction(W.PN, yu, target, OnPoints);;
      if hRep <> fail then
        f0 := hRep^-1;;
        for c in cElts do
          f := f0 * c;;
          xiRawCount := xiRawCount + 1;;

          if f in D then
            inDerivedCount := inDerivedCount + 1;;

            if AbstractProd([f, TH(W, f)]) = Identity(W.Bq) then
              thetaInvCount := thetaInvCount + 1;;

              if RtOf(W, m, f) = W.c^m then
                rTauCount := rTauCount + 1;;

                if Size(Group(W.x^u, AbstractProd([f^-1, W.y^u, f]))) = Size(W.PN) then
                  genCount := genCount + 1;;

                  settledHom := GroupHomomorphismByImages(W.Bq, W.Bq, [W.s1, W.s2],
                                  [W.s1^u, AbstractProd([f^-1, W.s2^u, f])]);;
                  if settledHom <> fail then
                    bqSettledCount := bqSettledCount + 1;;
                  fi;
                fi;
              fi;
            fi;
          fi;
        od;
      fi;
    od;
  fi;

  Print("  xi_raw=", xiRawCount, " in_derived=", inDerivedCount,
        " theta_inv=", thetaInvCount, " r_tau=", rTauCount,
        " generation=", genCount, " bq_settled=", bqSettledCount, "\n");
  Add(LEDGER_ROWS, rec(m := m, u := u,
    post_xi_raw := xiRawCount, post_xi_in_derived := inDerivedCount,
    post_xi_theta_inv := thetaInvCount, post_xi_r_tau := rTauCount,
    post_xi_generation := genCount, post_xi_bq_settled := bqSettledCount,
    pre_xi_legacy_pp := legacyPP));
od;

#############################################################################
## ---------------------- summary: where do the 3/5-primary factors die? ----
#############################################################################
Print("\n=== SUMMARY: prime factorization at each stage, per m ===\n");
FactStr := function(n)
  if n = 0 then return "0"; fi;
  return String(FactorsInt(n));
end;;
for row in LEDGER_ROWS do
  Print("m=", row.m, ":\n");
  Print("  xi_raw=", row.post_xi_raw, " = ", FactStr(row.post_xi_raw), "\n");
  Print("  in_derived=", row.post_xi_in_derived, " = ", FactStr(row.post_xi_in_derived), "\n");
  Print("  theta_inv=", row.post_xi_theta_inv, " = ", FactStr(row.post_xi_theta_inv), "\n");
  Print("  r_tau=", row.post_xi_r_tau, " = ", FactStr(row.post_xi_r_tau), "\n");
  Print("  generation=", row.post_xi_generation, " = ", FactStr(row.post_xi_generation), "\n");
  Print("  bq_settled=", row.post_xi_bq_settled, " = ", FactStr(row.post_xi_bq_settled), "\n");
od;

#############################################################################
## ---------------------- write JSON -------------------------------------------
#############################################################################
RowJson := function(r)
  return Concatenation("  {\n",
    "    \"m\":", String(r.m), ",\n",
    "    \"u\":", String(r.u), ",\n",
    "    \"pre_xi\": {\"legacy_pp_reference_NOT_enumerated\":", String(r.pre_xi_legacy_pp), "},\n",
    "    \"post_xi\": {\n",
    "      \"xi_raw\":", String(r.post_xi_raw), ",\n",
    "      \"in_derived\":", String(r.post_xi_in_derived), ",\n",
    "      \"theta_inv\":", String(r.post_xi_theta_inv), ",\n",
    "      \"r_tau\":", String(r.post_xi_r_tau), ",\n",
    "      \"generation\":", String(r.post_xi_generation), ",\n",
    "      \"bq_settled\":", String(r.post_xi_bq_settled), "\n",
    "    }\n",
    "  }");
end;;

outParts := [];;
Add(outParts, "{\n");
Add(outParts, "  \"generated_by\": \"search/a18-filter-ledger.g\",\n");
Add(outParts, "  \"note\": \"filter ledger for W-D-A18-13a: per-charming-m stage survivor counts. pre_xi is a reference figure only (|[P,P]|, never enumerated); post_xi are the real, actually-computed per-stage counts from the Prop 3.1 restricted scan. NOT a ledger claim, no cross-check performed.\",\n");
Add(outParts, Concatenation("  \"charming_count\": ", String(Length(ch)), ",\n"));
Add(outParts, Concatenation("  \"stab_order\": ", String(Length(stabElts)), ",\n"));
Add(outParts, "  \"rows\": [\n");
for i in [1 .. Length(LEDGER_ROWS)] do
  Add(outParts, RowJson(LEDGER_ROWS[i]));
  if i < Length(LEDGER_ROWS) then Add(outParts, ",\n"); else Add(outParts, "\n"); fi;
od;
Add(outParts, "  ]\n");
Add(outParts, "}\n");

WriteFile("search/certs/a18_filter_ledger_20260729.json", Concatenation(outParts));
Print("\nWrote search/certs/a18_filter_ledger_20260729.json\n");
Print("A18_FILTER_LEDGER_DONE\n");
