#!/usr/bin/env python3
"""Task 134 producer: noncommutative-kernel survival inventory and sweep.

Public inputs only:
  * the frozen 972 normal-form tuple list;
  * public K9/S4 certificates;
  * the truncated Magnus algebra F_2<X,Y>/(degree >= 5).

The script never reads sealed values.  It writes an atomic checkpoint and one
raw JSON certificate.  It has a wall-clock timeout and fails closed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import platform
import sys
import tempfile
import time
from collections import Counter, deque
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "search/certs/nf972_sourcemap_a_tuples_v2_20260804.json"
DEFAULT_OUTPUT = ROOT / "search/certs/d972_survival_noncomm_v1_20260815.json"
DEFAULT_CHECKPOINT = ROOT / "search/certs/.d972_survival_noncomm_v1_checkpoint.json"
K9_CERT = ROOT / "certificates/K9.v1.json"
S4_CERT = ROOT / "certificates/S4.v2.json"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def canonical_sha(obj: object) -> str:
    raw = json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def atomic_json(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            json.dump(obj, fh, ensure_ascii=False, sort_keys=True, indent=2)
            fh.write("\n")
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except FileNotFoundError:
            pass
        raise


class Deadline:
    def __init__(self, seconds: float):
        self.started = time.monotonic()
        self.seconds = seconds

    def check(self, stage: str) -> None:
        if time.monotonic() - self.started > self.seconds:
            raise TimeoutError(f"hard timeout at stage {stage}")

    def elapsed_ms(self) -> int:
        return round((time.monotonic() - self.started) * 1000)


class Magnus2:
    """Units generated by 1+X,1+Y in the degree-truncated algebra over F2.

    An element is the augmentation part of a unit, encoded as a bit mask; zero
    is the group identity.  Native multiplication is (1+a)(1+b)=1+a+b+ab.
    """

    def __init__(self, cutoff: int):
        if cutoff < 2:
            raise ValueError("cutoff must be at least 2")
        self.cutoff = cutoff
        self.words: list[tuple[int, int]] = []
        self.index: dict[tuple[int, int], int] = {}
        for length in range(1, cutoff):
            for value in range(1 << length):
                self.index[(length, value)] = len(self.words)
                self.words.append((length, value))
        self.x = 1 << self.index[(1, 0)]
        self.y = 1 << self.index[(1, 1)]
        self._terms_cache: dict[int, tuple[int, ...]] = {0: ()}

    def terms(self, a: int) -> tuple[int, ...]:
        got = self._terms_cache.get(a)
        if got is None:
            got = tuple(i for i in range(len(self.words)) if (a >> i) & 1)
            self._terms_cache[a] = got
        return got

    def mul(self, a: int, b: int) -> int:
        c = a ^ b
        for i in self.terms(a):
            length_a, word_a = self.words[i]
            for j in self.terms(b):
                length_b, word_b = self.words[j]
                length = length_a + length_b
                if length < self.cutoff:
                    word = (word_a << length_b) | word_b
                    c ^= 1 << self.index[(length, word)]
        return c

    def power(self, a: int, exponent: int) -> int:
        if exponent < 0:
            return self.power(self.inverse(a), -exponent)
        out = 0
        base = a
        n = exponent
        while n:
            if n & 1:
                out = self.mul(out, base)
            base = self.mul(base, base)
            n >>= 1
        return out

    def order(self, a: int) -> int:
        out = 0
        for n in range(1, 65):
            out = self.mul(out, a)
            if out == 0:
                return n
        raise AssertionError("element order exceeded bound")

    def inverse(self, a: int) -> int:
        return self.power(a, self.order(a) - 1)

    def commutator(self, a: int, b: int) -> int:
        return self.mul(self.mul(self.mul(self.inverse(a), self.inverse(b)), a), b)

    def closure(self, generators: list[int] | tuple[int, ...] | set[int]) -> set[int]:
        gs: list[int] = []
        for g in generators:
            gs.extend((g, self.inverse(g)))
        seen = {0}
        todo = deque([0])
        while todo:
            a = todo.popleft()
            for g in gs:
                b = self.mul(a, g)
                if b not in seen:
                    seen.add(b)
                    todo.append(b)
        return seen

    def enumerate_marked(self, deadline: Deadline):
        x, y = self.x, self.y
        xi, yi = self.inverse(x), self.inverse(y)
        generator_order = self.order(x)
        generators = (x, y, xi, yi)
        exp_delta = ((1, 0), (0, 1), (-1, 0), (0, -1))

        theta_generators = (y, x, yi, xi)
        tau_x = y
        tau_y = self.inverse(self.mul(x, y))
        tau_generators = (tau_x, tau_y, self.inverse(tau_x), self.inverse(tau_y))

        exponents = {0: (0, 0)}
        theta = {0: 0}
        tau = {0: 0}
        todo = deque([0])
        steps = 0
        while todo:
            a = todo.popleft()
            ea = exponents[a]
            for g, tg, ug, de in zip(generators, theta_generators, tau_generators, exp_delta):
                b = self.mul(a, g)
                eb = ((ea[0] + de[0]) % generator_order, (ea[1] + de[1]) % generator_order)
                tb = self.mul(theta[a], tg)
                ub = self.mul(tau[a], ug)
                if b in exponents:
                    if exponents[b] != eb or theta[b] != tb or tau[b] != ub:
                        raise AssertionError("marked BFS collision inconsistency")
                else:
                    exponents[b] = eb
                    theta[b] = tb
                    tau[b] = ub
                    todo.append(b)
            steps += 1
            if (steps & 511) == 0:
                deadline.check(f"enumerate_cutoff_{self.cutoff}")

        if len(set(theta.values())) != len(exponents) or len(set(tau.values())) != len(exponents):
            raise AssertionError("theta/tau is not bijective")
        if any(theta[theta[a]] != a for a in exponents):
            raise AssertionError("theta^2 != identity")
        if any(tau[tau[tau[a]]] != a for a in exponents):
            raise AssertionError("tau^3 != identity")
        return exponents, theta, tau, generator_order


def subgroup_generators(group: Magnus2, subgroup: set[int]) -> list[int]:
    chosen: list[int] = []
    generated = {0}
    for a in sorted(subgroup):
        if a not in generated:
            chosen.append(a)
            generated = group.closure(chosen)
    if generated != subgroup:
        raise AssertionError("subgroup generator extraction failed")
    return chosen


def quotient_representatives(group: Magnus2, whole: set[int], normal: set[int]) -> list[int]:
    unseen = set(whole)
    reps: list[int] = []
    while unseen:
        r = min(unseen)
        coset = {group.mul(r, h) for h in normal}
        if len(coset) != len(normal):
            raise AssertionError("coset size mismatch")
        reps.append(r)
        unseen.difference_update(coset)
    return reps


def abelian_2power_invariants(
    group: Magnus2, whole: set[int], derived: set[int]
) -> tuple[list[int], Counter[int]]:
    reps = quotient_representatives(group, whole, derived)
    order_hist: Counter[int] = Counter()
    for a in reps:
        for order in (1, 2, 4, 8, 16):
            if group.power(a, order) in derived:
                order_hist[order] += 1
                break
        else:
            raise AssertionError("abelian quotient exponent exceeded bound")
    total_log = int(math.log2(len(reps)))
    if sum(order_hist[o] for o in (1, 2)) == len(reps):
        return [2] * total_log, order_hist
    if sum(order_hist[o] for o in (1, 2, 4)) == len(reps):
        rank_mod2 = int(math.log2(sum(order_hist[o] for o in (1, 2))))
        rank4 = total_log - rank_mod2
        rank2 = rank_mod2 - rank4
        return [2] * rank2 + [4] * rank4, order_hist
    raise AssertionError("unexpected abelian quotient exponent")


def d9_mul(a: tuple[int, int], b: tuple[int, int]) -> tuple[int, int]:
    aa, ae = a
    ba, be = b
    return ((aa + (-ba if ae else ba)) % 9, (ae + be) % 2)


def d9_inv(a: tuple[int, int]) -> tuple[int, int]:
    aa, ae = a
    return (((-aa) if ae == 0 else aa) % 9, ae)


def g9_mul(a, b):
    return tuple(d9_mul(x, y) for x, y in zip(a, b))


def g9_inv(a):
    return tuple(d9_inv(x) for x in a)


def g9_comm(a, b):
    return g9_mul(g9_mul(g9_mul(g9_inv(a), g9_inv(b)), a), b)


def g9_closure(generators) -> set:
    identity = ((0, 0), (0, 0), (0, 0))
    gs = []
    for g in generators:
        gs.extend((g, g9_inv(g)))
    seen = {identity}
    todo = deque([identity])
    while todo:
        a = todo.popleft()
        for g in gs:
            b = g9_mul(a, g)
            if b not in seen:
                seen.add(b)
                todo.append(b)
    return seen


def audit_g9() -> dict:
    x = ((1, 0), (0, 1), (0, 1))
    y = ((1, 1), (1, 0), (1, 1))
    group = g9_closure((x, y))
    comm = g9_comm(x, y)
    conjugates = set()
    frontier = deque([comm])
    conjugates.add(comm)
    while frontier:
        a = frontier.popleft()
        for g in (x, y, g9_inv(x), g9_inv(y)):
            c = g9_mul(g9_mul(g9_inv(g), a), g)
            if c not in conjugates:
                conjugates.add(c)
                frontier.append(c)
    derived = g9_closure(conjugates)
    rotations = {a for a in group if all(e == 0 for _, e in a)}
    if len(group) != 2916 or derived != rotations or len(derived) != 729:
        raise AssertionError("G9 bridge audit failed")
    return {
        "order": len(group),
        "derived_order": len(derived),
        "abelianization": [2, 2],
        "maximal_2_quotient": "C2 x C2",
        "marked_bridge_basis": {
            "x": [0, 1, 1],
            "y": [1, 0, 1],
        },
    }


def infer_w_structure(group: Magnus2, all_elts, exponents, deadline: Deadline):
    wker = {
        a
        for a, (ex, ey) in exponents.items()
        if ex % 2 == 0 and ey % 2 == 0
    }
    generators = subgroup_generators(group, wker)
    derived = group.closure(
        [group.commutator(a, b) for a in generators for b in generators]
    )
    center = {
        a for a in wker if all(group.mul(a, g) == group.mul(g, a) for g in generators)
    }
    if not derived.issubset(center):
        raise AssertionError("W_ker is not class at most 2")
    invariants, quotient_order_hist = abelian_2power_invariants(group, wker, derived)
    element_order_hist = Counter(group.order(a) for a in wker)
    deadline.check("W_ker_structure")
    return wker, generators, derived, center, invariants, element_order_hist, quotient_order_hist


def write_checkpoint(path: Path, stage: str, deadline: Deadline, extra: dict | None = None) -> None:
    obj = {
        "schema": "d972-survival-noncomm-checkpoint/v1",
        "stage": stage,
        "elapsed_ms": deadline.elapsed_ms(),
        "complete": stage == "complete",
    }
    if extra:
        obj.update(extra)
    atomic_json(path, obj)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--hard-timeout-seconds", type=float, default=120.0)
    args = parser.parse_args()

    deadline = Deadline(args.hard_timeout_seconds)
    input_obj = json.loads(args.input.read_text(encoding="utf-8"))
    tuples = input_obj["tuples"]
    if input_obj.get("count") != 972 or len(tuples) != 972:
        raise AssertionError("frozen tuple input does not contain 972 entries")
    tuple_keys = {json.dumps(t, separators=(",", ":")) for t in tuples}
    if len(tuple_keys) != 972:
        raise AssertionError("frozen tuple input has duplicates")
    if any(any(int(pair[1]) != 0 for pair in t[1]) for t in tuples):
        raise AssertionError("a frozen G9 f-coordinate is outside G9 derived subgroup")

    s4 = json.loads(S4_CERT.read_text(encoding="utf-8"))
    if s4.get("universe", {}).get("derived_order") != 504:
        raise AssertionError("public PSL factor perfectness anchor failed")

    g9_audit = audit_g9()
    write_checkpoint(args.checkpoint, "bridge_audited", deadline)

    inventory = []
    selected = None
    for cutoff in range(2, 6):
        deadline.check(f"inventory_cutoff_{cutoff}")
        grp = Magnus2(cutoff)
        exps, theta, tau, generator_order = grp.enumerate_marked(deadline)
        wker = {a for a, (u, v) in exps.items() if u % 2 == 0 and v % 2 == 0}
        wker_abelian = all(grp.mul(a, b) == grp.mul(b, a) for a in wker for b in wker)
        row = {
            "route": "truncated_magnus_F2",
            "field": 2,
            "cutoff": cutoff,
            "P_order": len(exps),
            "P_generator_order": generator_order,
            "W_ker_order": len(wker),
            "W_ker_abelian": wker_abelian,
            "PB3_over_K_order": 1469664 * len(exps) // 4,
            "theta_order": 2,
            "tau_order": 3,
            "B3_normal_reason": "augmentation-ideal dimension subgroup is characteristic",
        }
        inventory.append(row)
        if selected is None and not wker_abelian:
            selected = (grp, exps, theta, tau, generator_order, row)
    if selected is None:
        raise AssertionError("no noncommutative relative kernel in frozen inventory")
    write_checkpoint(args.checkpoint, "inventory_complete", deadline, {"inventory_rows": len(inventory)})

    group, exponents, theta, tau, generator_order, selected_row = selected
    if selected_row["cutoff"] != 5 or len(exponents) != 8192 or generator_order != 8:
        raise AssertionError("first noncommutative candidate is not the frozen cutoff-5 candidate")

    wker, wgens, wderived, wcenter, wab_inv, w_order_hist, wab_order_hist = infer_w_structure(
        group, set(exponents), exponents, deadline
    )
    if len(wker) != 2048 or len(wderived) != 8 or len(wcenter) != 256:
        raise AssertionError("W_ker structural anchor mismatch")
    if wab_inv != [2, 2, 4, 4, 4]:
        raise AssertionError("W_ker abelianization invariant mismatch")

    squares_and_comm = group.closure(
        list(wderived) + [group.mul(a, a) for a in wker]
    )
    mod2_reps = quotient_representatives(group, wker, squares_and_comm)
    wab_reps = quotient_representatives(group, wker, wderived)
    if len(mod2_reps) != 32 or len(wab_reps) != 256:
        raise AssertionError("W_ker quotient size mismatch")

    def norm_counts(reps: list[int], modulus: set[int]) -> dict:
        theta_kernel = 0
        tau_norm_kernel = 0
        intersection = 0
        for a in reps:
            htheta = group.mul(a, theta[a]) in modulus
            atau = tau[a]
            atau2 = tau[atau]
            htau = group.mul(group.mul(a, atau), atau2) in modulus
            theta_kernel += int(htheta)
            tau_norm_kernel += int(htau)
            intersection += int(htheta and htau)
        return {
            "theta_kernel_size": theta_kernel,
            "tau_norm_kernel_size": tau_norm_kernel,
            "intersection_size": intersection,
        }

    mod2_norm = norm_counts(mod2_reps, squares_and_comm)
    wab_norm = norm_counts(wab_reps, wderived)
    if mod2_norm != {"theta_kernel_size": 8, "tau_norm_kernel_size": 16, "intersection_size": 4}:
        raise AssertionError("mod-2 pre-screen mismatch")
    d_value = int(math.log2(mod2_norm["intersection_size"]))
    if d_value != 2:
        raise AssertionError("pre-screen d mismatch")
    write_checkpoint(args.checkpoint, "prescreen_complete", deadline, {"d": d_value})

    # The bridge is abelian, and G9' (order 3^6) and P' (a 2-group) have no
    # nontrivial common quotient.  Hence E' = Q' x P'.  The f-fiber is P'.
    derived_p = {a for a, exp in exponents.items() if exp == (0, 0)}
    if len(derived_p) != 128:
        raise AssertionError("derived f-fiber size mismatch")
    derived_p_abelian = all(
        group.mul(a, b) == group.mul(b, a) for a in derived_p for b in derived_p
    )
    if not derived_p_abelian:
        raise AssertionError("derived f-fiber expected abelian")

    base_m_counts = Counter(int(t[0]) for t in tuples)
    if sorted(base_m_counts) != [0, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17]:
        raise AssertionError("unexpected frozen m support")
    if set(base_m_counts.values()) != {81}:
        raise AssertionError("unexpected frozen m multiplicities")

    # Selection is the full frozen list.  It cannot be changed by an outcome.
    selection = {
        "rule": "all entries of the frozen NF tuple list in stored order",
        "k": 972,
        "engineering_probe_before_versioned_freeze": True,
        "preregistration_blind": False,
        "outcome_adaptive": False,
        "scope_note": "the full 972-element universe is used, so no target can be reselected or omitted",
        "input_tuple_set_sha256": canonical_sha(sorted(tuple_keys)),
        "first_tuple": tuples[0],
        "last_tuple": tuples[-1],
    }

    per_m = {}
    target_survival_counts = []
    direct_generation_fixtures = []
    for base_m in sorted(base_m_counts):
        deadline.check(f"survival_m_{base_m}")
        compatible_m = [
            fine_m
            for fine_m in range(72)
            if fine_m % 18 == base_m % 18 and math.gcd(2 * fine_m + 1, 72) == 1
        ]
        # Canonical (3.60): reduction preserves the m coordinate modulo the
        # target order 18.  Equality of 2m+1 alone is not a substitute.
        if len(compatible_m) != 4:
            raise AssertionError("compatible m-fiber size mismatch")
        fine_rows = []
        total_pass = 0
        for fine_m in compatible_m:
            hex1_count = 0
            hex2_count = 0
            both_count = 0
            surj_count = 0
            first_both = None
            ypow = group.power(group.y, fine_m)
            for index, f in enumerate(sorted(derived_p)):
                h1 = group.mul(theta[f], f) == 0
                ymf = group.mul(f, ypow)  # AbstractProd([y^m,f]) in the project convention.
                tau1 = tau[ymf]
                tau2 = tau[tau1]
                h2 = group.mul(group.mul(ymf, tau1), tau2) == 0

                # Exhaustive Frattini-quotient generation test.  Since u is
                # odd, the two images are the marked basis of P/Phi(P).
                u = 2 * fine_m + 1
                gen_a_vector = (u % 2, 0)
                gen_b_vector = (0, u % 2)
                surj = gen_a_vector == (1, 0) and gen_b_vector == (0, 1)
                hex1_count += int(h1)
                hex2_count += int(h2)
                surj_count += int(surj)
                if h1 and h2 and surj:
                    both_count += 1
                    if first_both is None:
                        first_both = f
                if (index & 63) == 0:
                    deadline.check(f"survival_m_{base_m}_{fine_m}")
            if (hex1_count, hex2_count, both_count, surj_count) != (32, 16, 4, 128):
                raise AssertionError("per-fine-m raw counter mismatch")

            # Direct finite generation fixture, separate from the Frattini
            # test: one surviving f for every compatible fine m.
            assert first_both is not None
            u = 2 * fine_m + 1
            gen_a = group.power(group.x, u)
            gen_b = group.mul(
                group.mul(first_both, group.power(group.y, u)),
                group.inverse(first_both),
            )
            generated_size = len(group.closure([gen_a, gen_b]))
            if generated_size != 8192:
                raise AssertionError("direct generation fixture failed")
            direct_generation_fixtures.append(
                {"base_m": base_m, "fine_m": fine_m, "generated_order": generated_size}
            )
            fine_rows.append(
                {
                    "fine_m": fine_m,
                    "fiber_denominator": 128,
                    "hex310_count": hex1_count,
                    "hex311_count": hex2_count,
                    "both_and_surjective_count": both_count,
                    "surjective_count": surj_count,
                }
            )
            total_pass += both_count
        if total_pass != 16:
            raise AssertionError("per-target survival total mismatch")
        per_m[str(base_m)] = {
            "target_count": base_m_counts[base_m],
            "compatible_fine_m": compatible_m,
            "pair_denominator_per_target": 4 * len(derived_p),
            "survival_count_per_target": total_pass,
            "fine_rows": fine_rows,
        }
        target_survival_counts.extend([total_pass] * base_m_counts[base_m])

    survival_distribution = Counter(target_survival_counts)
    if survival_distribution != Counter({16: 972}):
        raise AssertionError("target survival distribution mismatch")
    target_nonzero_count = sum(v > 0 for v in target_survival_counts)
    if target_nonzero_count < 324:
        raise AssertionError("positive-control minimum violated")
    write_checkpoint(
        args.checkpoint,
        "survival_complete",
        deadline,
        {"targets": 972, "nonzero_targets": target_nonzero_count},
    )

    cert = {
        "schema": "d972-survival-noncomm/v1",
        "generated_at_local_date": "2026-08-15",
        "generated_by": {
            "script": "search/d972_survival_noncomm_v1.py",
            "python": platform.python_version(),
            "platform": platform.platform(),
        },
        "status": "completed",
        "stage_reached": 4,
        "scope": {
            "base_window": "M = K^(9) intersection N_S4",
            "base_quotient_order": 1469664,
            "base_shadow_count": 972,
            "sealed_values_touched": False,
            "endgame_scope": "gentle_only; B4 escalation requires PENT_W-PASS then FAKE-KILL^{B4}/U-10",
        },
        "inputs": {
            "nf_tuples": {
                "path": str(args.input.relative_to(ROOT)).replace("\\", "/"),
                "sha256": sha256_file(args.input),
                "count": len(tuples),
            },
            "K9_cert": {
                "path": "certificates/K9.v1.json",
                "sha256": sha256_file(K9_CERT),
            },
            "S4_cert": {
                "path": "certificates/S4.v2.json",
                "sha256": sha256_file(S4_CERT),
            },
        },
        "failed_or_deferred_routes": [
            {
                "route": "GAP_lins",
                "status": "not_constructed",
                "reason": "M has index 1469664 in F2 and a Reidemeister-Schreier presentation has rank 1469665; direct low-index enumeration is beyond the local representation budget",
            },
            {
                "route": "GQuotients_noncentral_extension_of_PSL2_8",
                "status": "not_constructed",
                "reason": "the known order-32256 extension has elementary abelian relative kernel; no bounded noncentral target list was supplied for a noncommutative relative kernel",
            },
            {
                "route": "GAP_ANUPQ_probe",
                "status": "environment_startup_failure",
                "attempts": 2,
                "command": ".\\gap.ps1 search\\d972_survival_noncomm_inventory_v1.g",
                "exit_code": 1,
                "error": "gap.exe could not create signal pipe (Win32 error 5) before reading the script",
            },
        ],
        "g9_bridge_audit": g9_audit,
        "inventory": inventory,
        "candidate": {
            "selection_rule": "field 2; increasing cutoff; first noncommutative W_ker",
            "cutoff": 5,
            "construction": "image of F2 under x->1+X, y->1+Y in F2<X,Y>/(degree>=5)",
            "characteristic_kernel": "D_5(F2) = {g : g-1 lies in augmentation ideal degree >=5}",
            "K_definition": "K = M intersection preimage(D_5(F2)) in PB3",
            "PB3_over_K_order": 3009871872,
            "projection_to_M_exists": True,
            "projection_image_order": 1469664,
            "bridge": "C2 x C2 with marked x,y basis",
            "W_ker": {
                "order": len(wker),
                "abelian": False,
                "nilpotency_class": 2,
                "exponent": max(w_order_hist),
                "minimal_generator_number": len(wgens),
                "derived_order": len(wderived),
                "center_order": len(wcenter),
                "abelianization_invariants": wab_inv,
                "element_order_histogram": {str(k): v for k, v in sorted(w_order_hist.items())},
                "abelianization_order_histogram": {str(k): v for k, v in sorted(wab_order_hist.items())},
                "small_group_id": None,
                "small_group_id_reason": "order 2048 is outside the complete SmallGroups identification range",
            },
        },
        "blind_family_audit": [
            {"family": 1, "applies": False, "reason": "source is a nontrivial fiber product over C2 x C2; its order is product_order/4"},
            {"family": 2, "applies": False, "reason": "K is not K^(l) intersection N_S4"},
            {"family": 3, "applies": False, "reason": "the added quotient is a finite 2-group, not a perfect-group window"},
            {"family": 4, "applies": False, "reason": "the bridge is C2 x C2 and W_ker is noncommutative, not the abelian C3 bridge"},
            {"family": 5, "applies": False, "reason": "there is no one-sided-trivial abelian module V"},
            {"family": 6, "applies": False, "reason": "there is no tensor-only F3 module"},
            {"family": 7, "applies": False, "reason": "the p-not-3 coefficient theorem assumes an abelian normal kernel; W_ker is noncommutative"},
        ],
        "prescreen": {
            "W_ker_ab_order": len(wab_reps),
            "W_ker_ab_invariants": wab_inv,
            "mod2_quotient_dimension": 5,
            "mod2": {**mod2_norm, "d": d_value},
            "exact_abelianization": wab_norm,
            "forced_total_vanishing": False,
            "action_checks": {"theta_squared_identity": True, "tau_cubed_identity": True},
        },
        "survival_sweep": {
            "selection": selection,
            "prop34_reduction": {
                "used": True,
                "derived_fiber_order": len(derived_p),
                "derived_fiber_abelian": derived_p_abelian,
                "fiber_subset_of_fine_derived": True,
                "generation_test": f"exhaustive marked-basis test in P/Phi(P), plus direct subgroup closures for all {len(direct_generation_fixtures)} compatible fine-m cells",
                "direct_generation_fixture_count": len(direct_generation_fixtures),
                "direct_generation_fixture_orders": sorted(set(r["generated_order"] for r in direct_generation_fixtures)),
            },
            "fine_order": 72,
            "base_order": 18,
            "f_fiber_denominator": len(derived_p),
            "compatible_m_count_per_target": 4,
            "pair_denominator_per_target": 4 * len(derived_p),
            "per_m": per_m,
            "target_survival_distribution": {str(k): v for k, v in sorted(survival_distribution.items())},
            "target_nonzero_count": target_nonzero_count,
            "positive_control_minimum": 324,
            "positive_control_pass": target_nonzero_count >= 324,
            "zero_survival_target_count": sum(v == 0 for v in target_survival_counts),
        },
        "runtime": {
            "hard_timeout_seconds": args.hard_timeout_seconds,
            "wall_ms": deadline.elapsed_ms(),
            "checkpoint": str(args.checkpoint.relative_to(ROOT)).replace("\\", "/"),
        },
        "grading": {
            "producer": "candidate",
            "independent_checker_required": True,
            "lean_certificate": False,
        },
    }
    atomic_json(args.output, cert)
    write_checkpoint(
        args.checkpoint,
        "complete",
        deadline,
        {"output": str(args.output.relative_to(ROOT)).replace("\\", "/"), "output_sha256": sha256_file(args.output)},
    )
    print(json.dumps({
        "status": "completed",
        "output": str(args.output),
        "W_ker_order": len(wker),
        "d": d_value,
        "survival_distribution": dict(survival_distribution),
        "wall_ms": deadline.elapsed_ms(),
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        code = main()
    except Exception as exc:
        print(f"INTEGRITY_STOP: {type(exc).__name__}: {exc}", file=sys.stderr)
        raise
    raise SystemExit(code)
