#!/usr/bin/env python3
"""Exact, shardable Magnus ideal generation for degree 6/7 B4 inputs.

The unsharded producer is deliberately simple and receipt-oriented, but its
tuple concatenation loop is expensive at degree five.  This version uses the
    same fixed monomial order and the same two-sided ideal, with monomials encoded
as base-6 integers.  A shard contains *all* left/right monomial multiples of
the relators assigned to it; the merge of the shard row spaces is therefore
exactly the ideal generated by all relators.  No roof word is evaluated here.

The file is intentionally self-contained in the algebraic core.  The normal
receipt checker rebuilds the ideal with a set-of-tuples implementation, so a
    bug in this accelerator cannot silently become a proof.  The v2 file is
    deliberately separate so the frozen degree-5 receipt retains its v1
    source hash.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from array import array
from pathlib import Path
from typing import Iterable, Sequence


NGEN = 6
RELATOR_COUNT = 158
ROOF_COUNT = 972
TARGET_KEY_DIGEST = (
    "9c77e6768feb7ffe7143abf18f753af70e81b8e9cc792910c30ae0075d3b1d62"
)
CANONICAL_RHO = [[-6, -5, -3], [3], [5], [-3, -2, -1], [-5, -4, -1], [1]]
CHUNK_BITS = 4
CHUNK_SIZE = 1 << CHUNK_BITS
MAX_DEGREE = 7


def canonical_json(value: object) -> bytes:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":")).encode("ascii")


def sha_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def file_sha(path: Path) -> str:
    return sha_bytes(path.read_bytes())


def powers_and_offsets(d: int) -> tuple[list[int], list[int]]:
    powers = [1]
    for _ in range(d):
        powers.append(powers[-1] * NGEN)
    offsets = [0]
    for length in range(d):
        offsets.append(offsets[-1] + powers[length])
    return powers, offsets


def monomial_count(d: int) -> int:
    return sum(NGEN ** n for n in range(d + 1))


def append_maps(d: int, powers: Sequence[int], offsets: Sequence[int]) -> list[list[int]]:
    """Index map for right multiplication by X_g in the fixed order."""
    count = monomial_count(d)
    # Degree 6 has 55,987 monomials.  Packed int32 maps keep each worker
    # small enough for a wide GHA matrix; Python-int lists would cost ~160 MB
    # before row reduction begins.
    result = [array("i", [-1]) * count for _ in range(NGEN)]
    for length in range(d):
        for code in range(powers[length]):
            old = offsets[length] + code
            for g in range(NGEN):
                result[g][old] = offsets[length + 1] + code * NGEN + g
    return result


def append_bits(poly: int, amap: Sequence[int]) -> int:
    out = 0
    bits = poly
    while bits:
        low = bits & -bits
        old = low.bit_length() - 1
        new = amap[old]
        if new >= 0:
            out ^= 1 << new
        bits ^= low
    return out


def chunk_tables(d: int, powers: Sequence[int], offsets: Sequence[int]) -> list[list[list[list[int]]]]:
    """Small exact lookup tables for the monomial append permutation.

    The table chunks four source coefficients at a time.  It is deliberately
    modest (under 40k small entries at d=5), while reducing the hot append
    loop from one Python iteration per set monomial to one per four source
    positions.  Values are still ordinary Python integers, so no arithmetic
    leaves F_2 or the lossless bitset representation.
    """
    tables: list[list[list[list[int]]]] = []
    for length in range(d):
        chunk_count = (powers[length] + CHUNK_BITS - 1) // CHUNK_BITS
        by_generator: list[list[list[int]]] = []
        for g in range(NGEN):
            by_chunk: list[list[int]] = []
            for chunk in range(chunk_count):
                values = [0] * CHUNK_SIZE
                first_code = chunk * CHUNK_BITS
                for mask in range(1, CHUNK_SIZE):
                    low = mask & -mask
                    bit = low.bit_length() - 1
                    previous = values[mask ^ low]
                    code = first_code + bit
                    if code < powers[length]:
                        target = offsets[length + 1] + code * NGEN + g
                        values[mask] = previous ^ (1 << target)
                    else:
                        values[mask] = previous
                by_chunk.append(values)
            by_generator.append(by_chunk)
        tables.append(by_generator)
    return tables


def append_bits_chunked(poly: int, generator: int, d: int,
                        powers: Sequence[int], offsets: Sequence[int],
                        tables: Sequence[Sequence[Sequence[Sequence[int]]]]) -> int:
    out = 0
    for length in range(d):
        block = (poly >> offsets[length]) & ((1 << powers[length]) - 1)
        for chunk, values in enumerate(tables[length][generator]):
            mask = (block >> (chunk * CHUNK_BITS)) & (CHUNK_SIZE - 1)
            if mask:
                out ^= values[mask]
    return out


def eval_word(word: Iterable[int], d: int, maps: Sequence[Sequence[int]]) -> int:
    """Evaluate a signed word at g_i=1+X_i over F_2."""
    poly = 1
    for raw in word:
        letter = int(raw)
        if letter == 0 or abs(letter) > NGEN:
            raise ValueError(f"invalid signed generator {letter}")
        amap = maps[abs(letter) - 1]
        if letter > 0:
            # (1+X) times poly; the constant term is essential.
            poly ^= append_bits(poly, amap)
        else:
            # (1+X)^-1 = 1+X+...+X^d in characteristic two.
            total = poly
            power = poly
            for _ in range(d):
                power = append_bits(power, amap)
                total ^= power
            poly = total
    return poly


def eval_word_chunked(word: Iterable[int], d: int, powers: Sequence[int], offsets: Sequence[int],
                      tables: Sequence[Sequence[Sequence[Sequence[int]]]]) -> int:
    """The same evaluator using the exact chunked append permutation."""
    poly = 1
    for raw in word:
        letter = int(raw)
        if letter == 0 or abs(letter) > NGEN:
            raise ValueError(f"invalid signed generator {letter}")
        generator = abs(letter) - 1
        if letter > 0:
            poly ^= append_bits_chunked(poly, generator, d, powers, offsets, tables)
        else:
            total = poly
            power = poly
            for _ in range(d):
                power = append_bits_chunked(power, generator, d, powers, offsets, tables)
                total ^= power
            poly = total
    return poly


def set_bits(poly: int):
    while poly:
        low = poly & -poly
        yield low.bit_length() - 1
        poly ^= low


def add_high_basis(basis: dict[int, int], row: int) -> None:
    """Insert a row into highest-pivot F_2 echelon form."""
    while row:
        pivot = row.bit_length() - 1
        old = basis.get(pivot)
        if old is None:
            basis[pivot] = row
            return
        row ^= old


def _relation_groups(poly: int, offsets: Sequence[int], powers: Sequence[int]) -> tuple[dict[int, list[int]], int]:
    groups: dict[int, list[int]] = {}
    min_degree = 10**9
    for index in set_bits(poly):
        degree = 0
        # d <= 5, so this short loop is cheaper and less error prone than a
        # second global index-to-degree table in the receipt path.
        while not (offsets[degree] <= index < offsets[degree] + powers[degree]):
            degree += 1
        code = index - offsets[degree]
        groups.setdefault(degree, []).append(code)
        min_degree = min(min_degree, degree)
    return groups, min_degree


def ideal_basis_encoded(rel_polys: Sequence[int], relator_indices: Sequence[int], d: int,
                        powers: Sequence[int], offsets: Sequence[int]) -> dict[int, int]:
    """Generate all u*(E(r)-1)*v rows for the assigned relators.

    A monomial of length l is represented by a base-6 code.  If the middle
    monomial has length m and code c, then

        code(left + middle + right)
          = left*6^(m+right) + c*6^right + right.

    This is exactly the fixed tuple lexicographic order used by the producer.
    """
    left_codes = [list(range(powers[n])) for n in range(d + 1)]
    basis: dict[int, int] = {}
    for relation, rel_index in zip(rel_polys, relator_indices):
        if relation == 0:
            continue
        groups, min_degree = _relation_groups(relation, offsets, powers)
        for total in range(d - min_degree + 1):
            for left_length in range(total + 1):
                right_length = total - left_length
                for left in left_codes[left_length]:
                    for right in left_codes[right_length]:
                        row = 0
                        for middle_length, middle_codes in groups.items():
                            if left_length + middle_length + right_length > d:
                                continue
                            middle_factor = powers[right_length]
                            left_base = offsets[left_length + middle_length + right_length]
                            left_base += left * powers[middle_length + right_length]
                            right_base = right
                            for middle in middle_codes:
                                index = left_base + middle * middle_factor + right_base
                                row ^= 1 << index
                        if row:
                            add_high_basis(basis, row)
        if rel_index % 10 == 0 or rel_index == RELATOR_COUNT:
            print(json.dumps({"event": "relator_done", "relator": rel_index,
                              "assigned_rows_rank": len(basis)}, sort_keys=True),
                  flush=True)
    return basis


def load_input(path: Path) -> tuple[dict[str, object], str, dict[str, str]]:
    obj = json.loads(path.read_text(encoding="utf-8"))
    if obj.get("schema") not in {"d972-b4-p2-magnus-input/v1",
                                  "d972-b4-p2-magnus-input/v2"}:
        raise ValueError("Magnus input schema drift")
    if len(obj.get("all_relators", [])) != RELATOR_COUNT:
        raise ValueError("exact relator count gate failed")
    if len(obj.get("roof_words", [])) != ROOF_COUNT:
        raise ValueError("exact roof count gate failed")
    if obj.get("target_key_digest") != TARGET_KEY_DIGEST:
        raise ValueError("frozen target-key digest gate failed")
    if obj.get("rho_words") != CANONICAL_RHO:
        raise ValueError("legacy rho map rejected; require universal_v2 canonical rho")
    if ("rho_words_source" in obj and
            obj.get("rho_words_source") != "universal_v2_canonical"):
        raise ValueError("rho_words_source is not universal_v2_canonical")
    rel_digest = sha_bytes(canonical_json(obj["all_relators"]))
    if obj.get("all_relators_sha256") != rel_digest:
        raise ValueError("relator digest metadata mismatch")
    roof_digest = sha_bytes(canonical_json(obj["roof_words"]))
    if obj.get("roof_words_sha256") != roof_digest:
        raise ValueError("roof digest metadata mismatch")
    rho_digest = sha_bytes(canonical_json(obj["rho_words"]))
    if ("rho_words_sha256" in obj and obj.get("rho_words_sha256") != rho_digest):
        raise ValueError("rho digest metadata mismatch")
    return obj, file_sha(path), {"all_relators_sha256": rel_digest,
                                 "roof_words_sha256": roof_digest,
                                 "rho_words_sha256": rho_digest,
                                 "target_key_digest": str(obj["target_key_digest"])}


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--degree", type=int, default=5)
    ap.add_argument("--shard-index", type=int, required=True,
                    help="zero-based shard index")
    ap.add_argument("--shard-count", type=int, required=True,
                    help="total number of disjoint shards")
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args(argv)
    if args.degree < 1 or args.degree > MAX_DEGREE:
        raise ValueError(f"degree must be in 1..{MAX_DEGREE}")
    if args.shard_count < 1 or not (0 <= args.shard_index < args.shard_count):
        raise ValueError("invalid shard index/count")
    obj, input_sha, digests = load_input(args.input)
    powers, offsets = powers_and_offsets(args.degree)
    maps = append_maps(args.degree, powers, offsets)
    all_rels = [[int(x) for x in w] for w in obj["all_relators"]]  # type: ignore[index]
    assigned = [i for i in range(RELATOR_COUNT) if i % args.shard_count == args.shard_index]
    assigned_rels = [all_rels[i] for i in assigned]
    print(json.dumps({"event": "start", "degree": args.degree,
                      "shard_index": args.shard_index, "shard_count": args.shard_count,
                      "relator_count": len(assigned)}, sort_keys=True), flush=True)
    started = time.monotonic()
    rel_polys = [eval_word(w, args.degree, maps) ^ 1 for w in assigned_rels]
    basis = ideal_basis_encoded(rel_polys, [i + 1 for i in assigned], args.degree,
                                powers, offsets)
    rows = [format(basis[p], "x") for p in sorted(basis)]
    result: dict[str, object] = {
        "schema": "d972-b4-magnus-ideal-shard/v2",
        "status": "CANDIDATE_SHARD",
        "degree": args.degree,
        "shard_index": args.shard_index,
        "shard_count": args.shard_count,
        "relator_indices": [i + 1 for i in assigned],
        "relator_indices_sha256": sha_bytes(canonical_json([i + 1 for i in assigned])),
        "monomial_count": monomial_count(args.degree),
        "ideal_rank": len(basis),
        "ideal_basis_hex": rows,
        "ideal_basis_pivots": sorted(basis),
        "input_path": str(args.input),
        "input_sha256": input_sha,
        "input_digests": digests,
        "encoding": {"alphabet_size": NGEN, "order": "length then lexicographic",
                      "index": "offset[length]+base6_code"},
        "method": "complete two-sided monomial ideal span; encoded accelerator v2",
        "elapsed_seconds": round(time.monotonic() - started, 3),
        "source": {"script": str(Path(__file__)), "sha256": file_sha(Path(__file__))},
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=True, sort_keys=True, indent=2) + "\n",
                            encoding="utf-8")
    print(json.dumps({"event": "done", "degree": args.degree,
                      "shard_index": args.shard_index, "ideal_rank": len(basis),
                      "output": str(args.output),
                      "elapsed_seconds": result["elapsed_seconds"]}, sort_keys=True), flush=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(json.dumps({"status": "ERROR", "error": str(exc)}, sort_keys=True),
              file=sys.stderr, flush=True)
        raise
