#!/usr/bin/env python3
"""Task452-carrier-fed exact task193-v4 mathematical compiler."""
from __future__ import annotations
import argparse,hashlib,importlib.util,json,os,stat
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];SCHEMA="d972-r07-second-frattini-affine-prefix-compiler/v5";COMMON="R07_SECOND_FRATTINI_AFFINE_PREFIX_COMPILER_V5";UNKNOWN_INPUT="UNKNOWN_INPUT";UNKNOWN_RESOURCE="UNKNOWN_RESOURCE"
CARRIER=("search/d972_r07_task451_task193_carrier_v1.py",8553,"18c4932cbff5fbd5885ea03e80cd7f5c9f9c10bdbf4c7cc043985d3196042644");CCHECK=("crosscheck/check_d972_r07_task451_task193_carrier_v1.py",8516,"82c5e7caa314e530782843bef81e66c431198fdc2d1c479886a14166f0fa1e73");CDRIVER=("search/d972_r07_task451_task193_carrier_gha_driver_v1.g",2499,"cdf8f4276740a18fc312de3dfca8669a0c8afd424d2551f00596e6d63251cf6a");V4=("search/d972_r07_second_frattini_affine_prefix_compiler_v4.py",2851,"a6e1d54c1c656ab496ed54e6bcac5fa8c027edc5686fa913c86cc1c0fe349d1a");V4C=("crosscheck/check_d972_r07_second_frattini_affine_prefix_compiler_v4.py",2986,"04f7c7df3395e841a21fe75fec71bd5fef1f35a4fbc4c0e642b5db7fa31e390d");V4D=("search/d972_r07_second_frattini_affine_prefix_compiler_gha_driver_v4.g",5798,"7447b2da4c83ba0f9818a3ea355636310368b22c8585e6b95632100894dfafb4")
def need(x,m):
 if not x:raise RuntimeError(m)
def sha(x):return hashlib.sha256(x).hexdigest()
def canon(x):return json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=True).encode("ascii")
def seal(x):y=dict(x);y.pop("self_digest",None);y["self_digest"]=sha(canon(y));return y
def checkseal(x,l):y=dict(x);h=y.pop("self_digest",None);need(isinstance(h,str) and h==sha(canon(y)),l+" seal")
def raw(s):b=(ROOT/s[0]).read_bytes();need(len(b)==s[1] and sha(b)==s[2],"pin:"+s[0]);return b
def load(s,n):raw(s);p=ROOT/s[0];q=importlib.util.spec_from_file_location(n,p);need(q and q.loader,"loader");m=importlib.util.module_from_spec(q);q.loader.exec_module(m);return m
def readj(name):
 p=Path(name);p=p if p.is_absolute() else ROOT/p;p=p.resolve();p.relative_to(ROOT.resolve());need(not p.is_symlink(),"symlink");b=p.read_bytes();x=json.loads(b);need(type(x)is dict and b==canon(x)+b"\n","canonical json");return x,{"path":str(p.relative_to(ROOT)).replace("\\","/"),"bytes":len(b),"sha256":sha(b)}
def red(w):
 o=[]
 for x in w:
  need(type(x)is int and x and abs(x)<=2,"F2 word")
  if o and o[-1]==-x:o.pop()
  else:o.append(x)
 return o
def legacy(row):
 h=hashlib.sha256();p=None
 for k,c in row:
  b=bytes.fromhex(k);need(p is None or p<b,"sparse order");p=b;need(c in(1,2),"coefficient");h.update(len(b).to_bytes(4,"big"));h.update(b);h.update(bytes((c,)))
 return h.hexdigest()
def short(x):return {k:x[k] for k in("path","bytes","sha256")}
def firewall(c,v,ci,vi):
 checkseal(c,"carrier");checkseal(v,"verdict");need(c.get("schema")=="d972-r07-task451-task193-carrier/v1" and c.get("status")=="ACCEPTED" and c.get("terminal")=="R07_TASK451_TASK193_CARRIER_V1_ACCEPTED" and c.get("claims")=={"carrier":True,"A2":False,"lift":False,"fake":False,"Ihara":False},"carrier envelope");need(v.get("schema")=="d972-r07-task451-task193-carrier/v1/checker" and v.get("status")=="PASS" and v.get("terminal")=="R07_TASK451_TASK193_CARRIER_V1_CHECKER_PASS" and v.get("carrier")==ci and v.get("claims")=={"literal_carrier_replayed":True,"A2":False,"lift":False,"fake":False,"Ihara":False},"verdict envelope")
 need(c.get("pins")=={"producer":dict(zip(("path","bytes","sha256"),("search/d972_r07_a0_dual_anchored_active_batch_v1.py",13834,"ca7fb15e06dd04881146c38d63d93015a9e630fbc334cf15098cbd8a32f22f9b"))),"checker":dict(zip(("path","bytes","sha256"),("crosscheck/check_d972_r07_a0_dual_anchored_active_batch_v1.py",13725,"5c2f76b825bd920245d0200f29ff860ba93a32663ef5db9567bc499a86f7ff8a"))),"driver":dict(zip(("path","bytes","sha256"),("search/d972_r07_a0_dual_anchored_active_batch_gha_driver_v1.g",2569,"6910d38adc56a564b4cd80211bb994de72fd77bf2da6abd8df2df5597ab9a000"))),"frozen_rank51":dict(zip(("path","bytes","sha256"),("search/certs/d972_r07_a0_actual_tau_free_rank51_checkpoint_v1.json",10934,"a83959e4c9fcfa79093c712e82164d47c31b78c9fc00b512f7adac9413c481f4")))},"carrier pins")
 inp=c.get("inputs",{});need(inp.get("source_head")=="3316809e483223ec571ca7d6976dc1317c892441" and str(inp.get("run_id","")).isdigit() and int(inp["run_id"])>0 and str(inp.get("artifact_id","")).isdigit() and int(inp["artifact_id"])>0 and all(isinstance(inp.get(k),dict) and set(inp[k])=={"path","bytes","sha256"} for k in("task451_result","task451_checkpoint","task451_checker_log")),"carrier input identities")
 x=c.get("carrier",{});g=x.get("g760");a=x.get("correction_word");f=x.get("corrected_word");need(isinstance(g,list)and len(g)==760 and red(g)==g and isinstance(a,list)and red(a)==a and isinstance(f,list)and red(f)==f==red(g+a),"literal boundary");d=x.get("direct_replay",{});need(isinstance(d.get("physical_row"),list) and d.get("physical_row_sha256")==legacy(d["physical_row"]) and isinstance(d.get("replay"),dict) and d["replay"].get("corrected_word")==f and all(d.get(k)is True for k in("direct_all_seven_replay","eleven_occurrence_replay","right_g760_multiplication","joint_kernel","hexagons","pentagon_printed_order")) and d.get("exact_exponent_pair")==[0,0],"direct boundary")
 return {"c_exact":a,"corrected_word":f,"g760":g,"direct_replay":{"row":d["physical_row"],"row_sha256":d["physical_row_sha256"],"replay":d["replay"],"direct_all_seven_replay":True,"right_g760_multiplication":True,"hexagons":True,"pentagon_printed_order":True},"carrier_receipt":short(ci),"carrier_verdict":short(vi)}
def minimal(b):return {"exactification":{"positive_receipt":True,"literal":{"c_exact":b["c_exact"]}},"exact_direct_replay":{"row":b["direct_replay"]["row"],"row_sha256":b["direct_replay"]["row_sha256"],"replay":{"corrected_word":b["corrected_word"],"direct_all_seven_replay":True},"right_g760_multiplication":True,"hexagons":True,"pentagon_printed_order":True}}
def fixture():
 g=[1]*760;a=[2];f=g+a;ident={"path":"ci/out/toy.json","bytes":1,"sha256":"0"*64};pins={"producer":dict(zip(("path","bytes","sha256"),("search/d972_r07_a0_dual_anchored_active_batch_v1.py",13834,"ca7fb15e06dd04881146c38d63d93015a9e630fbc334cf15098cbd8a32f22f9b"))),"checker":dict(zip(("path","bytes","sha256"),("crosscheck/check_d972_r07_a0_dual_anchored_active_batch_v1.py",13725,"5c2f76b825bd920245d0200f29ff860ba93a32663ef5db9567bc499a86f7ff8a"))),"driver":dict(zip(("path","bytes","sha256"),("search/d972_r07_a0_dual_anchored_active_batch_gha_driver_v1.g",2569,"6910d38adc56a564b4cd80211bb994de72fd77bf2da6abd8df2df5597ab9a000"))),"frozen_rank51":dict(zip(("path","bytes","sha256"),("search/certs/d972_r07_a0_actual_tau_free_rank51_checkpoint_v1.json",10934,"a83959e4c9fcfa79093c712e82164d47c31b78c9fc00b512f7adac9413c481f4")))};d={"physical_row":[],"physical_row_sha256":hashlib.sha256(b"").hexdigest(),"replay":{"corrected_word":f},"direct_all_seven_replay":True,"eleven_occurrence_replay":True,"right_g760_multiplication":True,"joint_kernel":True,"hexagons":True,"pentagon_printed_order":True,"exact_exponent_pair":[0,0]};c=seal({"schema":"d972-r07-task451-task193-carrier/v1","status":"ACCEPTED","terminal":"R07_TASK451_TASK193_CARRIER_V1_ACCEPTED","claims":{"carrier":True,"A2":False,"lift":False,"fake":False,"Ihara":False},"pins":pins,"inputs":{"source_head":"3316809e483223ec571ca7d6976dc1317c892441","run_id":"1","artifact_id":"2","task451_result":ident,"task451_checkpoint":ident,"task451_checker_log":ident},"carrier":{"g760":g,"correction_word":a,"corrected_word":f,"direct_replay":d}});v=seal({"schema":"d972-r07-task451-task193-carrier/v1/checker","status":"PASS","terminal":"R07_TASK451_TASK193_CARRIER_V1_CHECKER_PASS","carrier":ident,"claims":{"literal_carrier_replayed":True,"A2":False,"lift":False,"fake":False,"Ihara":False}});firewall(c,v,ident,ident);rejected=[]
 def attempt(label,mut,which="c",reseal=True):
  cc=json.loads(json.dumps(c));vv=json.loads(json.dumps(v));x=cc if which=="c" else vv;mut(x)
  if reseal:
   x.pop("self_digest",None);x.update(seal(x))
  try:firewall(cc,vv,ident,ident)
  except RuntimeError:rejected.append(label)
 attempt("carrier_seal",lambda x:x.update(status="BAD"),reseal=False);attempt("verdict_identity",lambda x:x.update(carrier={}),"v");attempt("carrier_schema",lambda x:x.update(schema="bad"));attempt("verdict_schema",lambda x:x.update(schema="bad"),"v");attempt("carrier_terminal",lambda x:x.update(terminal="bad"));attempt("verdict_terminal",lambda x:x.update(terminal="bad"),"v");attempt("claims",lambda x:x.update(claims={}));attempt("correction",lambda x:x["carrier"].update(correction_word=[-2]));attempt("g760_product",lambda x:x["carrier"].update(g760=[1]*759));attempt("sparse_digest",lambda x:x["carrier"]["direct_replay"].update(physical_row_sha256="0"*64));attempt("full_replay",lambda x:x["carrier"]["direct_replay"].update(replay={}));attempt("exponent",lambda x:x["carrier"]["direct_replay"].update(exact_exponent_pair=[1,0]));attempt("joint",lambda x:x["carrier"]["direct_replay"].update(joint_kernel=False));attempt("hexagon",lambda x:x["carrier"]["direct_replay"].update(hexagons=False));attempt("pentagon",lambda x:x["carrier"]["direct_replay"].update(pentagon_printed_order=False));attempt("pins",lambda x:x.update(pins={}));need(len(rejected)==16,"fixture mutations");return {"status":"PASS","actual_task451_positive":False,"mutation_rejections":rejected,"minimal_input_only":True}
def main(argv=None):
 p=argparse.ArgumentParser();p.add_argument("--fixture",action="store_true");p.add_argument("--carrier-receipt");p.add_argument("--carrier-verdict");p.add_argument("--output",required=True);p.add_argument("--resume",type=Path);p.add_argument("--seconds",type=int,default=19800);p.add_argument("--boundary-pairs",type=int,default=8000000);p.add_argument("--fibre-scans",type=int,default=80000000);p.add_argument("--candidate-words",type=int,default=2000000);p.add_argument("--retained-columns",type=int,default=250000);p.add_argument("--checkpoint-bytes",type=int,default=4000000000);p.add_argument("--rss-bytes",type=int,default=5700000000);p.add_argument("--oracle-rounds",type=int,default=1000000);a=p.parse_args(argv)
 try:
  for s in(CARRIER,CCHECK,CDRIVER,V4,V4C,V4D):raw(s)
  if a.fixture:r={"schema":SCHEMA,"status":"FIXTURE","fixture":fixture()}
  else:
   need(a.resume is None,"v5 starts from rank zero; foreign checkpoint rejected");c,ci=readj(a.carrier_receipt);v,vi=readj(a.carrier_verdict);b=firewall(c,v,ci,vi);mi=minimal(b);art={"carrier_receipt":short(ci),"carrier_verdict":short(vi)};core=load(V4,"task454_v4_core");owner=core.load_owner();old=owner.actual_compile(a,mi,art);r=core.adapt_owner_result(old,b,art,mi);body=dict(r);body.pop("self_digest",None);body["schema"]=SCHEMA;body["terminal"]=COMMON;body["carrier_artifact"]=body.pop("adapter_artifact");body["carrier_input"]=body.pop("adapter_input");body["source_provenance"]={"task193_v4":dict(zip(("path","bytes","sha256"),V4)),"carrier_producer":dict(zip(("path","bytes","sha256"),CARRIER)),"carrier_checker":dict(zip(("path","bytes","sha256"),CCHECK)),"corrected_word_source":"Task452 carrier"};r=seal(body)
 except Exception as e:
  if "owner" in locals() and isinstance(e,getattr(owner,"ResourceStop",())):
   cp=dict(getattr(e,"state",{})or{});cp.update({"schema":"d972-r07-second-frattini-affine-prefix-compiler-checkpoint/v5","resumable":False,"reason":str(e),"input_identity":locals().get("art"),"source_rebuild":True,"program_cursor":{"mode":"deterministic-replay-from-rank-zero"}});cp=seal(cp);r=seal({"schema":SCHEMA,"status":UNKNOWN_RESOURCE,"terminal":UNKNOWN_RESOURCE+":"+str(e),"reason":str(e),"carrier_artifact":locals().get("art"),"checkpoint":cp,"claims":{"task193_actual":False,"d1_pt":False,"beta1":False,"A2":False,"lift":False,"fake":False,"Ihara":False}})
  else:r=seal({"schema":SCHEMA,"status":UNKNOWN_INPUT,"terminal":UNKNOWN_INPUT+":"+str(e),"reason":str(e),"claims":{"task193_actual":False,"d1_pt":False,"beta1":False,"A2":False,"lift":False,"fake":False,"Ihara":False}})
 Path(a.output).write_bytes(canon(r)+b"\n");print(COMMON+"_PRODUCER_TERMINAL "+str(r.get("terminal",r.get("status"))),flush=True);return 0
if __name__=="__main__":raise SystemExit(main())
