#############################################################################
## Task383 A4/v9 pinned rows-1--7 candidate-only driver.
## ASCII only.  No production, rows-8--48, A4, lift, fake or Ihara route.
#############################################################################
if GAPInfo.Version<>"4.16.0" then
  Error("task383: GAP 4.16.0 required");
fi;;
if PositionSublist(LowercaseString(GAPInfo.Architecture),"linux")=fail or
   PositionSublist(LowercaseString(GAPInfo.Architecture),"x86_64")=fail then
  Error("task383: Linux x86_64 required");
fi;;
if LoadPackage("json")<>true then
  Error("task383: GAP json package unavailable");
fi;;
D383JsonCanary:=JsonStringToGap("{\"ok\":true}");;
if not IsRecord(D383JsonCanary) or not IsBound(D383JsonCanary.ok) or
   D383JsonCanary.ok<>true then
  Error("task383: GAP json capability gate");
fi;;
D383Python:=Filename(DirectoriesSystemPrograms(),"python3");;
if D383Python=fail then Error("task383: python3 unavailable"); fi;;
if not IsDirectoryPath("ci/out") then
  if CreateDir("ci/out")=fail then Error("task383: cannot create ci/out"); fi;
fi;;
if not IsDirectoryPath("search/certs") then
  if CreateDir("search/certs")=fail then
    Error("task383: cannot create search/certs");
  fi;
fi;;
if not IsDirectoryPath("ci/out") or not IsDirectoryPath("search/certs") then
  Error("task383: output directory gate");
fi;;
D383StaleRoots:=[["ci/out"],["search/certs"]];;
D383StalePrefixes:=[
  "d972_r07_a4_actual_owner_trace_rows1_7_v9.",
  ".d972_r07_a4_actual_owner_trace_rows1_7_v9."
];;
for D383Root in D383StaleRoots do
  D383Contents:=DirectoryContents(D383Root[1]);;
  if D383Contents=fail then Error("task383: stale scan unavailable"); fi;
  for D383Name in D383Contents do
    for D383Prefix in D383StalePrefixes do
      if PositionSublist(D383Name,D383Prefix)=1 then
        Error("task383: stale v9 artifact ",D383Root[1],"/",D383Name);
      fi;
    od;
  od;
od;
D383ProducerCommand:="python3 -B 'search/d972_r07_a4_actual_owner_trace_producer_v7.py' --fixture 'search/certs/d972_r07_a4_actual_owner_trace_authority_fixture_v5_20260829.json'";;
D383CheckerCommand:="python3 -B 'crosscheck/check_d972_r07_a4_actual_owner_trace_checker_v6.py' --fixture 'search/certs/d972_r07_a4_actual_owner_trace_authority_fixture_v5_20260829.json'";;
D383Harness:=Concatenation(
  "import gc\n",
  "import hashlib\n",
  "import json\n",
  "import os\n",
  "import platform\n",
  "import resource\n",
  "import selectors\n",
  "import secrets\n",
  "import signal\n",
  "import stat\n",
  "import subprocess\n",
  "import sys\n",
  "import time\n",
  "\n",
  "SCHEMA = \"d972-r07-a4-actual-owner-trace/v9/pinned-driver/v1\"\n",
  "TERMINAL_SCHEMA = SCHEMA + \"/terminal/v1\"\n",
  "SENTINEL_SCHEMA = SCHEMA + \"/accepted-sentinel/v1\"\n",
  "DRIVER_PATH = \"search/d972_r07_a4_actual_owner_trace_gha_driver_v9.g\"\n",
  "PRODUCER_PATH = \"search/d972_r07_a4_actual_owner_trace_producer_v7.py\"\n",
  "CHECKER_PATH = \"crosscheck/check_d972_r07_a4_actual_owner_trace_checker_v6.py\"\n",
  "FIXTURE_PATH = \"search/certs/d972_r07_a4_actual_owner_trace_authority_fixture_v5_20260829.json\"\n",
  "RECEIPT_PATH = \"ci/in/d972_r07_seven_context_roof_presentation_v1.json\"\n",
  "MANIFEST_PATH = \"ci/in/d972_r07_seven_context_roof_presentation_v1.acceptance_v2.json\"\n",
  "PRODUCER_COMMAND = [\"python3\", \"-B\", PRODUCER_PATH, \"--fixture\", FIXTURE_PATH]\n",
  "CHECKER_COMMAND = [\"python3\", \"-B\", CHECKER_PATH, \"--fixture\", FIXTURE_PATH]\n",
  "PRODUCER_COMMAND_TEXT = \"python3 -B 'search/d972_r07_a4_actual_owner_trace_producer_v7.py' --fixture 'search/certs/d972_r07_a4_actual_owner_trace_authority_fixture_v5_20260829.json'\"\n",
  "CHECKER_COMMAND_TEXT = \"python3 -B 'crosscheck/check_d972_r07_a4_actual_owner_trace_checker_v6.py' --fixture 'search/certs/d972_r07_a4_actual_owner_trace_authority_fixture_v5_20260829.json'\"\n",
  "PRODUCER_PIN = (102958, \"4f7f57150892e354f3398c33e0f72c0d968c7101de05b7ce7e5690b47fcd064c\")\n",
  "CHECKER_PIN = (100648, \"7cf5468be847c3a49014986e39af9bb71120af6371aec05e23bb9789bb22c6c1\")\n",
  "FIXTURE_PIN = (8489, \"474d8e19ca49cad06b560cf0ac1d5eeeac1927fe2666224cb9501e77b5cc8481\")\n",
  "FIXTURE_SELF = \"c674491a2f50b200a70349780f0e7a80c21cc0fc3cecd44432dc6e70c51f63fb\"\n",
  "RESULT_SCHEMAS = {\n",
  "    \"producer\": \"d972-r07-a4-actual-owner-trace/v7\",\n",
  "    \"checker\": \"d972-r07-a4-actual-owner-trace/v6\",\n",
  "}\n",
  "CI_FINALS = {\n",
  "    \"producer_raw\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.producer.stdout.raw.json\",\n",
  "    \"checker_raw\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.checker.stdout.raw.json\",\n",
  "    \"producer_log\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.producer.stderr.log\",\n",
  "    \"checker_log\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.checker.stderr.log\",\n",
  "    \"sentinel\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.accepted.json\",\n",
  "}\n",
  "CERT_FINALS = {\n",
  "    \"producer\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.producer.admitted.json\",\n",
  "    \"checker\": \"d972_r07_a4_actual_owner_trace_rows1_7_v9.checker.admitted.json\",\n",
  "}\n",
  "STALE_PREFIXES = (\n",
  "    \"d972_r07_a4_actual_owner_trace_rows1_7_v9.\",\n",
  "    \".d972_r07_a4_actual_owner_trace_rows1_7_v9.\",\n",
  ")\n",
  "CHUNK = 1048576\n",
  "PIPE_CHUNK = 65536\n",
  "RESULT_PAYLOAD_MAX = 35000000\n",
  "RESULT_FILE_MAX = RESULT_PAYLOAD_MAX + 1\n",
  "LOG_MAX = 1000000\n",
  "PROJECTION_MAX = 8000000\n",
  "PARENT_ADDRESS_SPACE = 1200000000\n",
  "CHILD_CPU_SOFT = 3600\n",
  "CHILD_CPU_HARD = 3610\n",
  "CHILD_WALL_SECONDS = 3900.0\n",
  "TERM_GRACE_SECONDS = 30.0\n",
  "CLEANUP_MARGIN_SECONDS = 260.0\n",
  "GLOBAL_SECONDS = 9000.0\n",
  "STARTED = time.monotonic()\n",
  "GLOBAL_END = STARTED + GLOBAL_SECONDS\n",
  "ROOT_FD = -1\n",
  "ACTIVE_PROCESS = None\n",
  "TX = None\n",
  "FAILURE_REPORTED = False\n",
  "\n",
  "class Gate(RuntimeError):\n",
  "    pass\n",
  "\n",
  "def need(condition, reason):\n",
  "    if not condition:\n",
  "        raise Gate(reason)\n",
  "\n",
  "def canonical(value):\n",
  "    return json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(\",\", \":\"), allow_nan=False).encode(\"ascii\")\n",
  "\n",
  "def sha256(raw):\n",
  "    return hashlib.sha256(raw).hexdigest()\n",
  "\n",
  "def hex64(value):\n",
  "    return type(value) is str and len(value) == 64 and all(character in \"0123456789abcdef\" for character in value)\n",
  "\n",
  "def deadline(reason):\n",
  "    if time.monotonic() > GLOBAL_END:\n",
  "        raise Gate(\"deadline:\" + reason)\n",
  "\n",
  "def alarm_handler(signum, frame):\n",
  "    raise Gate(\"deadline:signal\")\n",
  "\n",
  "def identity(st):\n",
  "    return (int(st.st_dev), int(st.st_ino), int(st.st_mode), int(st.st_nlink), int(st.st_size), int(st.st_mtime_ns))\n",
  "\n",
  "def directory_identity(st):\n",
  "    return (int(st.st_dev), int(st.st_ino), int(st.st_mode), int(st.st_nlink))\n",
  "\n",
  "def write_all(fd, raw):\n",
  "    view = memoryview(raw)\n",
  "    offset = 0\n",
  "    while offset < len(view):\n",
  "        deadline(\"write\")\n",
  "        count = os.write(fd, view[offset:offset + CHUNK])\n",
  "        need(type(count) is int and count > 0, \"short_write\")\n",
  "        offset += count\n",
  "    view.release()\n",
  "\n",
  "def hash_fd(fd, maximum, expected_size=None):\n",
  "    deadline(\"hash_start\")\n",
  "    before = os.fstat(fd)\n",
  "    need(stat.S_ISREG(before.st_mode) and before.st_nlink == 1, \"hash_nonregular\")\n",
  "    size = int(before.st_size)\n",
  "    need(0 <= size <= maximum, \"hash_size_bound\")\n",
  "    if expected_size is not None:\n",
  "        need(size == expected_size, \"hash_exact_size\")\n",
  "    need(os.lseek(fd, 0, os.SEEK_SET) == 0, \"hash_rewind\")\n",
  "    digest = hashlib.sha256()\n",
  "    remaining = size\n",
  "    total = 0\n",
  "    while remaining:\n",
  "        deadline(\"hash_stream\")\n",
  "        block = os.read(fd, min(CHUNK, remaining))\n",
  "        need(bool(block), \"hash_short_read\")\n",
  "        digest.update(block)\n",
  "        total += len(block)\n",
  "        remaining -= len(block)\n",
  "    need(os.read(fd, 1) == b\"\", \"hash_long_read\")\n",
  "    after = os.fstat(fd)\n",
  "    need(identity(before) == identity(after) and total == size, \"hash_fd_mutation\")\n",
  "    need(os.lseek(fd, 0, os.SEEK_SET) == 0, \"hash_restore\")\n",
  "    return size, digest.hexdigest(), identity(before)\n",
  "\n",
  "def open_relative(path):\n",
  "    need(type(path) is str and path and not path.startswith(\"/\") and \"\\\\\" not in path, \"path_envelope\")\n",
  "    parts = path.split(\"/\")\n",
  "    need(all(part not in (\"\", \".\", \"..\") for part in parts), \"path_escape\")\n",
  "    current = os.dup(ROOT_FD)\n",
  "    fd = -1\n",
  "    try:\n",
  "        for part in parts[:-1]:\n",
  "            next_fd = os.open(part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=current)\n",
  "            os.close(current)\n",
  "            current = next_fd\n",
  "        leaf = parts[-1]\n",
  "        fd = os.open(leaf, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=current)\n",
  "        named = os.stat(leaf, dir_fd=current, follow_symlinks=False)\n",
  "        opened = os.fstat(fd)\n",
  "        need(stat.S_ISREG(opened.st_mode) and not stat.S_ISLNK(named.st_mode), \"owner_nonregular:\" + path)\n",
  "        need(identity(opened) == identity(named), \"owner_path_mismatch:\" + path)\n",
  "        return fd, current, leaf\n",
  "    except BaseException:\n",
  "        if fd >= 0:\n",
  "            os.close(fd)\n",
  "        os.close(current)\n",
  "        raise\n",
  "\n",
  "class BoundDirectory:\n",
  "    def __init__(self, parts, label):\n",
  "        self.parts = tuple(parts)\n",
  "        self.label = label\n",
  "        current = os.dup(ROOT_FD)\n",
  "        try:\n",
  "            for part in self.parts:\n",
  "                next_fd = os.open(part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=current)\n",
  "                os.close(current)\n",
  "                current = next_fd\n",
  "            self.fd = current\n",
  "            current = -1\n",
  "            opened = os.fstat(self.fd)\n",
  "            need(stat.S_ISDIR(opened.st_mode), \"directory_kind:\" + label)\n",
  "            self.bound = directory_identity(opened)\n",
  "        finally:\n",
  "            if current >= 0:\n",
  "                os.close(current)\n",
  "    @property\n",
  "    def path(self):\n",
  "        return \"/\".join(self.parts)\n",
  "    def check(self):\n",
  "        deadline(\"directory_check:\" + self.label)\n",
  "        current = os.dup(ROOT_FD)\n",
  "        try:\n",
  "            for part in self.parts:\n",
  "                next_fd = os.open(part, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=current)\n",
  "                os.close(current)\n",
  "                current = next_fd\n",
  "            need(directory_identity(os.fstat(current)) == self.bound == directory_identity(os.fstat(self.fd)), \"directory_substitution:\" + self.label)\n",
  "        finally:\n",
  "            os.close(current)\n",
  "    def stale_gate(self):\n",
  "        self.check()\n",
  "        for name in os.listdir(self.fd):\n",
  "            if any(name.startswith(prefix) for prefix in STALE_PREFIXES):\n",
  "                raise Gate(\"stale_name:\" + self.path + \"/\" + name)\n",
  "    def close(self):\n",
  "        if self.fd >= 0:\n",
  "            os.close(self.fd)\n",
  "            self.fd = -1\n",
  "\n",
  "class BoundOwner:\n",
  "    def __init__(self, path, maximum, expected_size=None, expected_sha=None):\n",
  "        self.path = path\n",
  "        self.fd, self.parent_fd, self.leaf = open_relative(path)\n",
  "        size, digest, ident = hash_fd(self.fd, maximum, expected_size)\n",
  "        if expected_sha is not None:\n",
  "            need(digest == expected_sha, \"owner_digest:\" + path)\n",
  "        self.size = size\n",
  "        self.sha256 = digest\n",
  "        self.ident = ident\n",
  "        self.maximum = maximum\n",
  "    def revalidate(self):\n",
  "        deadline(\"owner_revalidate:\" + self.path)\n",
  "        named = os.stat(self.leaf, dir_fd=self.parent_fd, follow_symlinks=False)\n",
  "        need(identity(named) == self.ident == identity(os.fstat(self.fd)), \"owner_identity_changed:\" + self.path)\n",
  "        fresh_fd = -1\n",
  "        fresh_parent = -1\n",
  "        try:\n",
  "            fresh_fd, fresh_parent, fresh_leaf = open_relative(self.path)\n",
  "            need(fresh_leaf == self.leaf and identity(os.fstat(fresh_fd)) == self.ident, \"owner_path_changed:\" + self.path)\n",
  "        finally:\n",
  "            if fresh_fd >= 0:\n",
  "                os.close(fresh_fd)\n",
  "            if fresh_parent >= 0:\n",
  "                os.close(fresh_parent)\n",
  "        size, digest, ident = hash_fd(self.fd, self.maximum, self.size)\n",
  "        need(ident == self.ident and digest == self.sha256, \"owner_bytes_changed:\" + self.path)\n",
  "    def public(self):\n",
  "        return {\"path\": self.path, \"bytes\": self.size, \"sha256\": self.sha256}\n",
  "    def close(self):\n",
  "        if self.fd >= 0:\n",
  "            os.close(self.fd)\n",
  "            self.fd = -1\n",
  "        if self.parent_fd >= 0:\n",
  "            os.close(self.parent_fd)\n",
  "            self.parent_fd = -1\n",
  "\n",
  "def read_bounded_fd(fd, maximum):\n",
  "    deadline(\"bounded_read_start\")\n",
  "    before = os.fstat(fd)\n",
  "    size = int(before.st_size)\n",
  "    need(stat.S_ISREG(before.st_mode) and before.st_nlink == 1 and 0 <= size <= maximum, \"bounded_read_owner\")\n",
  "    need(os.lseek(fd, 0, os.SEEK_SET) == 0, \"bounded_read_rewind\")\n",
  "    remaining = size\n",
  "    pieces = []\n",
  "    while remaining:\n",
  "        deadline(\"bounded_read_stream\")\n",
  "        block = os.read(fd, min(CHUNK, remaining))\n",
  "        need(bool(block), \"bounded_read_short\")\n",
  "        pieces.append(block)\n",
  "        remaining -= len(block)\n",
  "    need(os.read(fd, 1) == b\"\", \"bounded_read_long\")\n",
  "    after = os.fstat(fd)\n",
  "    need(identity(before) == identity(after), \"bounded_read_mutation\")\n",
  "    raw = b\"\".join(pieces)\n",
  "    del pieces\n",
  "    need(len(raw) == size, \"bounded_read_length\")\n",
  "    need(os.lseek(fd, 0, os.SEEK_SET) == 0, \"bounded_read_restore\")\n",
  "    return raw\n",
  "\n",
  "def admit_owner_json(owner, maximum, newline, seal_key, expected_seal):\n",
  "    raw = read_bounded_fd(owner.fd, maximum)\n",
  "    need(not raw.startswith(b\"\\xef\\xbb\\xbf\") and b\"\\r\" not in raw, \"owner_json_encoding:\" + owner.path)\n",
  "    suffix = b\"\\n\" if newline else b\"\"\n",
  "    need(raw.endswith(suffix) if suffix else not raw.endswith(b\"\\n\"), \"owner_json_newline:\" + owner.path)\n",
  "    payload = raw[:-1] if newline else raw\n",
  "    need(b\"\\n\" not in payload, \"owner_json_multiline:\" + owner.path)\n",
  "    try:\n",
  "        value = json.loads(payload.decode(\"ascii\"))\n",
  "    except (UnicodeError, json.JSONDecodeError) as exc:\n",
  "        raise Gate(\"owner_json_parse:\" + owner.path) from exc\n",
  "    need(type(value) is dict, \"owner_json_root:\" + owner.path)\n",
  "    encoded = canonical(value)\n",
  "    need(payload == encoded, \"owner_json_noncanonical:\" + owner.path)\n",
  "    del raw, payload, encoded\n",
  "    body = dict(value)\n",
  "    claimed = body.pop(seal_key, None)\n",
  "    need(hex64(claimed) and claimed == expected_seal, \"owner_json_claimed_seal:\" + owner.path)\n",
  "    body_encoded = canonical(body)\n",
  "    need(sha256(body_encoded) == claimed, \"owner_json_body_seal:\" + owner.path)\n",
  "    del body, body_encoded\n",
  "    deadline(\"owner_json_admitted\")\n",
  "    return value, claimed\n",
  "\n",
  "class TempOwner:\n",
  "    def __init__(self, directory, name, fd, label):\n",
  "        self.directory = directory\n",
  "        self.name = name\n",
  "        self.fd = fd\n",
  "        self.label = label\n",
  "        self.active = True\n",
  "        self.expected_inode = None\n",
  "\n",
  "class PublishedOwner:\n",
  "    def __init__(self, directory, name):\n",
  "        self.directory = directory\n",
  "        self.name = name\n",
  "        self.fd = -1\n",
  "        self.size = None\n",
  "        self.sha256 = None\n",
  "        self.ident = None\n",
  "        self.expected_inode = None\n",
  "    @property\n",
  "    def path(self):\n",
  "        return self.directory.path + \"/\" + self.name\n",
  "    def public(self):\n",
  "        need(type(self.size) is int and hex64(self.sha256), \"published_public\")\n",
  "        return {\"path\": self.path, \"bytes\": self.size, \"sha256\": self.sha256}\n",
  "\n",
  "class Transaction:\n",
  "    def __init__(self):\n",
  "        self.temps = []\n",
  "        self.visible = []\n",
  "        self.serial = 0\n",
  "    def new_temp(self, directory, final_name, label):\n",
  "        deadline(\"temp_create:\" + label)\n",
  "        directory.check()\n",
  "        need(\"/\" not in final_name and final_name and not final_name.startswith(\".\"), \"final_name_envelope\")\n",
  "        self.serial += 1\n",
  "        name = \".\" + final_name + \".tmp.\" + secrets.token_hex(16) + \".\" + str(self.serial)\n",
  "        temp = TempOwner(directory, name, -1, label)\n",
  "        self.temps.append(temp)\n",
  "        previous_mask = signal.pthread_sigmask(signal.SIG_BLOCK, {signal.SIGALRM})\n",
  "        try:\n",
  "            temp.fd = os.open(name, os.O_RDWR | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o600, dir_fd=directory.fd)\n",
  "            opened = os.fstat(temp.fd)\n",
  "            temp.expected_inode = (int(opened.st_dev), int(opened.st_ino))\n",
  "            need(stat.S_ISREG(opened.st_mode) and opened.st_nlink == 1, \"temp_identity\")\n",
  "        finally:\n",
  "            signal.pthread_sigmask(signal.SIG_SETMASK, previous_mask)\n",
  "        return temp\n",
  "    def copy_from(self, source_fd, directory, final_name, maximum, label):\n",
  "        temp = self.new_temp(directory, final_name, label)\n",
  "        source_before = os.fstat(source_fd)\n",
  "        need(stat.S_ISREG(source_before.st_mode) and source_before.st_nlink == 1 and source_before.st_size <= maximum, \"copy_source\")\n",
  "        need(os.lseek(source_fd, 0, os.SEEK_SET) == 0, \"copy_rewind\")\n",
  "        remaining = int(source_before.st_size)\n",
  "        while remaining:\n",
  "            deadline(\"copy_stream:\" + label)\n",
  "            block = os.read(source_fd, min(CHUNK, remaining))\n",
  "            need(bool(block), \"copy_short\")\n",
  "            write_all(temp.fd, block)\n",
  "            remaining -= len(block)\n",
  "        need(os.read(source_fd, 1) == b\"\", \"copy_long\")\n",
  "        need(identity(source_before) == identity(os.fstat(source_fd)), \"copy_source_mutation\")\n",
  "        need(os.lseek(source_fd, 0, os.SEEK_SET) == 0, \"copy_restore\")\n",
  "        os.fsync(temp.fd)\n",
  "        return temp\n",
  "    def publish(self, temp, maximum, expected_size=None, expected_sha=None):\n",
  "        deadline(\"publish:\" + temp.label)\n",
  "        need(temp.active and temp.fd >= 0, \"publish_inactive\")\n",
  "        temp.directory.check()\n",
  "        os.fsync(temp.fd)\n",
  "        before = os.fstat(temp.fd)\n",
  "        need(stat.S_ISREG(before.st_mode) and before.st_nlink == 1, \"publish_temp_identity\")\n",
  "        final_name = temp.name[1:temp.name.index(\".tmp.\")]\n",
  "        visible = PublishedOwner(temp.directory, final_name)\n",
  "        visible.expected_inode = (int(before.st_dev), int(before.st_ino))\n",
  "        self.visible.append(visible)\n",
  "        os.link(temp.name, final_name, src_dir_fd=temp.directory.fd, dst_dir_fd=temp.directory.fd, follow_symlinks=False)\n",
  "        os.fsync(temp.directory.fd)\n",
  "        visible.fd = os.open(final_name, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=temp.directory.fd)\n",
  "        named = os.stat(final_name, dir_fd=temp.directory.fd, follow_symlinks=False)\n",
  "        opened = os.fstat(visible.fd)\n",
  "        need((before.st_dev, before.st_ino, before.st_mode, before.st_size, before.st_mtime_ns) == (opened.st_dev, opened.st_ino, opened.st_mode, opened.st_size, opened.st_mtime_ns) == (named.st_dev, named.st_ino, named.st_mode, named.st_size, named.st_mtime_ns), \"publish_link_identity\")\n",
  "        need(opened.st_nlink == 2 and named.st_nlink == 2, \"publish_link_count\")\n",
  "        os.unlink(temp.name, dir_fd=temp.directory.fd)\n",
  "        os.fsync(temp.directory.fd)\n",
  "        temp.active = False\n",
  "        named = os.stat(final_name, dir_fd=temp.directory.fd, follow_symlinks=False)\n",
  "        need(identity(before) == identity(os.fstat(temp.fd)) == identity(os.fstat(visible.fd)) == identity(named), \"publish_single_link_identity\")\n",
  "        size, digest, ident = hash_fd(visible.fd, maximum, expected_size)\n",
  "        if expected_sha is not None:\n",
  "            need(digest == expected_sha, \"publish_digest\")\n",
  "        visible.size, visible.sha256, visible.ident = size, digest, ident\n",
  "        os.close(temp.fd)\n",
  "        temp.fd = -1\n",
  "        temp.directory.check()\n",
  "        return visible\n",
  "    def verify_all(self):\n",
  "        for owner in self.visible:\n",
  "            deadline(\"published_revalidate:\" + owner.path)\n",
  "            owner.directory.check()\n",
  "            need(owner.fd >= 0, \"published_fd_closed\")\n",
  "            named = os.stat(owner.name, dir_fd=owner.directory.fd, follow_symlinks=False)\n",
  "            need(identity(named) == owner.ident == identity(os.fstat(owner.fd)), \"published_identity_changed:\" + owner.path)\n",
  "            size, digest, ident = hash_fd(owner.fd, RESULT_FILE_MAX if owner.path.endswith(\".json\") else LOG_MAX, owner.size)\n",
  "            need(ident == owner.ident and digest == owner.sha256, \"published_bytes_changed:\" + owner.path)\n",
  "    def rollback(self):\n",
  "        errors = []\n",
  "        for owner in reversed(self.visible):\n",
  "            try:\n",
  "                named = os.stat(owner.name, dir_fd=owner.directory.fd, follow_symlinks=False)\n",
  "                if (int(named.st_dev), int(named.st_ino)) == owner.expected_inode:\n",
  "                    os.unlink(owner.name, dir_fd=owner.directory.fd)\n",
  "                else:\n",
  "                    errors.append(\"final_foreign:\" + owner.path)\n",
  "            except FileNotFoundError:\n",
  "                pass\n",
  "            except BaseException as exc:\n",
  "                errors.append(\"final:\" + owner.path + \":\" + type(exc).__name__)\n",
  "            try:\n",
  "                os.fsync(owner.directory.fd)\n",
  "            except BaseException as exc:\n",
  "                errors.append(\"final_fsync:\" + owner.path + \":\" + type(exc).__name__)\n",
  "            if owner.fd >= 0:\n",
  "                try:\n",
  "                    os.close(owner.fd)\n",
  "                except BaseException as exc:\n",
  "                    errors.append(\"final_close:\" + owner.path + \":\" + type(exc).__name__)\n",
  "                owner.fd = -1\n",
  "        for temp in reversed(self.temps):\n",
  "            if temp.active:\n",
  "                try:\n",
  "                    named = os.stat(temp.name, dir_fd=temp.directory.fd, follow_symlinks=False)\n",
  "                    if temp.expected_inode is not None and (int(named.st_dev), int(named.st_ino)) == temp.expected_inode:\n",
  "                        os.unlink(temp.name, dir_fd=temp.directory.fd)\n",
  "                    elif temp.expected_inode is not None:\n",
  "                        errors.append(\"temp_foreign:\" + temp.label)\n",
  "                except FileNotFoundError:\n",
  "                    pass\n",
  "                except BaseException as exc:\n",
  "                    errors.append(\"temp:\" + temp.label + \":\" + type(exc).__name__)\n",
  "                try:\n",
  "                    os.fsync(temp.directory.fd)\n",
  "                except BaseException as exc:\n",
  "                    errors.append(\"temp_fsync:\" + temp.label + \":\" + type(exc).__name__)\n",
  "            if temp.fd >= 0:\n",
  "                try:\n",
  "                    os.close(temp.fd)\n",
  "                except BaseException as exc:\n",
  "                    errors.append(\"temp_close:\" + temp.label + \":\" + type(exc).__name__)\n",
  "                temp.fd = -1\n",
  "            temp.active = False\n",
  "        return errors\n",
  "    def close_success(self):\n",
  "        for owner in self.visible:\n",
  "            if owner.fd >= 0:\n",
  "                os.close(owner.fd)\n",
  "                owner.fd = -1\n",
  "        for temp in self.temps:\n",
  "            if temp.fd >= 0:\n",
  "                os.close(temp.fd)\n",
  "                temp.fd = -1\n",
  "\n",
  "def child_limits():\n",
  "    signal.signal(signal.SIGALRM, signal.SIG_DFL)\n",
  "    os.setsid()\n",
  "    resource.setrlimit(resource.RLIMIT_CPU, (CHILD_CPU_SOFT, CHILD_CPU_HARD))\n",
  "\n",
  "def stop_process(process):\n",
  "    if process is None or process.poll() is not None:\n",
  "        return\n",
  "    try:\n",
  "        os.killpg(process.pid, signal.SIGTERM)\n",
  "    except ProcessLookupError:\n",
  "        return\n",
  "    try:\n",
  "        process.wait(timeout=TERM_GRACE_SECONDS)\n",
  "    except subprocess.TimeoutExpired:\n",
  "        try:\n",
  "            os.killpg(process.pid, signal.SIGKILL)\n",
  "        except ProcessLookupError:\n",
  "            pass\n",
  "        process.wait(timeout=TERM_GRACE_SECONDS)\n",
  "\n",
  "def frame_stdout(temp):\n",
  "    before = os.fstat(temp.fd)\n",
  "    size = int(before.st_size)\n",
  "    need(0 < size <= RESULT_PAYLOAD_MAX, \"stdout_size\")\n",
  "    need(os.lseek(temp.fd, 0, os.SEEK_SET) == 0, \"stdout_scan_rewind\")\n",
  "    newlines = 0\n",
  "    carriage = 0\n",
  "    first = b\"\"\n",
  "    last = None\n",
  "    remaining = size\n",
  "    while remaining:\n",
  "        deadline(\"stdout_scan\")\n",
  "        block = os.read(temp.fd, min(CHUNK, remaining))\n",
  "        need(bool(block), \"stdout_scan_short\")\n",
  "        if not first:\n",
  "            first = block[:3]\n",
  "        newlines += block.count(b\"\\n\")\n",
  "        carriage += block.count(b\"\\r\")\n",
  "        last = block[-1]\n",
  "        remaining -= len(block)\n",
  "    need(first != b\"\\xef\\xbb\\xbf\" and carriage == 0, \"stdout_encoding\")\n",
  "    if newlines == 0:\n",
  "        need(size + 1 <= RESULT_FILE_MAX, \"stdout_frame_bound\")\n",
  "        need(os.lseek(temp.fd, 0, os.SEEK_END) == size, \"stdout_frame_seek\")\n",
  "        write_all(temp.fd, b\"\\n\")\n",
  "        size += 1\n",
  "    else:\n",
  "        need(newlines == 1 and last == 10, \"stdout_exact_line\")\n",
  "    os.fsync(temp.fd)\n",
  "    need(os.fstat(temp.fd).st_size == size, \"stdout_framed_size\")\n",
  "    need(os.lseek(temp.fd, 0, os.SEEK_SET) == 0, \"stdout_frame_restore\")\n",
  "\n",
  "def run_candidate(command, command_text, side, ci_directory):\n",
  "    global ACTIVE_PROCESS\n",
  "    need(command == (PRODUCER_COMMAND if side == \"producer\" else CHECKER_COMMAND), \"fixed_command:\" + side)\n",
  "    need(\"--output\" not in command and command.count(\"--fixture\") == 1 and command[0:2] == [\"python3\", \"-B\"], \"command_boundary:\" + side)\n",
  "    expected_text = PRODUCER_COMMAND_TEXT if side == \"producer\" else CHECKER_COMMAND_TEXT\n",
  "    need(command_text == expected_text, \"quoted_command_text:\" + side)\n",
  "    remaining_runs = 2 if side == \"producer\" else 1\n",
  "    required_remaining = remaining_runs * (CHILD_WALL_SECONDS + 2.0 * TERM_GRACE_SECONDS) + CLEANUP_MARGIN_SECONDS\n",
  "    need(time.monotonic() + required_remaining <= GLOBAL_END, \"cleanup_margin:\" + side)\n",
  "    local_end = time.monotonic() + CHILD_WALL_SECONDS\n",
  "    stdout_temp = TX.new_temp(ci_directory, CI_FINALS[side + \"_raw\"], side + \"_stdout\")\n",
  "    stderr_temp = TX.new_temp(ci_directory, CI_FINALS[side + \"_log\"], side + \"_stderr\")\n",
  "    process = subprocess.Popen(command, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True, preexec_fn=child_limits, bufsize=0)\n",
  "    ACTIVE_PROCESS = process\n",
  "    selector = selectors.DefaultSelector()\n",
  "    counts = {\"stdout\": 0, \"stderr\": 0}\n",
  "    streams = ((process.stdout, \"stdout\", stdout_temp, RESULT_PAYLOAD_MAX), (process.stderr, \"stderr\", stderr_temp, LOG_MAX))\n",
  "    try:\n",
  "        for stream, label, temp, maximum in streams:\n",
  "            need(stream is not None, \"pipe_missing\")\n",
  "            os.set_blocking(stream.fileno(), False)\n",
  "            selector.register(stream, selectors.EVENT_READ, (label, temp, maximum))\n",
  "        while selector.get_map():\n",
  "            deadline(\"subprocess:\" + side)\n",
  "            if time.monotonic() > local_end:\n",
  "                stop_process(process)\n",
  "                raise Gate(\"external_timeout:\" + side)\n",
  "            ready = selector.select(timeout=0.25)\n",
  "            for key, mask in ready:\n",
  "                label, temp, maximum = key.data\n",
  "                block = os.read(key.fd, PIPE_CHUNK)\n",
  "                if block:\n",
  "                    counts[label] += len(block)\n",
  "                    if counts[label] > maximum:\n",
  "                        stop_process(process)\n",
  "                        raise Gate(label + \"_bound:\" + side)\n",
  "                    write_all(temp.fd, block)\n",
  "                else:\n",
  "                    selector.unregister(key.fileobj)\n",
  "                    key.fileobj.close()\n",
  "        remaining = max(0.0, local_end - time.monotonic())\n",
  "        try:\n",
  "            status = process.wait(timeout=remaining)\n",
  "        except subprocess.TimeoutExpired:\n",
  "            stop_process(process)\n",
  "            raise Gate(\"external_wait_timeout:\" + side)\n",
  "        ACTIVE_PROCESS = None\n",
  "        need(type(status) is int and status == 0, \"process_status:\" + side + \":\" + str(status))\n",
  "        frame_stdout(stdout_temp)\n",
  "        os.fsync(stderr_temp.fd)\n",
  "        return stdout_temp, stderr_temp\n",
  "    finally:\n",
  "        selector.close()\n",
  "        for stream, label, temp, maximum in streams:\n",
  "            if stream is not None and not stream.closed:\n",
  "                stream.close()\n",
  "        if process.poll() is None:\n",
  "            stop_process(process)\n",
  "        ACTIVE_PROCESS = None\n",
  "\n",
  "MUTATIONS = [\n",
  "    \"per_layer_ordinal\",\n",
  "    \"authority_binding\",\n",
  "    \"canonical_input_bytes\",\n",
  "    \"resolved_path_traversal\",\n",
  "    \"normal_generation_proof\",\n",
  "    \"bridge_typed_occurrence_ledger\",\n",
  "    \"evaluator_abi_canary\",\n",
  "]\n",
  "ROWS_SHA = \"e00880c01bc96ba8f0549311f4955662668d74001ecf5c06097646dad4268950\"\n",
  "SOURCE_TRANSCRIPT = [\n",
  "    (\"source_pin_1\", 81, \"b5ab577d14ed490af12e3921ee41cfea533abcbf92d60cc037f0d40035ba5090\"),\n",
  "    (\"source_pin_2\", 95, \"260eb23f73a8fb6b9cd2316aa4ea6c29a4a6db92e77d8c5c6f4f1dd6e7ff290e\"),\n",
  "    (\"source_pin_3\", 150, \"ac841c5a979bbe89bdd47c73151ecabf29783793b7b288b4d08c4824596251de\"),\n",
  "    (\"source_pin_4\", 137169, \"6b2645b80f97256a659af81e856c086cca724b36e2a22ae70335b29ffa95d44c\"),\n",
  "    (\"source_pin_5\", 157253, \"001277d44dbbc2acd7e03c6ecb6c6419df84996ae188cbb4be7b18f7cfb56ca1\"),\n",
  "    (\"source_pin_6\", 20541, \"6048174be12d5f6f48508f1b2e80c87b3e1cb9df9ed348b30b6d3e19420b5068\"),\n",
  "]\n",
  "EVENT_SUFFIXES = {\n",
  "    \"per_layer_ordinal\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "        (\"authority.manifest_acceptance\", \"authority\", \"manifest.accepted\"),\n",
  "        (\"transport.receipt_open\", \"transport\", \"receipt.bytes\"),\n",
  "        (\"authority.row_order\", \"authority\", \"receipt.Delta0.presentation.rows\"),\n",
  "    ],\n",
  "    \"authority_binding\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "        (\"authority.manifest_acceptance\", \"authority\", \"manifest.accepted\"),\n",
  "    ],\n",
  "    \"canonical_input_bytes\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "        (\"authority.manifest_acceptance\", \"authority\", \"manifest.accepted\"),\n",
  "        (\"transport.receipt_open\", \"transport\", \"receipt.bytes\"),\n",
  "        (\"transport.receipt_identity\", \"transport\", \"manifest.receipt.{bytes,sha256}\"),\n",
  "    ],\n",
  "    \"resolved_path_traversal\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "    ],\n",
  "    \"normal_generation_proof\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "        (\"authority.manifest_acceptance\", \"authority\", \"manifest.accepted\"),\n",
  "        (\"transport.receipt_open\", \"transport\", \"receipt.bytes\"),\n",
  "        (\"authority.row_order\", \"authority\", \"receipt.Delta0.presentation.rows\"),\n",
  "        (\"authority.normal_generation\", \"authority\", \"receipt.Delta0.presentation.normal_generation_proof\"),\n",
  "    ],\n",
  "    \"bridge_typed_occurrence_ledger\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "        (\"authority.manifest_acceptance\", \"authority\", \"manifest.accepted\"),\n",
  "        (\"transport.receipt_open\", \"transport\", \"receipt.bytes\"),\n",
  "        (\"authority.row_order\", \"authority\", \"receipt.Delta0.presentation.rows\"),\n",
  "        (\"authority.normal_generation\", \"authority\", \"receipt.Delta0.presentation.normal_generation_proof\"),\n",
  "        (\"authority.bridge_occurrence\", \"authority\", \"receipt.bridge.occurrence_ledger\"),\n",
  "    ],\n",
  "    \"evaluator_abi_canary\": [\n",
  "        (\"transport.path_containment\", \"transport\", \"manifest.path\"),\n",
  "        (\"transport.manifest_open\", \"transport\", \"manifest.bytes\"),\n",
  "        (\"transport.manifest_decode\", \"decode\", \"manifest.bytes\"),\n",
  "        (\"transport.path_containment\", \"transport\", \"receipt.path\"),\n",
  "        (\"authority.manifest_acceptance\", \"authority\", \"manifest.accepted\"),\n",
  "        (\"transport.receipt_open\", \"transport\", \"receipt.bytes\"),\n",
  "        (\"authority.row_order\", \"authority\", \"receipt.Delta0.presentation.rows\"),\n",
  "        (\"authority.normal_generation\", \"authority\", \"receipt.Delta0.presentation.normal_generation_proof\"),\n",
  "        (\"authority.bridge_occurrence\", \"authority\", \"receipt.bridge.occurrence_ledger\"),\n",
  "        (\"authority.evaluator_abi\", \"authority\", \"receipt.evaluator\"),\n",
  "    ],\n",
  "}\n",
  "EVENT_COUNTS = [len(EVENT_SUFFIXES[name]) for name in MUTATIONS]\n",
  "IDENTITY_KEYS = {\n",
  "    \"logical_case_path\", \"owner_kind\", \"byte_length\", \"content_sha256\", \"link_count\",\n",
  "    \"symlink_or_reparse\", \"logical_link_target\", \"single_open_handle\",\n",
  "    \"opened_handle_stable\", \"pathname_matches_opened_handle\",\n",
  "    \"substitution_detected\", \"canonical_before_sha256\", \"canonical_after_sha256\",\n",
  "}\n",
  "ROW_KEYS = {\n",
  "    \"id\", \"owner\", \"identity_kind\", \"before_identity\", \"after_identity\",\n",
  "    \"resealed_nodes\", \"semantic_reseal_dag\", \"entered_validators\",\n",
  "    \"first_rejection\", \"event_trace_digest\", \"terminal_count\",\n",
  "    \"baseline_revalidated\", \"baseline_revalidation_transcript\",\n",
  "    \"owner_disposed\", \"disposal_proof\", \"resource_before\", \"resource_after\",\n",
  "}\n",
  "SNAPSHOT_KEYS = {\n",
  "    \"counts\", \"reserved\", \"modeled_payload_live\", \"modeled_payload_peak\",\n",
  "    \"payload_owners\", \"traversed_bytes\", \"revalidated_bytes\",\n",
  "}\n",
  "TRAVERSED_KEYS = {\n",
  "    \"canonical_compared_bytes\", \"seal_body_hashed_bytes\", \"row_digest_bytes\",\n",
  "    \"canonical_digest_bytes\", \"canonical_constructed_bytes\",\n",
  "    \"physical_hashed_bytes\", \"case_stage_readback_hashed_bytes\",\n",
  "    \"wire_source_hashed_bytes\", \"stdout_canonical_bytes\",\n",
  "}\n",
  "RESOURCE_COUNT_KEYS = {\"opened_bytes\", \"temporary_bytes\", \"canonical_bytes\", \"parsed_input_bytes\", \"opens\", \"writes\", \"events\", \"mutations\"}\n",
  "\n",
  "def expected_events(role, mutation):\n",
  "    return [\n",
  "        {\"ordinal\": index, \"validator\": role + \".\" + suffix, \"stage\": stage, \"owner\": owner}\n",
  "        for index, (suffix, stage, owner) in enumerate(EVENT_SUFFIXES[mutation], 1)\n",
  "    ]\n",
  "\n",
  "def expected_transcript(fixture_pin, receipt_pin, manifest_pin):\n",
  "    rows = SOURCE_TRANSCRIPT + [\n",
  "        (\"fixture\", fixture_pin[0], fixture_pin[1]),\n",
  "        (\"manifest\", manifest_pin[\"bytes\"], manifest_pin[\"sha256\"]),\n",
  "        (\"receipt\", receipt_pin[\"bytes\"], receipt_pin[\"sha256\"]),\n",
  "    ]\n",
  "    return {\n",
  "        label: {\n",
  "            \"fd_rewound\": True,\n",
  "            \"exact_length\": size,\n",
  "            \"sha256\": digest,\n",
  "            \"identity_match\": True,\n",
  "            \"pathname_no_follow_match\": True,\n",
  "        }\n",
  "        for label, size, digest in rows\n",
  "    }\n",
  "\n",
  "def expected_dag(name):\n",
  "    if name == \"authority_binding\":\n",
  "        return [{\"node\": \"changed_manifest_body\", \"output\": \"manifest.manifest_self_digest_sha256+raw_sha256\"}]\n",
  "    if name in (\"canonical_input_bytes\", \"resolved_path_traversal\"):\n",
  "        return []\n",
  "    return [\n",
  "        {\"node\": \"changed_receipt_body\", \"output\": \"receipt.self_digest_sha256\"},\n",
  "        {\"node\": \"receipt.self_digest_sha256\", \"output\": \"receipt.raw_sha256+byte_length\"},\n",
  "        {\"node\": \"receipt.raw_sha256+byte_length+self_digest_sha256\", \"output\": \"manifest.receipt.binding\"},\n",
  "        {\"node\": \"manifest.receipt.binding\", \"output\": \"changed_manifest_body\"},\n",
  "        {\"node\": \"changed_manifest_body\", \"output\": \"manifest.manifest_self_digest_sha256+raw_sha256\"},\n",
  "    ]\n",
  "\n",
  "def validate_snapshot(value, row_index, phase, authority_bytes):\n",
  "    need(type(value) is dict and set(value) == SNAPSHOT_KEYS, \"snapshot_shape\")\n",
  "    counts = value[\"counts\"]\n",
  "    reserved = value[\"reserved\"]\n",
  "    need(type(counts) is dict and type(reserved) is dict and set(counts) == RESOURCE_COUNT_KEYS and set(reserved) == RESOURCE_COUNT_KEYS, \"snapshot_counter_shape\")\n",
  "    need(all(type(number) is int and number >= 0 for number in counts.values()), \"snapshot_counts\")\n",
  "    need(all(number == 0 for number in reserved.values()), \"snapshot_reserved\")\n",
  "    need(type(value[\"payload_owners\"]) is dict and all(type(k) is str and type(v) is int and v >= 0 for k, v in value[\"payload_owners\"].items()), \"snapshot_payload_owners\")\n",
  "    need(sum(value[\"payload_owners\"].values()) == value[\"modeled_payload_live\"] == authority_bytes, \"snapshot_payload_live\")\n",
  "    need(type(value[\"modeled_payload_peak\"]) is int and value[\"modeled_payload_peak\"] >= authority_bytes, \"snapshot_payload_peak\")\n",
  "    need(type(value[\"traversed_bytes\"]) is dict and set(value[\"traversed_bytes\"]) == TRAVERSED_KEYS and all(type(v) is int and v >= 0 for v in value[\"traversed_bytes\"].values()), \"snapshot_traversed\")\n",
  "    expected_revalidated = (2 * row_index - (1 if phase == \"before\" else 0)) * authority_bytes\n",
  "    need(value[\"revalidated_bytes\"] == expected_revalidated, \"snapshot_revalidated\")\n",
  "\n",
  "def validate_identity(value, fixture_row, mutation, phase, receipt_pin, manifest_pin):\n",
  "    need(type(value) is dict and set(value) == IDENTITY_KEYS, \"identity_shape\")\n",
  "    need(value[\"logical_case_path\"] == fixture_row[\"logical_case_path\"] and value[\"owner_kind\"] == fixture_row[\"identity_kind\"], \"identity_logical\")\n",
  "    need(value[\"logical_link_target\"] == \"none\" and value[\"substitution_detected\"] is False, \"identity_safe\")\n",
  "    unreadable = \"UNREADABLE_AT_REGISTERED_STAGE\"\n",
  "    if mutation == \"resolved_path_traversal\":\n",
  "        need(value[\"owner_kind\"] == \"path\", \"path_identity_kind\")\n",
  "        need(value[\"symlink_or_reparse\"] is (phase == \"after\"), \"path_identity_presence\")\n",
  "        need(value[\"byte_length\"] == unreadable and value[\"content_sha256\"] == unreadable and value[\"canonical_before_sha256\"] == unreadable and value[\"canonical_after_sha256\"] == unreadable, \"path_identity_unreadable\")\n",
  "        expected_link = 1 if phase == \"before\" else unreadable\n",
  "        need(value[\"link_count\"] == expected_link, \"path_identity_link\")\n",
  "        need(value[\"single_open_handle\"] is False and value[\"opened_handle_stable\"] is False and value[\"pathname_matches_opened_handle\"] is False, \"path_identity_handle\")\n",
  "        return\n",
  "    base = manifest_pin if mutation == \"authority_binding\" else receipt_pin\n",
  "    need(value[\"owner_kind\"] == \"file\" and value[\"symlink_or_reparse\"] is False and value[\"single_open_handle\"] is True and value[\"opened_handle_stable\"] is True and value[\"pathname_matches_opened_handle\"] is True and value[\"link_count\"] == 1, \"file_identity_handle\")\n",
  "    if phase == \"before\":\n",
  "        need(value[\"byte_length\"] == base[\"bytes\"] and value[\"content_sha256\"] == base[\"sha256\"], \"before_identity_pin\")\n",
  "        need(value[\"canonical_before_sha256\"] == base[\"sha256\"] and value[\"canonical_after_sha256\"] == base[\"sha256\"], \"before_canonical_pin\")\n",
  "    else:\n",
  "        need(type(value[\"byte_length\"]) is int and 0 < value[\"byte_length\"] <= RESULT_PAYLOAD_MAX and hex64(value[\"content_sha256\"]) and value[\"content_sha256\"] != base[\"sha256\"], \"after_identity_changed\")\n",
  "        need(value[\"canonical_before_sha256\"] == base[\"sha256\"], \"after_canonical_before\")\n",
  "        if mutation == \"canonical_input_bytes\":\n",
  "            need(value[\"canonical_after_sha256\"] == unreadable, \"wire_canonical_after\")\n",
  "        else:\n",
  "            need(value[\"canonical_after_sha256\"] == value[\"content_sha256\"], \"after_canonical_digest\")\n",
  "\n",
  "def validate_public_resource(value, fixture):\n",
  "    need(type(value) is dict and set(value) == {\n",
  "        \"caps\", \"counts\", \"modeled_payload_tokens\", \"process_address_space\",\n",
  "        \"traversed_bytes\", \"revalidated_bytes\", \"one_meter\",\n",
  "        \"logical_open_account\", \"snapshot_boundary\",\n",
  "    }, \"public_resource_shape\")\n",
  "    need(value[\"caps\"] == fixture[\"resource_caps\"], \"resource_caps\")\n",
  "    formula = fixture[\"resource_formula\"]\n",
  "    counts = value[\"counts\"]\n",
  "    need(type(counts) is dict and set(counts) == RESOURCE_COUNT_KEYS, \"resource_count_shape\")\n",
  "    need(counts[\"opened_bytes\"] == formula[\"opened_bytes_intended\"] == 186443583, \"resource_opened\")\n",
  "    need(counts[\"temporary_bytes\"] == formula[\"temporary_bytes_intended\"] == 155099839, \"resource_temporary\")\n",
  "    need(counts[\"parsed_input_bytes\"] == formula[\"parsed_input_bytes_intended\"] == 279185470, \"resource_parsed\")\n",
  "    need(counts[\"opens\"] == 53 and counts[\"writes\"] == 10 and counts[\"events\"] == 66 and counts[\"mutations\"] == 7, \"resource_discrete\")\n",
  "    need(type(counts[\"canonical_bytes\"]) is int and 0 <= counts[\"canonical_bytes\"] <= fixture[\"resource_caps\"][\"canonical_bytes\"], \"resource_canonical\")\n",
  "    tokens = value[\"modeled_payload_tokens\"]\n",
  "    need(type(tokens) is dict and tokens.get(\"current\") == 31343744 and tokens.get(\"peak\") == formula[\"modeled_payload_tokens_intended\"] == 63409572, \"resource_tokens\")\n",
  "    need(tokens.get(\"definition\") == \"exact ledger tokens for retained file/canonical/mutation byte lengths and reserved bounded I/O/canonical-fragment capacities\", \"resource_token_definition\")\n",
  "    need(tokens.get(\"omits\") == \"parsed Python DOMs, decoder/interpreter/container/allocator overhead, bytearray capacity slack, and RSS\", \"resource_token_omits\")\n",
  "    address = value[\"process_address_space\"]\n",
  "    need(address == {\"mechanism\": \"RLIMIT_AS\", \"soft_bytes\": 700000000, \"ceiling_bytes\": 750000000, \"rss_observed\": False}, \"resource_address\")\n",
  "    need(value[\"revalidated_bytes\"] == 438812416 and value[\"one_meter\"] is True, \"resource_revalidation\")\n",
  "    need(value[\"logical_open_account\"] == \"logical owner opens plus retained-fd revalidation passes; traversal-component OS opens are not included\", \"resource_open_account\")\n",
  "    need(value[\"snapshot_boundary\"] == \"complete seven-row no-path-output run before result self-seal and canonical stdout\", \"resource_snapshot_boundary\")\n",
  "    need(type(value[\"traversed_bytes\"]) is dict and set(value[\"traversed_bytes\"]) == TRAVERSED_KEYS and all(type(v) is int and v >= 0 for v in value[\"traversed_bytes\"].values()), \"resource_traversed\")\n",
  "\n",
  "def validate_result(role, value, fixture, receipt_pin, manifest_pin):\n",
  "    need(type(value) is dict and set(value) == {\n",
  "        \"schema\", \"candidate_only\", \"synthetic\", \"covered_rows\", \"remaining_rows\",\n",
  "        \"full_a4_selftest\", \"actual_a4_numerator\", \"baseline\", \"rows\",\n",
  "        \"resource\", \"self_digest_sha256\",\n",
  "    }, \"result_root_shape:\" + role)\n",
  "    need(value[\"schema\"] == RESULT_SCHEMAS[role], \"result_schema:\" + role)\n",
  "    need(value[\"candidate_only\"] is True and value[\"synthetic\"] is False and value[\"covered_rows\"] == list(range(1, 8)) and value[\"remaining_rows\"] == list(range(8, 49)) and value[\"full_a4_selftest\"] is False and value[\"actual_a4_numerator\"] is False, \"result_scope:\" + role)\n",
  "    baseline = value[\"baseline\"]\n",
  "    need(baseline == {\n",
  "        \"receipt_canonical_sha256\": receipt_pin[\"sha256\"],\n",
  "        \"manifest_canonical_sha256\": manifest_pin[\"sha256\"],\n",
  "        \"rows_sha256\": ROWS_SHA,\n",
  "        \"baseline_revalidated\": True,\n",
  "    }, \"result_baseline:\" + role)\n",
  "    rows = value[\"rows\"]\n",
  "    need(type(rows) is list and len(rows) == 7 and [row.get(\"id\") for row in rows if type(row) is dict] == MUTATIONS, \"result_row_order:\" + role)\n",
  "    transcript = expected_transcript(FIXTURE_PIN, receipt_pin, manifest_pin)\n",
  "    authority_bytes = 315289 + FIXTURE_PIN[0] + receipt_pin[\"bytes\"] + manifest_pin[\"bytes\"]\n",
  "    event_digests = []\n",
  "    for index, (name, row) in enumerate(zip(MUTATIONS, rows), 1):\n",
  "        need(type(row) is dict and set(row) == ROW_KEYS, \"row_shape:\" + role + \":\" + name)\n",
  "        expected = fixture[role][name]\n",
  "        need(row[\"owner\"] == expected[\"owner\"] and row[\"identity_kind\"] == expected[\"identity_kind\"], \"row_owner:\" + role + \":\" + name)\n",
  "        need(row[\"first_rejection\"] == expected[\"first_rejection\"], \"row_first_rejection:\" + role + \":\" + name)\n",
  "        need(row[\"resealed_nodes\"] == expected[\"allowed_downstream_reseals\"] and row[\"semantic_reseal_dag\"] == expected_dag(name), \"row_reseal:\" + role + \":\" + name)\n",
  "        events = expected_events(role, name)\n",
  "        validators = [event[\"validator\"] for event in events]\n",
  "        need(row[\"entered_validators\"] == validators, \"row_entered:\" + role + \":\" + name)\n",
  "        need(row[\"event_trace_digest\"] == sha256(canonical(events)) and hex64(row[\"event_trace_digest\"]), \"row_event_digest:\" + role + \":\" + name)\n",
  "        event_digests.append(row[\"event_trace_digest\"])\n",
  "        rejection_validator = expected[\"first_rejection\"][\"validator\"]\n",
  "        rejection_entries = [(event[\"stage\"], event[\"owner\"]) for event in events if event[\"validator\"] == rejection_validator]\n",
  "        if name == \"resolved_path_traversal\":\n",
  "            need(rejection_entries == [(\"transport\", \"manifest.path\"), (\"transport\", \"receipt.path\")], \"row4_two_admissions:\" + role)\n",
  "            need(events[-1] == {\"ordinal\": 4, \"validator\": rejection_validator, \"stage\": \"transport\", \"owner\": \"receipt.path\"}, \"row4_terminal_event:\" + role)\n",
  "        else:\n",
  "            need(len(rejection_entries) == 1 and events[-1][\"validator\"] == rejection_validator and events[-1][\"stage\"] == expected[\"stage\"], \"other_terminal_event:\" + role + \":\" + name)\n",
  "        need(row[\"terminal_count\"] == 1 and row[\"baseline_revalidated\"] is True and row[\"owner_disposed\"] is True, \"row_terminal:\" + role + \":\" + name)\n",
  "        need(row[\"disposal_proof\"] == {\"workspace_absent\": True, \"outside_owner_absent\": True, \"cache_evicted\": True}, \"row_disposal:\" + role + \":\" + name)\n",
  "        need(row[\"baseline_revalidation_transcript\"] == {\"before\": transcript, \"after\": transcript}, \"row_revalidation_transcript:\" + role + \":\" + name)\n",
  "        validate_identity(row[\"before_identity\"], expected, name, \"before\", receipt_pin, manifest_pin)\n",
  "        validate_identity(row[\"after_identity\"], expected, name, \"after\", receipt_pin, manifest_pin)\n",
  "        validate_snapshot(row[\"resource_before\"], index, \"before\", authority_bytes)\n",
  "        validate_snapshot(row[\"resource_after\"], index, \"after\", authority_bytes)\n",
  "    need(len(set(event_digests)) == 7, \"event_digest_distinct:\" + role)\n",
  "    validate_public_resource(value[\"resource\"], fixture)\n",
  "    return event_digests\n",
  "\n",
  "def normalize_string(value, role):\n",
  "    if value.startswith(role + \".\"):\n",
  "        return \"ROLE.\" + value[len(role) + 1:]\n",
  "    if value.startswith(role + \":\"):\n",
  "        return \"ROLE:\" + value[len(role) + 1:]\n",
  "    return value\n",
  "\n",
  "def normalize_value(value, role):\n",
  "    if type(value) is dict:\n",
  "        normalized = {}\n",
  "        for key, child in value.items():\n",
  "            new_key = normalize_string(key, role) if type(key) is str else key\n",
  "            need(new_key not in normalized, \"normalization_key_collision\")\n",
  "            normalized[new_key] = normalize_value(child, role)\n",
  "        return normalized\n",
  "    if type(value) is list:\n",
  "        return [normalize_value(child, role) for child in value]\n",
  "    if type(value) is str:\n",
  "        return normalize_string(value, role)\n",
  "    return value\n",
  "\n",
  "def adjust_snapshot(snapshot, role, event_count):\n",
  "    delta = (len(role) - len(\"ROLE\")) * event_count\n",
  "    snapshot[\"counts\"][\"canonical_bytes\"] -= delta\n",
  "    snapshot[\"traversed_bytes\"][\"canonical_digest_bytes\"] -= delta\n",
  "    need(snapshot[\"counts\"][\"canonical_bytes\"] >= 0 and snapshot[\"traversed_bytes\"][\"canonical_digest_bytes\"] >= 0, \"normalized_snapshot_counter\")\n",
  "\n",
  "def projection_bytes(value, role):\n",
  "    deadline(\"projection_start:\" + role)\n",
  "    projected = normalize_value(value, role)\n",
  "    projected[\"schema\"] = \"d972-r07-a4-actual-owner-trace/ROLE\"\n",
  "    projected.pop(\"self_digest_sha256\")\n",
  "    cumulative = 0\n",
  "    for name, row, count in zip(MUTATIONS, projected[\"rows\"], EVENT_COUNTS):\n",
  "        adjust_snapshot(row[\"resource_before\"], role, cumulative)\n",
  "        cumulative += count\n",
  "        adjust_snapshot(row[\"resource_after\"], role, cumulative)\n",
  "        row[\"event_trace_digest\"] = sha256(canonical(expected_events(\"ROLE\", name)))\n",
  "    adjust_snapshot(projected[\"resource\"], role, cumulative)\n",
  "    raw = canonical(projected)\n",
  "    need(len(raw) <= PROJECTION_MAX, \"projection_bound:\" + role)\n",
  "    del projected\n",
  "    deadline(\"projection_complete:\" + role)\n",
  "    return raw\n",
  "\n",
  "def admit_result(temp, role, fixture, receipt_pin, manifest_pin):\n",
  "    raw = read_bounded_fd(temp.fd, RESULT_FILE_MAX)\n",
  "    need(1 < len(raw) <= RESULT_FILE_MAX and raw.endswith(b\"\\n\") and raw.count(b\"\\n\") == 1 and b\"\\r\" not in raw and not raw.startswith(b\"\\xef\\xbb\\xbf\"), \"result_line:\" + role)\n",
  "    payload = raw[:-1]\n",
  "    try:\n",
  "        value = json.loads(payload.decode(\"ascii\"))\n",
  "    except (UnicodeError, json.JSONDecodeError) as exc:\n",
  "        raise Gate(\"result_parse:\" + role) from exc\n",
  "    need(type(value) is dict, \"result_root:\" + role)\n",
  "    encoded = canonical(value)\n",
  "    need(encoded == payload, \"result_noncanonical:\" + role)\n",
  "    physical_sha = sha256(raw)\n",
  "    physical_bytes = len(raw)\n",
  "    del raw, payload, encoded\n",
  "    body = dict(value)\n",
  "    claimed = body.pop(\"self_digest_sha256\", None)\n",
  "    need(hex64(claimed) and sha256(canonical(body)) == claimed, \"result_self_seal:\" + role)\n",
  "    del body\n",
  "    event_digests = validate_result(role, value, fixture, receipt_pin, manifest_pin)\n",
  "    projection = projection_bytes(value, role)\n",
  "    return value, {\n",
  "        \"bytes\": physical_bytes,\n",
  "        \"sha256\": physical_sha,\n",
  "        \"self_digest_sha256\": claimed,\n",
  "        \"event_trace_digests\": event_digests,\n",
  "        \"projection\": projection,\n",
  "    }\n",
  "\n",
  "def install_parent_limit():\n",
  "    need(platform.system() == \"Linux\" and platform.machine() == \"x86_64\", \"platform\")\n",
  "    need(hasattr(resource, \"RLIMIT_AS\") and hasattr(resource, \"RLIMIT_CPU\"), \"rlimit_support\")\n",
  "    need(hasattr(signal, \"pthread_sigmask\"), \"signal_mask_support\")\n",
  "    soft, hard = resource.getrlimit(resource.RLIMIT_AS)\n",
  "    target = PARENT_ADDRESS_SPACE\n",
  "    if hard != resource.RLIM_INFINITY:\n",
  "        target = min(target, int(hard))\n",
  "    need(800000000 <= target <= PARENT_ADDRESS_SPACE, \"parent_rlimit_preexisting\")\n",
  "    resource.setrlimit(resource.RLIMIT_AS, (target, target))\n",
  "    installed = resource.getrlimit(resource.RLIMIT_AS)\n",
  "    need(installed == (target, target), \"parent_rlimit_readback\")\n",
  "    return target\n",
  "\n",
  "def main():\n",
  "    global ROOT_FD, TX, FAILURE_REPORTED\n",
  "    parent_limit = install_parent_limit()\n",
  "    signal.signal(signal.SIGALRM, alarm_handler)\n",
  "    signal.setitimer(signal.ITIMER_REAL, GLOBAL_SECONDS)\n",
  "    ROOT_FD = os.open(\".\", os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC)\n",
  "    need(stat.S_ISDIR(os.fstat(ROOT_FD).st_mode), \"root_directory\")\n",
  "    ci_directory = BoundDirectory((\"ci\", \"out\"), \"ci/out\")\n",
  "    cert_directory = BoundDirectory((\"search\", \"certs\"), \"search/certs\")\n",
  "    TX = Transaction()\n",
  "    owners = []\n",
  "    success = False\n",
  "    try:\n",
  "        ci_directory.stale_gate()\n",
  "        cert_directory.stale_gate()\n",
  "        producer_owner = BoundOwner(PRODUCER_PATH, 200000, PRODUCER_PIN[0], PRODUCER_PIN[1])\n",
  "        checker_owner = BoundOwner(CHECKER_PATH, 200000, CHECKER_PIN[0], CHECKER_PIN[1])\n",
  "        fixture_owner = BoundOwner(FIXTURE_PATH, 1000000, FIXTURE_PIN[0], FIXTURE_PIN[1])\n",
  "        owners.extend([producer_owner, checker_owner, fixture_owner])\n",
  "        need(len({owner.path for owner in owners}) == 3 and len({owner.ident[:2] for owner in owners}) == 3, \"frozen_owner_alias\")\n",
  "        driver_owner = BoundOwner(DRIVER_PATH, 1000000)\n",
  "        owners.append(driver_owner)\n",
  "        fixture, fixture_seal = admit_owner_json(fixture_owner, 1000000, True, \"self_digest_sha256\", FIXTURE_SELF)\n",
  "        need(set(fixture) == {\n",
  "            \"actual_a4_numerator\", \"candidate_only\", \"checker\", \"covered_rows\",\n",
  "            \"full_a4_selftest\", \"immutable_input_identities\", \"producer\",\n",
  "            \"remaining_rows\", \"resource_caps\", \"resource_formula\", \"schema\",\n",
  "            \"self_digest_sha256\", \"synthetic\",\n",
  "        }, \"fixture_root_shape\")\n",
  "        need(fixture[\"schema\"] == \"d972-r07-a4-actual-owner-trace/v5/authority-fixture/v5\" and fixture[\"candidate_only\"] is True and fixture[\"synthetic\"] is False and fixture[\"covered_rows\"] == list(range(1, 8)) and fixture[\"remaining_rows\"] == list(range(8, 49)) and fixture[\"full_a4_selftest\"] is False and fixture[\"actual_a4_numerator\"] is False, \"fixture_scope\")\n",
  "        need(set(fixture[\"producer\"]) == set(MUTATIONS) and set(fixture[\"checker\"]) == set(MUTATIONS), \"fixture_mutations\")\n",
  "        immutable = fixture[\"immutable_input_identities\"]\n",
  "        need(type(immutable) is dict and set(immutable) == {\"task198_receipt\", \"task198_manifest\"}, \"fixture_immutable_shape\")\n",
  "        receipt_pin = immutable[\"task198_receipt\"]\n",
  "        manifest_pin = immutable[\"task198_manifest\"]\n",
  "        need(set(receipt_pin) == {\"bytes\", \"sha256\", \"self_digest_sha256\"} and type(receipt_pin[\"bytes\"]) is int and receipt_pin[\"bytes\"] == 31017244 and hex64(receipt_pin[\"sha256\"]) and hex64(receipt_pin[\"self_digest_sha256\"]), \"receipt_pin_shape\")\n",
  "        need(set(manifest_pin) == {\"bytes\", \"sha256\", \"manifest_self_digest_sha256\"} and type(manifest_pin[\"bytes\"]) is int and manifest_pin[\"bytes\"] == 2722 and hex64(manifest_pin[\"sha256\"]) and hex64(manifest_pin[\"manifest_self_digest_sha256\"]), \"manifest_pin_shape\")\n",
  "        receipt_owner = BoundOwner(RECEIPT_PATH, 40000000, receipt_pin[\"bytes\"], receipt_pin[\"sha256\"])\n",
  "        manifest_owner = BoundOwner(MANIFEST_PATH, 10000, manifest_pin[\"bytes\"], manifest_pin[\"sha256\"])\n",
  "        owners.extend([receipt_owner, manifest_owner])\n",
  "        need(len({owner.path for owner in owners}) == len(owners) and len({owner.ident[:2] for owner in owners}) == len(owners), \"physical_owner_alias\")\n",
  "        manifest, manifest_seal = admit_owner_json(manifest_owner, 10000, False, \"manifest_self_digest_sha256\", manifest_pin[\"manifest_self_digest_sha256\"])\n",
  "        binding = manifest.get(\"receipt\")\n",
  "        need(manifest.get(\"accepted\") is True and type(binding) is dict and binding.get(\"basename\") == RECEIPT_PATH.split(\"/\")[-1] and binding.get(\"bytes\") == receipt_pin[\"bytes\"] and binding.get(\"sha256\") == receipt_pin[\"sha256\"] and binding.get(\"self_digest_sha256\") == receipt_pin[\"self_digest_sha256\"], \"manifest_receipt_binding\")\n",
  "        receipt, receipt_seal = admit_owner_json(receipt_owner, 40000000, False, \"self_digest_sha256\", receipt_pin[\"self_digest_sha256\"])\n",
  "        need(receipt.get(\"schema\") == \"d972-r07-seven-context-roof-presentation/v1\" and receipt.get(\"status\") == \"COMPLETE\", \"receipt_envelope\")\n",
  "        receipt.clear()\n",
  "        manifest.clear()\n",
  "        del receipt, manifest\n",
  "        gc.collect()\n",
  "        for owner in owners:\n",
  "            owner.revalidate()\n",
  "        producer_stdout, producer_stderr = run_candidate(PRODUCER_COMMAND, PRODUCER_COMMAND_TEXT, \"producer\", ci_directory)\n",
  "        for owner in owners:\n",
  "            owner.revalidate()\n",
  "        producer_result, producer_meta = admit_result(producer_stdout, \"producer\", fixture, receipt_pin, manifest_pin)\n",
  "        producer_projection = producer_meta.pop(\"projection\")\n",
  "        producer_raw = TX.publish(producer_stdout, RESULT_FILE_MAX, producer_meta[\"bytes\"], producer_meta[\"sha256\"])\n",
  "        producer_log = TX.publish(producer_stderr, LOG_MAX)\n",
  "        producer_admitted_temp = TX.copy_from(producer_raw.fd, cert_directory, CERT_FINALS[\"producer\"], RESULT_FILE_MAX, \"producer_admitted\")\n",
  "        producer_admitted = TX.publish(producer_admitted_temp, RESULT_FILE_MAX, producer_meta[\"bytes\"], producer_meta[\"sha256\"])\n",
  "        producer_result.clear()\n",
  "        del producer_result\n",
  "        gc.collect()\n",
  "        deadline(\"producer_dom_released\")\n",
  "        for owner in owners:\n",
  "            owner.revalidate()\n",
  "        checker_stdout, checker_stderr = run_candidate(CHECKER_COMMAND, CHECKER_COMMAND_TEXT, \"checker\", ci_directory)\n",
  "        for owner in owners:\n",
  "            owner.revalidate()\n",
  "        checker_result, checker_meta = admit_result(checker_stdout, \"checker\", fixture, receipt_pin, manifest_pin)\n",
  "        checker_projection = checker_meta.pop(\"projection\")\n",
  "        need(producer_projection == checker_projection, \"cross_projection\")\n",
  "        common_projection_sha = sha256(producer_projection)\n",
  "        checker_raw = TX.publish(checker_stdout, RESULT_FILE_MAX, checker_meta[\"bytes\"], checker_meta[\"sha256\"])\n",
  "        checker_log = TX.publish(checker_stderr, LOG_MAX)\n",
  "        checker_admitted_temp = TX.copy_from(checker_raw.fd, cert_directory, CERT_FINALS[\"checker\"], RESULT_FILE_MAX, \"checker_admitted\")\n",
  "        checker_admitted = TX.publish(checker_admitted_temp, RESULT_FILE_MAX, checker_meta[\"bytes\"], checker_meta[\"sha256\"])\n",
  "        checker_result.clear()\n",
  "        del checker_result, checker_projection, producer_projection\n",
  "        gc.collect()\n",
  "        deadline(\"cross_comparison_complete\")\n",
  "        for owner in owners:\n",
  "            owner.revalidate()\n",
  "        TX.verify_all()\n",
  "        ci_directory.check()\n",
  "        cert_directory.check()\n",
  "        sentinel_body = {\n",
  "            \"schema\": SENTINEL_SCHEMA,\n",
  "            \"status\": \"ACCEPTED_ROWS1_7_CANDIDATE_ONLY\",\n",
  "            \"candidate_only\": True,\n",
  "            \"synthetic\": False,\n",
  "            \"covered_rows\": list(range(1, 8)),\n",
  "            \"remaining_rows\": list(range(8, 49)),\n",
  "            \"full_a4_selftest\": False,\n",
  "            \"actual_a4_numerator\": False,\n",
  "            \"a4_basis\": False,\n",
  "            \"cofinal_lift\": False,\n",
  "            \"fake\": False,\n",
  "            \"Ihara_witness\": False,\n",
  "            \"driver\": driver_owner.public(),\n",
  "            \"producer\": producer_owner.public(),\n",
  "            \"checker\": checker_owner.public(),\n",
  "            \"fixture\": dict(fixture_owner.public(), self_digest_sha256=fixture_seal),\n",
  "            \"task198\": {\n",
  "                \"receipt\": dict(receipt_owner.public(), self_digest_sha256=receipt_seal),\n",
  "                \"manifest\": dict(manifest_owner.public(), manifest_self_digest_sha256=manifest_seal),\n",
  "            },\n",
  "            \"commands\": {\n",
  "                \"producer\": PRODUCER_COMMAND_TEXT,\n",
  "                \"checker\": CHECKER_COMMAND_TEXT,\n",
  "                \"serial_exact_once\": True,\n",
  "                \"producer_output_injected_into_checker\": False,\n",
  "                \"output_argument_used\": False,\n",
  "            },\n",
  "            \"timeouts\": {\n",
  "                \"internal_cpu_soft_seconds\": CHILD_CPU_SOFT,\n",
  "                \"internal_cpu_hard_seconds\": CHILD_CPU_HARD,\n",
  "                \"external_wall_seconds_each\": int(CHILD_WALL_SECONDS),\n",
  "                \"termination_grace_seconds\": int(TERM_GRACE_SECONDS),\n",
  "                \"maximum_stop_wait_seconds\": int(2 * TERM_GRACE_SECONDS),\n",
  "                \"cleanup_margin_seconds\": int(CLEANUP_MARGIN_SECONDS),\n",
  "                \"global_seconds\": int(GLOBAL_SECONDS),\n",
  "                \"two_candidate_budget_formula\": \"2*(3900+2*30)+260=8180 < 9000\",\n",
  "            },\n",
  "            \"resource_boundary\": {\n",
  "                \"parent_RLIMIT_AS_hard_bytes\": parent_limit,\n",
  "                \"candidate_RLIMIT_AS_soft_bytes\": 700000000,\n",
  "                \"result_file_max_bytes\": RESULT_FILE_MAX,\n",
  "                \"stderr_log_max_bytes\": LOG_MAX,\n",
  "                \"projection_max_bytes\": PROJECTION_MAX,\n",
  "                \"stream_chunk_bytes\": CHUNK,\n",
  "                \"maximum_simultaneous_explicit_buffer_formula\": \"max(2*31017244+1048576+8489+2722,2*35000001+2*8000000+1048576); one parsed DOM only; producer DOM released before checker DOM; candidate child serial\",\n",
  "                \"maximum_simultaneous_explicit_buffer_bytes\": 87048578,\n",
  "                \"rss_observed\": False,\n",
  "            },\n",
  "            \"results\": {\n",
  "                \"producer_raw\": producer_raw.public(),\n",
  "                \"producer_admitted\": dict(producer_admitted.public(), self_digest_sha256=producer_meta[\"self_digest_sha256\"], event_trace_digests=producer_meta[\"event_trace_digests\"]),\n",
  "                \"checker_raw\": checker_raw.public(),\n",
  "                \"checker_admitted\": dict(checker_admitted.public(), self_digest_sha256=checker_meta[\"self_digest_sha256\"], event_trace_digests=checker_meta[\"event_trace_digests\"]),\n",
  "                \"common_projection_sha256\": common_projection_sha,\n",
  "            },\n",
  "            \"logs\": {\n",
  "                \"producer\": producer_log.public(),\n",
  "                \"checker\": checker_log.public(),\n",
  "                \"stderr_nonaccepting\": True,\n",
  "            },\n",
  "            \"publication\": {\n",
  "                \"exclusive_same_directory_temps\": True,\n",
  "                \"no_replace_hardlink\": True,\n",
  "                \"retained_descriptor_rehash\": True,\n",
  "                \"file_and_directory_fsync\": True,\n",
  "                \"rollback_on_post_visible_failure\": True,\n",
  "            },\n",
  "            \"fresh_independent_static_audit_required\": True,\n",
  "            \"rows1_7_GHA_authorized\": False,\n",
  "        }\n",
  "        sentinel_self = sha256(canonical(sentinel_body))\n",
  "        sentinel = dict(sentinel_body, self_digest_sha256=sentinel_self)\n",
  "        sentinel_raw = canonical(sentinel) + b\"\\n\"\n",
  "        need(len(sentinel_raw) <= 1000000, \"sentinel_bound\")\n",
  "        sentinel_temp = TX.new_temp(ci_directory, CI_FINALS[\"sentinel\"], \"sentinel\")\n",
  "        write_all(sentinel_temp.fd, sentinel_raw)\n",
  "        os.fsync(sentinel_temp.fd)\n",
  "        sentinel_owner = TX.publish(sentinel_temp, 1000000, len(sentinel_raw), sha256(sentinel_raw))\n",
  "        for owner in owners:\n",
  "            owner.revalidate()\n",
  "        TX.verify_all()\n",
  "        ci_directory.check()\n",
  "        cert_directory.check()\n",
  "        terminal_body = {\n",
  "            \"schema\": TERMINAL_SCHEMA,\n",
  "            \"status\": \"ACCEPTED_ROWS1_7_CANDIDATE_ONLY\",\n",
  "            \"accepted_sentinel\": dict(sentinel_owner.public(), self_digest_sha256=sentinel_self),\n",
  "            \"candidate_only\": True,\n",
  "            \"covered_rows\": list(range(1, 8)),\n",
  "            \"full_a4_selftest\": False,\n",
  "            \"actual_a4_numerator\": False,\n",
  "            \"lift_fake_ihara\": False,\n",
  "        }\n",
  "        terminal = dict(terminal_body, self_digest_sha256=sha256(canonical(terminal_body)))\n",
  "        terminal_raw = canonical(terminal) + b\"\\n\"\n",
  "        deadline(\"terminal\")\n",
  "        TX.close_success()\n",
  "        write_all(1, terminal_raw)\n",
  "        success = True\n",
  "        signal.setitimer(signal.ITIMER_REAL, 0.0)\n",
  "    except BaseException as exc:\n",
  "        signal.setitimer(signal.ITIMER_REAL, 0.0)\n",
  "        try:\n",
  "            stop_process(ACTIVE_PROCESS)\n",
  "        except BaseException:\n",
  "            pass\n",
  "        rollback_errors = TX.rollback() if TX is not None else []\n",
  "        diagnostic = {\n",
  "            \"schema\": SCHEMA + \"/failure/v1\",\n",
  "            \"status\": \"NONACCEPTING\",\n",
  "            \"reason\": type(exc).__name__ + \":\" + str(exc),\n",
  "            \"rollback_errors\": rollback_errors,\n",
  "        }\n",
  "        try:\n",
  "            os.write(2, canonical(diagnostic) + b\"\\n\")\n",
  "        except BaseException:\n",
  "            pass\n",
  "        FAILURE_REPORTED = True\n",
  "        raise\n",
  "    finally:\n",
  "        if not success:\n",
  "            signal.setitimer(signal.ITIMER_REAL, 0.0)\n",
  "        for owner in owners:\n",
  "            try:\n",
  "                owner.close()\n",
  "            except BaseException:\n",
  "                pass\n",
  "        for directory in (ci_directory, cert_directory):\n",
  "            try:\n",
  "                directory.close()\n",
  "            except BaseException:\n",
  "                pass\n",
  "        if ROOT_FD >= 0:\n",
  "            try:\n",
  "                os.close(ROOT_FD)\n",
  "            except BaseException:\n",
  "                pass\n",
  "\n",
  "try:\n",
  "    main()\n",
  "except BaseException as exc:\n",
  "    signal.setitimer(signal.ITIMER_REAL, 0.0)\n",
  "    if not FAILURE_REPORTED:\n",
  "        diagnostic = {\"schema\": SCHEMA + \"/failure/v1\", \"status\": \"NONACCEPTING\", \"reason\": type(exc).__name__ + \":\" + str(exc), \"rollback_errors\": []}\n",
  "        try:\n",
  "            os.write(2, canonical(diagnostic) + b\"\\n\")\n",
  "        except BaseException:\n",
  "            pass\n",
  "    raise SystemExit(1)\n",
  "\n"
);;
D383HarnessInput:=InputTextString(D383Harness);;
D383HarnessStatus:=Process(DirectoryCurrent(),D383Python,D383HarnessInput,
  OutputTextUser(),["-B","-"]);;
if D383HarnessStatus<>0 then
  Error("task383: pinned harness returned nonzero status ",D383HarnessStatus);
fi;;
