## search/extract_deep15_data.g -- one-shot filter: read search/zcensus83_data.g's TARGET83 list,
## keep ONLY the 8 id_group isomorphism types that appear in the delta>1 (A-type, e=6) 15-record
## subset of search/certs/zcensus83_v2_20260812.json's target83_detail, write the matching TARGET83
## entries (index, id, words) to search/iso_census83_deep15_data.g as DEEP15.
## Not committed as a permanent tool -- a one-shot data-extraction step (847-style: reads an
## existing committed data file, writes a derived smaller data file, no new census).
SizeScreen([1000000, 1000000]);;
Read("search/zcensus83_data.g");;

TARGET_IDS := [ [1008,521], [1008,683], [1134,55], [1134,53], [1152,154161], [1152,154163],
                 [1872,568], [1872,780] ];;

IdInTargets := function(id)
  local t;
  for t in TARGET_IDS do
    if id[1] = t[1] and id[2] = t[2] then return true; fi;
  od;
  return false;
end;;

matched := Filtered(TARGET83, m -> IdInTargets(m.id));;
Print("matched count = ", Length(matched), " (expected 15)\n");
for m in matched do
  Print("  index=", m.index, " id=", m.id, " nwords=", Length(m.words), "\n");
od;

if Length(matched) <> 15 then
  Error("extract_deep15_data.g: matched count != 15, got ", Length(matched));
fi;

## write out as GAP source defining DEEP15
f := OutputTextFile("search/iso_census83_deep15_data.g", false);;
SetPrintFormattingStatus(f, false);;
PrintTo(f, "## search/iso_census83_deep15_data.g -- AUTO-GENERATED by search/extract_deep15_data.g\n");
PrintTo(f, "## from search/zcensus83_data.g's TARGET83 (itself extracted from the committed cert\n");
PrintTo(f, "## search/certs/lins_census_2000_v1_20260811.json by search/extract_zcensus83.py).\n");
PrintTo(f, "## The 15 delta>1 (A-type, e=6) window records (search/certs/zcensus83_v2_20260812.json\n");
PrintTo(f, "## target83_detail), each with its canonical_id_words for reconstructing N as a\n");
PrintTo(f, "## subgroup of B3 (needed for the (F2) commutation-rule machinery, which requires the\n");
PrintTo(f, "## full B3/N quotient preserving sigma1,sigma2 markings, not just the isomorphism type).\n");
PrintTo(f, "DEEP15 := [\n");
for i in [1 .. Length(matched)] do
  m := matched[i];
  PrintTo(f, "  rec(index:=", m.index, ", id:=", m.id, ", words:=", m.words, ")");
  if i < Length(matched) then PrintTo(f, ",\n"); else PrintTo(f, "\n"); fi;
od;
PrintTo(f, "];;\n");
CloseStream(f);;
Print("Wrote search/iso_census83_deep15_data.g\n");
Print("EXTRACT_DONE\n");
QUIT;
