## search/k9_sigma_realization_v1.g -- [SIG-1] sigma_1, sigma_2 realization in Aut(G_9) (裁定1132 副次)
##
## 正本: docs/notes/d972_h1_adjudication_v1.md §7 [SIG-1]。
## 設計: sigma_i を G_9=PB3/K^(9) の元として探すのではなく、正典 (1.11)(1.12) の
## 共役作用(c in K^(9) ゆえ c 因子消滅)から Aut(G_9) の元として直接構成する:
##   sigma_bar_1: x |-> x,        y |-> y^-1 x^-1
##   sigma_bar_2: x |-> x^-1 y^-1, y |-> y
## ansatz 不要(実装係の前回試行 scratchpad/try_sigma_k9.g の block-swap ansatz は
## D_9 に位数4の元が無く原理的に0件だった -- その診断への対策としてこの設計)。
##
## 規律: u/c 非接触・封印3量非接触・prereg 量非計算・判定語なし・UNKNOWN 一級。

Read("search/probe/wac_v1/gap_output_prelude.g");
Read("search/gaplib_common.g");
Read("search/week3-battery-common.g");   # MakeGn, AbstractProd, JB, JStr, JPair, JoinC

t0Global := GAPLIB_WallElapsedMs();;

Print("############################################################\n");
Print("# k9_sigma_realization_v1.g -- [SIG-1] alpha_1,alpha_2 in Aut(G_9) (裁定1132)\n");
Print("############################################################\n");

## ================= [S-1] G_9 = PB3/K^(9), order 2916 (既存資産 MakeGn(9)) =================
Print("\n=== [S-1] G_9 := MakeGn(9) ===\n");
g9 := MakeGn(9);;
G9 := g9.G;;  x9 := g9.x;;  y9 := g9.y;;
g9size := Size(G9);;
Print("  |G_9| = ", g9size, " (expect 2916)\n");
g9sizeOk := (g9size = 2916);;
if not g9sizeOk then
  Error("k9_sigma_realization: G_9 order mismatch -- refusing to proceed");
fi;

## ================= [S-2] alpha_1, alpha_2 via GroupHomomorphismByImages =================
Print("\n=== [S-2] alpha_1, alpha_2 construction from canonical (1.11)/(1.12) (c-factor vanished) ===\n");
imgY1 := AbstractProd([y9^-1, x9^-1]);;   # y^-1 x^-1  (AbstractProd = left-to-right paper order)
alpha1 := GroupHomomorphismByImages(G9, G9, [x9, y9], [x9, imgY1]);;
imgX2 := AbstractProd([x9^-1, y9^-1]);;   # x^-1 y^-1
alpha2 := GroupHomomorphismByImages(G9, G9, [x9, y9], [imgX2, y9]);;

alpha1IsFail := (alpha1 = fail);;
alpha2IsFail := (alpha2 = fail);;
Print("  alpha1 construction fail = ", alpha1IsFail, "  alpha2 construction fail = ", alpha2IsFail, "\n");

alpha1IsBij := false;;  alpha2IsBij := false;;
if not alpha1IsFail then alpha1IsBij := IsBijective(alpha1); fi;;
if not alpha2IsFail then alpha2IsBij := IsBijective(alpha2); fi;;
Print("  alpha1 bijective (=automorphism) = ", alpha1IsBij, "\n");
Print("  alpha2 bijective (=automorphism) = ", alpha2IsBij, "\n");

## braid relation check: alpha1 alpha2 alpha1 = alpha2 alpha1 alpha2, verified pointwise on
## generators x9,y9 (sufficient since both sides are endomorphisms of G9=<x9,y9> and G9 is
## generated by x9,y9 -- equality on generators implies equality as homomorphisms).
ApplyChain := function(homlist, g)
  local v, h;
  v := g;
  for h in homlist do v := Image(h, v); od;
  return v;
end;;

lhsX := ApplyChain([alpha1, alpha2, alpha1], x9);;  # (alpha1 then alpha2 then alpha1) applied left-to-right
lhsY := ApplyChain([alpha1, alpha2, alpha1], y9);;
rhsX := ApplyChain([alpha2, alpha1, alpha2], x9);;
rhsY := ApplyChain([alpha2, alpha1, alpha2], y9);;
braidOnX_lr := (lhsX = rhsX);;
braidOnY_lr := (lhsY = rhsY);;

## also check the reverse composition order (GAP CompositionMapping2 convention ambiguity --
## record both interpretations, no verdict)
lhsX_rev := ApplyChain([alpha1, alpha2, alpha1], x9);;  # same list order; GAP Image() applies left-to-right regardless
Print("  braid check (apply order alpha1,alpha2,alpha1 to generators, left-to-right):\n");
Print("    lhs(x)=", lhsX, "  rhs(x)=", rhsX, "  equal_on_x=", braidOnX_lr, "\n");
Print("    lhs(y)=", lhsY, "  rhs(y)=", rhsY, "  equal_on_y=", braidOnY_lr, "\n");
braidHoldsOnGenerators := braidOnX_lr and braidOnY_lr;;
Print("  braid_relation_holds_on_generators = ", braidHoldsOnGenerators, "\n");

## ================= [S-3] H := <alpha_1, alpha_2> <= Aut(G_9), |H| =================
Print("\n=== [S-3] H := <alpha1, alpha2> <= Aut(G_9) ===\n");
hSize := fail;;  hSizeOk := false;;  centerG9Size := fail;;
if alpha1IsBij and alpha2IsBij then
  AutG9H := Group(alpha1, alpha2);;
  hSize := Size(AutG9H);;
  centerG9Size := Size(Center(G9));;
  hSizeOk := (hSize = 17496);;
  Print("  Z(G_9) order = ", centerG9Size, " (=1 predicts |H|=17496 injectivity)\n");
  Print("  |H| = ", hSize, " (predicted 17496 if Z(G_9)=1): ", hSizeOk, "\n");
else
  Print("  [SKIP] alpha1 or alpha2 not bijective -- cannot form H := <alpha1,alpha2> in Aut(G_9)\n");
fi;

## ================= [S-4] alpha_i^2 vs Ad(x), Ad(y) =================
Print("\n=== [S-4] alpha_i^2 vs Ad(x9), Ad(y9) (both conjugation conventions recorded) ===\n");
alpha1SqOnX := fail;; alpha1SqOnY := fail;; alpha2SqOnX := fail;; alpha2SqOnY := fail;;
if alpha1IsBij then
  alpha1SqOnX := ApplyChain([alpha1, alpha1], x9);;
  alpha1SqOnY := ApplyChain([alpha1, alpha1], y9);;
fi;;
if alpha2IsBij then
  alpha2SqOnX := ApplyChain([alpha2, alpha2], x9);;
  alpha2SqOnY := ApplyChain([alpha2, alpha2], y9);;
fi;;

## Ad(x9) conjugation, both conventions
AdRightOnX_x := fail;; AdRightOnY_x := fail;; AdLeftOnX_x := fail;; AdLeftOnY_x := fail;;
AdRightOnX_y := fail;; AdRightOnY_y := fail;; AdLeftOnX_y := fail;; AdLeftOnY_y := fail;;
if x9 <> fail then
  AdRightOnX_x := x9^-1 * x9 * x9;;   # g -> x^-1 g x
  AdRightOnY_x := x9^-1 * y9 * x9;;
  AdLeftOnX_x  := x9 * x9 * x9^-1;;   # g -> x g x^-1
  AdLeftOnY_x  := x9 * y9 * x9^-1;;
fi;;
if y9 <> fail then
  AdRightOnX_y := y9^-1 * x9 * y9;;
  AdRightOnY_y := y9^-1 * y9 * y9;;
  AdLeftOnX_y  := y9 * x9 * y9^-1;;
  AdLeftOnY_y  := y9 * y9 * y9^-1;;
fi;;

Print("  alpha1^2(x) = ", alpha1SqOnX, "   alpha1^2(y) = ", alpha1SqOnY, "\n");
Print("  Ad_right(x)(x) [x^-1 x x] = ", AdRightOnX_x, "   Ad_right(x)(y) [x^-1 y x] = ", AdRightOnY_x, "\n");
Print("  Ad_left(x)(x)  [x x x^-1] = ", AdLeftOnX_x,  "   Ad_left(x)(y)  [x y x^-1] = ", AdLeftOnY_x, "\n");
alpha1SqEqAdRightX := (alpha1SqOnX = AdRightOnX_x) and (alpha1SqOnY = AdRightOnY_x);;
alpha1SqEqAdLeftX  := (alpha1SqOnX = AdLeftOnX_x)  and (alpha1SqOnY = AdLeftOnY_x);;
Print("  alpha1^2 == Ad_right(x) on {x,y} : ", alpha1SqEqAdRightX, "\n");
Print("  alpha1^2 == Ad_left(x)  on {x,y} : ", alpha1SqEqAdLeftX, "\n");

Print("  alpha2^2(x) = ", alpha2SqOnX, "   alpha2^2(y) = ", alpha2SqOnY, "\n");
Print("  Ad_right(y)(x) [y^-1 x y] = ", AdRightOnX_y, "   Ad_right(y)(y) [y^-1 y y] = ", AdRightOnY_y, "\n");
Print("  Ad_left(y)(x)  [y x y^-1] = ", AdLeftOnX_y,  "   Ad_left(y)(y)  [y y y^-1] = ", AdLeftOnY_y, "\n");
alpha2SqEqAdRightY := (alpha2SqOnX = AdRightOnX_y) and (alpha2SqOnY = AdRightOnY_y);;
alpha2SqEqAdLeftY  := (alpha2SqOnX = AdLeftOnX_y)  and (alpha2SqOnY = AdLeftOnY_y);;
Print("  alpha2^2 == Ad_right(y) on {x,y} : ", alpha2SqEqAdRightY, "\n");
Print("  alpha2^2 == Ad_left(y)  on {x,y} : ", alpha2SqEqAdLeftY, "\n");

t1Global := GAPLIB_WallElapsedMs();;
Print("\n総経過 = ", t1Global - t0Global, " ms\n");

## ================= JSON 出力 =================
ComputeSha256File := function(relpath)
  local tmp, f, line;
  tmp := "search/.tmp_sha256_out_k9sigma.txt";;
  Exec(Concatenation("sha256sum \"", relpath, "\" > \"", tmp, "\""));;
  f := InputTextFile(tmp);;
  line := ReadLine(f);;
  CloseStream(f);;
  Exec(Concatenation("rm -f \"", tmp, "\""));;
  return line{[1..64]};
end;;

scriptSha256 := ComputeSha256File("search/k9_sigma_realization_v1.g");;

hSizeStr := "null";;
if hSize <> fail then hSizeStr := String(hSize); fi;;
centerG9SizeStr := "null";;
if centerG9Size <> fail then centerG9SizeStr := String(centerG9Size); fi;;

cert := Concatenation(
  "{\"schema\":\"sigma_realization/v1\"",
  ",\"generated_by\":{\"tool\":\"GAP 4.16.0\",\"script\":\"search/k9_sigma_realization_v1.g\",\"order\":\"裁定1132 ([CP] (H1) 副次 W4 対照)\"}",
  ",\"gap_version\":\"", GAPInfo.Version, "\"",
  ",\"spec_ref\":\"docs/notes/d972_h1_adjudication_v1.md §7 [SIG-1]\"",
  ",\"s1_g9\":{\"g9_size\":", String(g9size), ",\"g9_size_expected\":2916,\"g9_size_ok\":", JB(g9sizeOk), "},",
  "\"s2_alpha_construction\":{",
    "\"alpha1_construction_fail\":", JB(alpha1IsFail), ",\"alpha1_is_bijective\":", JB(alpha1IsBij), ",",
    "\"alpha2_construction_fail\":", JB(alpha2IsFail), ",\"alpha2_is_bijective\":", JB(alpha2IsBij), ",",
    "\"braid_relation_holds_on_generators\":", JB(braidHoldsOnGenerators), ",",
    "\"braid_detail\":{\"equal_on_x\":", JB(braidOnX_lr), ",\"equal_on_y\":", JB(braidOnY_lr), "}",
  "},",
  "\"s3_h_group\":{",
    "\"h_size\":", hSizeStr, ",\"h_size_expected_if_center_trivial\":17496,\"h_size_matches_expected\":", JB(hSizeOk), ",",
    "\"center_g9_size\":", centerG9SizeStr,
  "},",
  "\"s4_alpha_squared_vs_ad\":{",
    "\"alpha1_squared_eq_ad_right_x\":", JB(alpha1SqEqAdRightX), ",",
    "\"alpha1_squared_eq_ad_left_x\":", JB(alpha1SqEqAdLeftX), ",",
    "\"alpha2_squared_eq_ad_right_y\":", JB(alpha2SqEqAdRightY), ",",
    "\"alpha2_squared_eq_ad_left_y\":", JB(alpha2SqEqAdLeftY), ",",
    "\"note\":\"Ad_right(g)(h):=g^-1 h g ; Ad_left(g)(h):=g h g^-1. どちらの規約が正典と一致するかは判定しない(生値のみ)。\"",
  "},",
  "\"u_touched\":false,\"c_touched\":false,\"prereg_quantities_untouched\":true",
  ",\"no_verdict_note\":\"machine values only; verdict は司令塔/数学者。UNKNOWN は一級の結果。\"",
  ",\"total_elapsed_ms\":", String(t1Global - t0Global),
  ",\"provenance\":{\"script_sha256\":\"", scriptSha256, "\"}",
  "}"
);;

outPath := "search/certs/k9_sigma_realization_v1_20260813.json";;
WriteFile(outPath, cert);;
Print("\nwrote ", outPath, "\n");
Print("script sha256 = ", scriptSha256, "\n");
Print("K9_SIGMA_REALIZATION_DONE\n");
QUIT;
