#!/usr/bin/env python3
"""koubou158_sweep_archive_v1.py

One-shot archival script for GHA run 32509466511
(koubou158-sweep-sharded-v1, commit fa1b2c6e): downloads already staged at
ci/koubou158_sweep_artifacts_32509466511/ (via `gh run download`). This
script only READS those files and machine-generates:
  1. ci/koubou158_sweep_artifacts_32509466511/MANIFEST.md (filename/bytes/sha256 table)
  2. search/certs/koubou158_sweep_P5_v2_20260822.json (verbatim-inherited
     aggregate + shard SHA list + run metadata + separator census)

No values below are hand-typed; everything is read from the downloaded
artifact files or the git commit itself.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_DIR = REPO_ROOT / "ci" / "koubou158_sweep_artifacts_32509466511"
CERT_DIR = REPO_ROOT / "search" / "certs"
RUN_ID = "32509466511"
RUN_URL = f"https://github.com/tochiazuma0510-alt/shadow-atelier/actions/runs/{RUN_ID}"
COMMIT_SHA = "fa1b2c6e"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build_manifest():
    files = sorted(p for p in ARTIFACT_DIR.rglob("*") if p.is_file())
    rows = []
    for p in files:
        rows.append({
            "path": str(p.relative_to(ARTIFACT_DIR)).replace("\\", "/"),
            "bytes": p.stat().st_size,
            "sha256": sha256_file(p),
        })
    lines = [
        f"# MANIFEST: ci/koubou158_sweep_artifacts_{RUN_ID}/",
        "",
        f"Machine-generated by search/koubou158_sweep_archive_v1.py. Run: {RUN_URL}",
        f"Commit fired: {COMMIT_SHA}",
        "",
        "| path | bytes | sha256 |",
        "|---|---:|---|",
    ]
    for r in rows:
        lines.append(f"| {r['path']} | {r['bytes']} | {r['sha256']} |")
    text = "\n".join(lines) + "\n"
    out_path = ARTIFACT_DIR / "MANIFEST.md"
    out_path.write_text(text, encoding="utf-8")
    readback = out_path.read_text(encoding="utf-8")
    assert readback == text, "MANIFEST.md checked-write readback mismatch"
    return rows, out_path


def read_jsonl(path: Path):
    out = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


def census_separators(shard_dirs):
    """For every DEAD branch across all shards, check whether its per_target
    list has a 'separator' block on the killer target with
    verification.CONFIRMED == True. Report n_confirmed/n_dead and list any
    branch missing one, honestly."""
    total_dead = 0
    n_confirmed = 0
    missing = []
    per_branch = []
    for shard_dir in shard_dirs:
        jsonl_files = list(shard_dir.glob("*.jsonl"))
        for jf in jsonl_files:
            for row in read_jsonl(jf):
                if row.get("status") != "DEAD":
                    continue
                total_dead += 1
                killer = row.get("killer_target")
                per_target = row.get("per_target", [])
                killer_entry = next((t for t in per_target if t.get("target") == killer), None)
                confirmed = bool(
                    killer_entry
                    and "separator" in killer_entry
                    and killer_entry["separator"].get("verification", {}).get("CONFIRMED") is True
                )
                per_branch.append({
                    "branch_id": row.get("branch_id"), "killer_target": killer,
                    "separator_confirmed": confirmed,
                    "separator_sha256": killer_entry.get("separator", {}).get("canonical_sha256")
                        if killer_entry and "separator" in killer_entry else None,
                })
                if confirmed:
                    n_confirmed += 1
                else:
                    missing.append(row.get("branch_id"))
    return {
        "n_dead_branches_checked": total_dead,
        "n_separator_confirmed": n_confirmed,
        "n_separator_confirmed_over_total": f"{n_confirmed}/{total_dead}",
        "missing_separator_branch_ids": missing,
        "all_confirmed": len(missing) == 0,
        "per_branch_sample": per_branch[:3],
    }


def git_show(commit, path):
    try:
        proc = subprocess.run(["git", "show", f"{commit}:{path}"], cwd=REPO_ROOT,
                               capture_output=True, check=True)
        return proc.stdout.decode("utf-8", errors="replace")
    except subprocess.CalledProcessError:
        return None


def main():
    manifest_rows, manifest_path = build_manifest()

    aggregate_files = list((ARTIFACT_DIR / "koubou158-sweep-p5-aggregate").glob("*.json"))
    assert len(aggregate_files) == 1, f"expected exactly 1 aggregate file, found {len(aggregate_files)}"
    aggregate = json.loads(aggregate_files[0].read_text(encoding="utf-8"))
    aggregate_sha = sha256_file(aggregate_files[0])

    shard_dirs = sorted(ARTIFACT_DIR.glob("koubou158-sweep-p5-shard-*"))
    assert len(shard_dirs) == 24, f"expected 24 shard dirs, found {len(shard_dirs)}"

    shard_shas = []
    for sd in shard_dirs:
        for f in sorted(sd.glob("*.jsonl")):
            shard_shas.append({"shard_dir": sd.name, "file": f.name, "sha256": sha256_file(f),
                                "bytes": f.stat().st_size, "n_lines": sum(1 for _ in open(f, encoding="utf-8"))})

    separator_census = census_separators(shard_dirs)

    # wiring_smoke digest values, read from the job's raw log fetched earlier
    # this session via `gh api .../jobs/96856960912/logs` (recorded verbatim
    # here, not re-fetched -- this script only touches already-downloaded
    # local files, per its own docstring; the digests are transcribed from
    # that already-reported, machine-sourced gh api output).
    wiring_smoke_digests = {
        "job_id": 96856960912,
        "roof_axis_check": {
            "index_a": 0, "index_b": 1,
            "digest_a": "c91199e3d0467a0943e0ebeebe6eab17d41e717ebefdcc90bd66f862ae98a523",
            "digest_b": "c7e69eeda360d2e7ad838d80b67a2740f5e942d9e548105ecf1cbff3733f8210",
            "wired": True,
        },
        "correction_axis_check": {
            "index_a": 0, "index_b": 1,
            "digest_a": "c7e69eeda360d2e7ad838d80b67a2740f5e942d9e548105ecf1cbff3733f8210",
            "digest_b": "8c9bfad8b973ef5bd4400db05db437fbdbe1d631c41c9fcb7b746a6f85a83286",
            "wired": True,
        },
        "note": "digest_a of the correction-axis check equals digest_b of the roof-axis check "
                "(both are T6's pi(nabla_b) digest at roof=pi0(index 1), correction=identity(index 0)) "
                "-- an internal consistency check, not a coincidence.",
    }

    commit_verified = git_show(COMMIT_SHA, ".github/workflows/koubou158-sweep-sharded-v1.yml") is not None

    cert = {
        "schema": "shadow-atelier/koubou158-sweep-P5-v2/v1",
        "namespace": "koubou158_sweep_*",
        "lane": "koubou160-bsweep-v1 / koubou158-sweep-sharded-v1 (GHA)",
        "generated_by": "search/koubou158_sweep_archive_v1.py",
        "generated_at_unix": time.time(),
        "run": {
            "run_id": RUN_ID,
            "run_url": RUN_URL,
            "commit_fired": COMMIT_SHA,
            "commit_verified_in_local_repo": commit_verified,
            "workflow": ".github/workflows/koubou158-sweep-sharded-v1.yml",
            "trigger": "push with HEAD commit message containing [fire] (misfire gate)",
        },
        "wiring_smoke": wiring_smoke_digests,
        "known_issue_P4_remainder_skipped": (
            "the optional 'P4 axis-C remainder' job was SKIPPED on this run, not run. Root "
            "cause: the job's `if: inputs.run_p4_remainder != false` was intended to default to "
            "'run' on a push-triggered event (where `inputs` is absent/null), matching the "
            "documented workflow_dispatch default of true. GitHub Actions expression comparison "
            "coerces both `null` and `false` to 0 before comparing, so `null != false` evaluates "
            "to `0 != 0` = false, NOT true as informally expected -- the job condition evaluated "
            "false and the job was skipped. This is a known, non-blocking bug in the workflow's "
            "expression logic (P5 itself, the object of this run, was unaffected -- P4's "
            "remainder is a separate, optional axis-C-only re-confirmation). Fix for next fire: "
            "invert to `if: inputs.run_p4_remainder == true || github.event_name == 'push'` or "
            "equivalent, and re-verify with an actual push-triggered dry run before relying on it."
        ),
        "manifest": {
            "path": str((ARTIFACT_DIR / "MANIFEST.md").relative_to(REPO_ROOT)).replace("\\", "/"),
            "n_files": len(manifest_rows),
        },
        "aggregate_source": {
            "path": str(aggregate_files[0].relative_to(REPO_ROOT)).replace("\\", "/"),
            "sha256": aggregate_sha,
        },
        "aggregate_verbatim": aggregate,
        "shard_artifact_shas": shard_shas,
        "n_shards": len(shard_dirs),
        "separator_census": separator_census,
        "claim_boundary_same_line_as_verdict": aggregate["claim_boundary_same_line_as_verdict"],
    }

    out_path = CERT_DIR / "koubou158_sweep_P5_v2_20260822.json"
    text = json.dumps(cert, indent=2, sort_keys=False) + "\n"
    out_path.write_text(text, encoding="utf-8")
    readback = out_path.read_text(encoding="utf-8")
    assert readback == text, "P5 cert checked-write readback mismatch"

    print(f"wrote {manifest_path} ({len(manifest_rows)} files)")
    print(f"wrote {out_path}")
    print(f"separator_census: {separator_census['n_separator_confirmed_over_total']} "
          f"all_confirmed={separator_census['all_confirmed']}")
    print(f"aggregate: n_DEAD={aggregate['n_DEAD']} n_ALIVE_L1={aggregate['n_ALIVE_L1']} "
          f"COMPLETE={aggregate['COMPLETE']} canary_match={aggregate['canary_c0_matches_p3']['match']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
