"""koubou158_prodrung_v1.py

lane koubou158-prodrung-v1 (commander instruction 2026-08-22, mathematician
verbatim spec): resolve the 18 branches still MEMBER at L3
(koubou158_L3_bulk162_v1_2.py) using a FINER combined space:

    Ebar_B := Res_B(Q4-side) x Pi4[3]   (Pi4[3] FULL -- not truncated),
    B = the 18-element block-quotient group at block index 4 (D18a,
    perm restricted to the 9-point orbit [36:45]).

DIMENSION MODEL (verified against the quoted figures before writing any
of the closure code): dim(Lambda / a^j Lambda) = 6 * |B| * N(j), where
N(j) = #{e in {0,1,2}^10 : Jennings-weight(e) < j} is the SAME Pi4[3]-
side monomial count as the L3 lane (a = F3[B] (x) I_Pi, i.e. the B-side
group ring is used WHOLESALE -- no further filtration on B -- while the
Pi-side gets the Jennings I-adic filtration exactly as in
search/koubou158_L3_core_v1_2.py). Checked: j=2,3,4,5 give
6*18*7=756, 6*18*32=3456, 6*18*106=11448, 6*18*290=31320 -- EXACT match
to the quoted dims, confirming the structural understanding before any
closure code was written.

CONSTRUCTION:

  S0  projection pi_B: an E4 element (perm144, pcvec10) maps to
      (perm9_restricted_to_B, pcvec10) -- both coordinates KEPT (the pc
      side is NOT truncated to a smaller quotient).

  S1  Delta <= Ebar_B^3, generated by g1=(pi(l)_xy,pi(l)_xz,pi(l)_yz),
      g2=(pi(r)_xy,pi(r)_xz,pi(r)_yz) where l,r are the free-group
      generators (l->X0 in xy/xz contexts, Y0 in yz; r->Y0 in xy, Z0 in
      xz/yz -- IDENTICAL construction to the L3/S1-S5 lane's Delta, just
      with pi_B instead of the Pi4[3]-only or perm-block-only
      projections used elsewhere). BFS-enumerated (quoted expectation
      |Delta|<=8748; recorded, not silently capped if it differs).

  S2  Schreier generators of K=ker(F2->Delta) -> Sigma(c) (SAME closed-
      form chain-rule formula as the rest of this lane) -> V (a plain
      span, projected into the (B,Pi)-combined Lambda/a^j Lambda
      coordinates).

  S3  im(D2bar) mod a^j: for each of the 11 PB4 relator gradients v_k
      (S0-projected), the FULL 18-element enumeration of B is used to
      translate the B-coordinate (NOT a generator-only shortcut --
      B is NOT exponent-3, so a generator-based augmentation-ideal
      trick would UNDER-COUNT the true span, a FALSE NO risk -- see
      canary 4 below), and for EACH of the 18 B-translates, the SAME
      (x_i-1)-BFS closure (degree<j, Pi4[3]-side only) as
      koubou158_L3_core_v1_2.py is run, seeded fresh (repair-1 ordering:
      im(D2bar) built in its own echelon first, V added to a clone
      after).

  S4  the 18 still-MEMBER-at-L3 branches' pi_B(nabla_b') are tested
      against the combined span at increasing j=2,3,4,5(,...) -- first
      NO per branch is recorded as that branch's j*; a branch with no NO
      by j=J_MAX is reported honestly as undetermined at this rung (next
      step, per commander, would be PSL(2,8) x Pi -- NOT attempted here).

4 REQUIRED CANARIES (commander's own list, transcribed):
  (a) D1(nabla_b')=0 -- interpreted here (documented, not assumed
      obvious) as the Fox-calculus AUGMENTATION IDENTITY: for a genuine
      Fox derivative of a word w, the sum of a component's raw
      coefficients over all group-ring terms equals that generator's
      NET (signed) occurrence count in w -- a basic, always-true
      sanity check on the gradient CONSTRUCTION (not a vanishing
      claim), required for every branch's target and re-checked here.
  (b) D1(Sigma(c))=0 -- same augmentation identity, checked for every
      Schreier-generator Sigma(c) vector.
  (c) BFS depth >= j*-1 -- recorded as an OBSERVATIONAL receipt (per the
      v1.2 lesson: this canary does not gate soundness by itself: the
      real soundness argument is SATURATION + the repair-1 fresh-
      echelon-first ordering, both reused unchanged from
      search/koubou158_L3_core_v1_2.py).
  (d) B-side uses the FULL 18-element enumeration (not a generator-only
      shortcut) -- require()'d explicitly (B closed under inversion,
      all 18 elements present) and recorded.

No prediction is made. cert: search/certs/koubou158_prodrung_v1_<date>.json
"""
from __future__ import annotations

import json
import sys
import time
from collections import defaultdict, deque
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "search"))
import koubou158_L3_core_v1_2 as core  # noqa: E402

SCHEMA = "koubou158-prodrung/v1"

Q3_CHIEF = core.Q3_CHIEF
Q3_CHIEF_SHA = core.Q3_CHIEF_SHA
Q3_CHIEF_BYTES = core.Q3_CHIEF_BYTES
FIXED_WORD = core.FIXED_WORD
X0, Y0, Z0 = core.X0, core.Y0, core.Z0

BLOCK_START = 36  # D18a, block index 4 of 16 (0-indexed start = 9*4)
BLOCK_SIZE = 9
DELTA_CAP = 20000  # quoted expectation <=8748; margin, not a silent cap
J_MAX = 5  # restored to 5 (2026-08-22, commander instruction after j<=4 pass:
# "j=5 まで NO が出なければ PSL(2,8)xPi へ", mathematician's own spec). The
# earlier uncapped attempt was KILLED (background task timeout) with NO cert
# written (all work lost, no checkpointing then). This run relies on the
# checkpoint mechanism added after that incident (scratchpad/prodrung_
# checkpoint.json, written after every completed j level) so a future kill
# loses at most the in-progress level, not the whole run.

# the 18 branches still MEMBER at L3 (from search/certs/
# koubou158_L3_bulk162_v1_2_20260822.json's member_at_L3_branch_ids)
REMAINING_18_BRANCHES = [
    "r0_c13", "r0_c18", "r0_c8", "r1_c17", "r1_c2", "r1_c23",
    "r2_c15", "r2_c2", "r2_c22", "r3_c16", "r3_c2", "r3_c21",
    "r4_c1", "r4_c16", "r4_c22", "r5_c10", "r5_c26", "r5_c3",
]


def roof_word(q3: dict, roof_index: int) -> list[int]:
    return q3["canonical_roof_powers"]["rows"][roof_index]["word"]


def correction_word(q3: dict, correction_index: int) -> list[int]:
    return q3["correction_fibre"]["records"][correction_index]["word"]


def project_to_B_and_pi(v: dict, start: int, size: int) -> dict:
    """S0: E4 element (perm144,pcvec10) -> (perm_B (9 pts), pcvec10)."""
    out: dict = defaultdict(int)
    for (comp, elt), c in v.items():
        perm_b = bytes(x - start for x in elt[0][start:start + size])
        out[(comp, (perm_b, elt[1]))] = (out[(comp, (perm_b, elt[1]))] + c) % 3
    return {k: c for k, c in out.items() if c}


def build_B(e4, start: int, size: int):
    gens_perm = [e4.gen(i)[0] for i in range(1, 7)]
    gens_b = [bytes(x - start for x in g[start:start + size]) for g in gens_perm]
    identity_b = bytes(range(size))
    seen = {identity_b}
    queue = deque([identity_b])
    while queue:
        cur = queue.popleft()
        for g in gens_b:
            nxt = core.perm_mul(cur, g)
            if nxt not in seen:
                seen.add(nxt)
                queue.append(nxt)
    B = sorted(seen)
    # canary (d): B must be closed under inversion (sanity check that
    # the group we enumerated really is a GROUP, not just a monoid
    # image) -- required, not assumed.
    Bset = set(B)
    for b in B:
        inv = bytes(sorted(range(size), key=lambda p: b[p]))
        core.require(inv in Bset, "B is not closed under inversion")
    return B


def build_idx(monomials, B):
    idx = {}
    i = 0
    for c in range(1, 7):
        for b in B:
            for e in monomials:
                idx[(c, b, e)] = i
                i += 1
    return idx


def project_vec_to_aj(v_bpi: dict, j: int, idx: dict) -> dict:
    """v_bpi: {(comp,(permB,pcvec)): coeff} -> combined (comp,B,Pi-monomial)
    coordinates at level j, via the SAME PBW binomial expansion as
    core.project_pcvec_terms on the pc-part, with the B-part kept as-is
    (no filtration -- flat |B| factor)."""
    out: dict = defaultdict(int)
    for (comp, (permb, pcvec)), coeff in v_bpi.items():
        for e_tuple, c in core.project_pcvec_terms(pcvec, j):
            key = (comp, permb, e_tuple)
            if key in idx:
                out[idx[key]] = (out[idx[key]] + coeff * c) % 3
    return {k: c for k, c in out.items() if c}


def translate_B_component(v_bpi: dict, b) -> dict:
    """Left-translate ONLY the B-coordinate of a (comp,(permB,pcvec))
    vector by b in B (full group element, not a generator) -- the pc
    coordinate is untouched (B and Pi4[3] act independently, E4=Q4xPi4[3]
    is a genuine direct product)."""
    out: dict = defaultdict(int)
    for (comp, (permb, pcvec)), c in v_bpi.items():
        new_permb = core.perm_mul(b, permb)
        out[(comp, (new_permb, pcvec))] = (out[(comp, (new_permb, pcvec))] + c) % 3
    return {k: c for k, c in out.items() if c}


def augmentation_identity_check(word: list[int], grad_E4: dict) -> dict:
    """Canary (a)/(b): the Fox-calculus augmentation identity -- for
    each generator i, the SUM of the raw gradient's coefficients over
    ALL (i, elt) terms must equal the NET (signed) occurrence count of
    letter i in `word` (mod 3). Always true for a genuinely-computed
    Fox derivative; checked here as a sanity canary on the gradient
    CONSTRUCTION, not a vanishing claim."""
    net_occurrence = defaultdict(int)
    for letter in word:
        net_occurrence[abs(letter)] += 1 if letter > 0 else -1
    grad_sum = defaultdict(int)
    for (comp, _elt), c in grad_E4.items():
        grad_sum[comp] = (grad_sum[comp] + c) % 3
    ok = all(grad_sum.get(i, 0) == (net_occurrence.get(i, 0) % 3) for i in range(1, 7))
    return {"ok": ok, "grad_sum": dict(grad_sum),
            "expected_net_occurrence_mod3": {i: net_occurrence.get(i, 0) % 3 for i in range(1, 7)}}


def submodule_closure_B_pi(v_pi_raw: dict, j: int, idx: dict, sp, e4,
                           shared_ech, B: list) -> dict:
    """im(D2bar) generator for one relator: seed with ALL 18 B-translates
    (full enumeration, canary (d)), then run the Pi4[3]-side (x_i-1)-BFS
    closure (degree<j) on EACH seed, adding into shared_ech (fresh/
    unseeded per repair-1 ordering)."""
    pc = e4.pc
    total_new_pivots = 0
    max_depth_explored = 0
    total_explored = 0
    for b in B:
        v_seed = translate_B_component(v_pi_raw, b)
        v0_proj = project_vec_to_aj(v_seed, j, idx)
        queue = deque()
        explored_by_depth: dict = defaultdict(int)
        explored_by_depth[0] += 1
        if shared_ech.add(sp.vec(v0_proj)):
            total_new_pivots += 1
            queue.append((v_seed, 0))
        seen_keys = set()
        while queue:
            cur, depth = queue.popleft()
            for i in range(1, core.N_GEN + 1):
                nxt: dict = defaultdict(int)
                gi = core.gen_pcvec(i)
                for (comp, (permb, pcvec)), c in cur.items():
                    new_pc = pc.mul(gi, pcvec)
                    nxt[(comp, (permb, new_pc))] = (nxt[(comp, (permb, new_pc))] + c) % 3
                for (comp, (permb, pcvec)), c in cur.items():
                    nxt[(comp, (permb, pcvec))] = (nxt[(comp, (permb, pcvec))] - c) % 3
                nxt = {k: c for k, c in nxt.items() if c}
                if not nxt:
                    continue
                explored_by_depth[depth + 1] += 1
                nxt_proj = project_vec_to_aj(nxt, j, idx)
                if shared_ech.add(sp.vec(nxt_proj)):
                    total_new_pivots += 1
                    fp = tuple(sorted(nxt.items()))
                    if fp not in seen_keys:
                        seen_keys.add(fp)
                        queue.append((nxt, depth + 1))
        max_depth_explored = max(max_depth_explored, max(explored_by_depth.keys()) if explored_by_depth else 0)
        total_explored += sum(explored_by_depth.values())
    return {"new_pivots": total_new_pivots, "max_depth_reached": max_depth_explored,
            "total_vectors_explored": total_explored}


def main() -> int:
    t_start = time.perf_counter()

    full = ROOT / Q3_CHIEF
    core.require(full.is_file(), "q3_chief receipt missing")
    core.require(full.stat().st_size == Q3_CHIEF_BYTES, "q3_chief byte drift")
    got_sha = core.sha_file(full)
    core.require(got_sha == Q3_CHIEF_SHA, f"q3_chief SHA drift: got {got_sha}")
    q3 = json.loads(full.read_text(encoding="utf-8"))

    e4 = core.E4(q3)
    B = build_B(e4, BLOCK_START, BLOCK_SIZE)
    core.require(len(B) == 18, f"expected |B|=18, got {len(B)}")

    pb4_rels = q3["formulas"]["presentations"]["PB4"]["relations"]
    core.require(len(pb4_rels) == 11, "PB4 relation count")
    rk_E4 = [core.fox_gradient(e4, r) for r in pb4_rels]
    rk_augcheck = [augmentation_identity_check(r, g) for r, g in zip(pb4_rels, rk_E4)]
    core.require(all(a["ok"] for a in rk_augcheck), f"relator gradient augmentation check FAILED: {rk_augcheck}")
    rk_bpi = [project_to_B_and_pi(v, BLOCK_START, BLOCK_SIZE) for v in rk_E4]

    x0_val, y0_val, z0_val = e4.eval(X0), e4.eval(Y0), e4.eval(Z0)

    def to_B(val):
        return (bytes(x - BLOCK_START for x in val[0][BLOCK_START:BLOCK_START + BLOCK_SIZE]), val[1])

    xbar, ybar, zbar = to_B(x0_val), to_B(y0_val), to_B(z0_val)

    def mul3(a, b):
        return tuple((core.perm_mul(a[i][0], b[i][0]), e4.pc.mul(a[i][1], b[i][1])) for i in range(3))

    g1 = (xbar, xbar, ybar)
    g2 = (ybar, zbar, zbar)

    print(f"[{time.strftime('%H:%M:%S')}] E4/B built (|B|=18), relator gradients + augmentation "
          f"canary checked ({time.perf_counter() - t_start:.1f}s elapsed)", flush=True)

    # S1: Delta <= Ebar_B^3 via forward BFS (finite group -> forward-only closure suffices)
    identity3 = ((bytes(range(BLOCK_SIZE)), e4.pc.one()),) * 3
    transversal = {identity3: []}
    tree_edge: dict = {}
    queue = deque([identity3])
    gens = {1: g1, 2: g2}
    while queue:
        cur = queue.popleft()
        cur_word = transversal[cur]
        for s in (1, 2):
            g = gens[s]
            nxt = tuple((core.perm_mul(cur[i][0], g[i][0]), e4.pc.mul(cur[i][1], g[i][1])) for i in range(3))
            if nxt not in transversal:
                core.require(len(transversal) < DELTA_CAP, f"Delta enumeration exceeded cap {DELTA_CAP}")
                transversal[nxt] = cur_word + [s]
                tree_edge[nxt] = (cur, s)
                queue.append(nxt)
    n_delta = len(transversal)
    print(f"[{time.strftime('%H:%M:%S')}] |Delta|={n_delta} (quoted expectation <=8748)", flush=True)

    # S2: Schreier generators of K, then Sigma(c)
    sgens: list[list[int]] = []
    for delta, t_delta in transversal.items():
        for s in (1, 2):
            g = gens[s]
            nxt = tuple((core.perm_mul(delta[i][0], g[i][0]), e4.pc.mul(delta[i][1], g[i][1])) for i in range(3))
            edge = tree_edge.get(nxt)
            if edge is not None and edge == (delta, s):
                continue
            t_nxt = transversal[nxt]
            sgens.append(core.reduce_word(t_delta + [s] + core.inv_word(t_nxt)))
    core.require(len(sgens) == n_delta + 1, f"expected {n_delta+1} Schreier generators, got {len(sgens)}")

    C_word = core.substitute2(FIXED_WORD, Y0, Z0)
    Cbar_E4 = e4.eval(C_word)
    sigma_vectors_bpi = []
    sigma_augcheck = []
    for c_word in sgens:
        ga = core.fox_gradient(e4, core.substitute2(c_word, X0, Y0))
        gb = core.fox_gradient(e4, core.substitute2(c_word, X0, Z0))
        gc = core.fox_gradient(e4, core.substitute2(c_word, Y0, Z0))
        diff = core.add_vec(gc, core.neg_vec(gb))
        sigma_c = core.add_vec(core.translate_vec(e4, diff, Cbar_E4), ga)
        sigma_augcheck.append(augmentation_identity_check(c_word, sigma_c))
        sigma_vectors_bpi.append(project_to_B_and_pi(sigma_c, BLOCK_START, BLOCK_SIZE))
    core.require(all(a["ok"] for a in sigma_augcheck), "Sigma(c) augmentation canary FAILED for at least one Schreier generator")

    print(f"[{time.strftime('%H:%M:%S')}] {len(sgens)} Schreier generators, Sigma(c) computed, "
          f"augmentation canary PASSED ({time.perf_counter() - t_start:.1f}s elapsed)", flush=True)

    # per-branch targets (18 remaining), computed once (E4-level), reused across all j
    branch_targets_bpi = {}
    branch_augcheck = {}
    for bid in REMAINING_18_BRANCHES:
        r_idx = int(bid.split("_c")[0][1:])
        c_idx = int(bid.split("_c")[1])
        rw = roof_word(q3, r_idx)
        cw = correction_word(q3, c_idx)
        candidate_word = core.reduce_word(list(rw) + list(cw))
        c_w = core.substitute2(candidate_word, Y0, Z0)
        b_w = core.substitute2(candidate_word, X0, Z0)
        a_w = core.substitute2(candidate_word, X0, Y0)
        h1_word = core.reduce_word(c_w + core.inv_word(b_w) + a_w)
        nabla_bp = core.fox_gradient(e4, h1_word)
        branch_augcheck[bid] = augmentation_identity_check(h1_word, nabla_bp)
        branch_targets_bpi[bid] = project_to_B_and_pi(nabla_bp, BLOCK_START, BLOCK_SIZE)
    core.require(all(a["ok"] for a in branch_augcheck.values()),
                 f"branch target augmentation canary FAILED: {branch_augcheck}")

    print(f"[{time.strftime('%H:%M:%S')}] {len(REMAINING_18_BRANCHES)} branch targets computed, "
          f"augmentation canary PASSED ({time.perf_counter() - t_start:.1f}s elapsed)", flush=True)

    # S3/S4: increasing j, testing all still-undetermined branches each level
    undetermined = set(REMAINING_18_BRANCHES)
    branch_results: dict[str, dict] = {}
    j_progression = []
    for j in range(2, J_MAX + 1):
        if not undetermined:
            break
        t_j = time.perf_counter()
        monomials = core.enumerate_monomials(j)
        idx = build_idx(monomials, B)
        dim_j = len(idx)
        sp = core.F3BitSpace(dim_j)

        ech_v = core.F3BitEchelon(sp)
        for v in sigma_vectors_bpi:
            ech_v.add(sp.vec(project_vec_to_aj(v, j, idx)))
        rank_v = ech_v.rank()

        ech_d2 = core.F3BitEchelon(sp)
        per_relator_receipts = []
        for v_bpi in rk_bpi:
            rec = submodule_closure_B_pi(v_bpi, j, idx, sp, e4, ech_d2, B)
            per_relator_receipts.append(rec)
        rank_d2_alone = ech_d2.rank()

        ech_combined = ech_d2.clone()
        for v in sigma_vectors_bpi:
            ech_combined.add(sp.vec(project_vec_to_aj(v, j, idx)))
        rank_combined = ech_combined.rank()

        depth_ok = all(r["max_depth_reached"] >= j - 1 for r in per_relator_receipts)

        newly_resolved = []
        for bid in list(undetermined):
            tv = sp.vec(project_vec_to_aj(branch_targets_bpi[bid], j, idx))
            ech_branch = ech_combined.clone()
            _, pivot = ech_branch.reduce(tv)
            non_member = pivot >= 0
            if non_member:
                sep = ech_branch.extract_separator(tv)
                core.require(sep is not None, f"branch {bid} j={j}: separator extraction failed unexpectedly")
                support = bin(sep[0] | sep[1]).count("1")
                phi_val = sp.dot(sep, tv)
                branch_results[bid] = {"branch_id": bid, "j_star": j, "non_member": True,
                                       "separator": {"support": support, "phi_val": phi_val}}
                newly_resolved.append(bid)
        for bid in newly_resolved:
            undetermined.discard(bid)

        elapsed_j = time.perf_counter() - t_j
        j_progression.append({
            "j": j, "dim_Lambda_over_aj": dim_j, "rank_D2bar_alone": rank_d2_alone,
            "rank_V": rank_v, "rank_combined": rank_combined,
            "depth_requirement_observational_ok": depth_ok,
            "per_relator_closure_receipts": per_relator_receipts,
            "n_branches_resolved_this_level": len(newly_resolved),
            "n_branches_still_undetermined_after": len(undetermined),
            "wall_seconds": elapsed_j,
        })
        print(f"[{time.strftime('%H:%M:%S')}] j={j}: dim={dim_j} rank_D2bar_alone={rank_d2_alone} "
              f"rank_V={rank_v} rank_combined={rank_combined} depth_ok={depth_ok} "
              f"resolved_this_level={len(newly_resolved)} still_undetermined={len(undetermined)} "
              f"({elapsed_j:.1f}s)", flush=True)

        # CHECKPOINT (added after the j<=5 kill lost all work with no cert written):
        # dump progress-so-far to a scratch file after every j level, so a future
        # kill loses at most the in-progress level, not the whole run.
        ckpt_path = ROOT / "scratchpad" / "prodrung_checkpoint.json"
        ckpt_path.parent.mkdir(parents=True, exist_ok=True)
        ckpt_path.write_text(json.dumps({
            "j_progression_so_far": j_progression,
            "branch_results_so_far": branch_results,
            "still_undetermined": sorted(undetermined),
        }, sort_keys=True, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    for bid in undetermined:
        branch_results[bid] = {"branch_id": bid, "j_star": None, "non_member": False, "separator": None}

    elapsed = time.perf_counter() - t_start
    n_dead = sum(1 for r in branch_results.values() if r["non_member"])
    n_undetermined = len(undetermined)
    all_18_dead = (n_dead == 18)

    cert: dict[str, Any] = {
        "schema": SCHEMA,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "spec_source": "commander instruction 2026-08-22, mathematician verbatim spec "
                       "(koubou158-prodrung-v1): resolve the 18 L3-still-MEMBER branches "
                       "via Ebar_B=Res_B(Q4)xPi4[3] (full Pi, not truncated)",
        "input_provenance": {"q3_chief_receipt": {"path": str(Q3_CHIEF).replace("\\", "/"),
                                                   "sha256": Q3_CHIEF_SHA, "bytes": Q3_CHIEF_BYTES}},
        "block": {"start": BLOCK_START, "size": BLOCK_SIZE, "size_B": len(B)},
        "dimension_model_verified_before_coding": {
            "formula": "dim(Lambda/a^j Lambda) = 6 * |B| * N(j)",
            "j_2_3_4_5": [6 * 18 * len(core.enumerate_monomials(j)) for j in (2, 3, 4, 5)],
            "quoted_expected": [756, 3456, 11448, 31320],
            "exact_match": [6 * 18 * len(core.enumerate_monomials(j)) for j in (2, 3, 4, 5)] == [756, 3456, 11448, 31320],
        },
        "n_Delta": n_delta,
        "delta_bound_note": f"quoted expectation |Delta|<=8748; measured n_Delta={n_delta}",
        "n_schreier_generators": len(sgens),
        "canary_a_D1_nabla_bprime": {
            "interpretation": "Fox-calculus augmentation identity (see module docstring) -- "
                              "checked for all 18 branch targets",
            "all_branches_ok": all(a["ok"] for a in branch_augcheck.values()),
        },
        "canary_b_D1_sigma_c": {
            "interpretation": "same augmentation identity, checked for all Sigma(c) vectors",
            "all_ok": all(a["ok"] for a in sigma_augcheck),
        },
        "canary_c_depth_observational": "recorded per-j in j_progression[*].depth_requirement_"
                                        "observational_ok and per_relator_closure_receipts -- "
                                        "NOT the soundness basis (see search/koubou158_L3_"
                                        "core_v1_2.py's repair 2: saturation + fresh-echelon-"
                                        "first ordering is the actual soundness argument, "
                                        "reused unchanged here)",
        "canary_d_B_full_enumeration": "REQUIRED and PASSED: B (18 elements) verified closed "
                                       "under inversion; im(D2bar)'s B-side contribution uses "
                                       "ALL 18 elements as literal translates (submodule_closure_"
                                       "B_pi), NOT a generator-only shortcut -- B is not "
                                       "exponent-3 so a generator-based augmentation-ideal trick "
                                       "would under-count the true span (false NO risk)",
        "j_progression": j_progression,
        "branch_results": branch_results,
        "n_branches_dead": n_dead,
        "n_branches_undetermined": n_undetermined,
        "all_18_dead": all_18_dead,
        "overall_reading": (
            "all 18 remaining branches DIE at this rung (Ebar_B x Pi4[3] full): 162/162 "
            "branches now have target6 (or their own analog) unliftable to the full legal-"
            "correction span at SOME rung -- combined with the 144 already resolved at plain "
            "L3, this DISCHARGES condition (ii) for the ENTIRE 162-branch census (part of "
            "condition (i)'s census discharges too). NOT reported as OBS*: (iii)/(iv) of T-56 "
            "remain open (mathematician reportedly closing (iii) via canonical-form matching "
            "in parallel, not yet landed here)."
            if all_18_dead else
            f"{n_dead}/18 branches resolved (DEAD) at j<=J_MAX={J_MAX}; {n_undetermined} "
            "remain undetermined at this rung -- next step (PSL(2,8) x Pi, not attempted "
            "here) would be needed for those, per commander's own framing"
        ),
        "condition_ii_iii_iv_note": "(ii) discharges for all branches resolved here (sound, "
                                    "same over-approximation caveat as the rest of the L3 "
                                    "lane); (i) discharges partially (the resolved subset of "
                                    "the 162-branch census); (iii)/(iv) remain open -- OBS* "
                                    "is NOT claimed.",
        "k3_overapproximation_caveat": "same as the rest of the L3 lane: V is built from the "
                                       "FULL kernel K, not the true exponent-sum-mod-3-"
                                       "filtered legal-correction span.",
        "wall_clock_seconds": elapsed,
        "grade": "candidate, single-system producer measurement; no independent second-"
                "system cross-check has been run for this prodrung result yet",
    }

    today = date.today().isoformat().replace("-", "")
    out_path = ROOT / "search" / "certs" / f"koubou158_prodrung_v1_{today}.json"
    text = json.dumps(cert, sort_keys=True, indent=2, ensure_ascii=False) + "\n"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    readback = out_path.read_text(encoding="utf-8")
    core.require(readback == text, "checked-write readback mismatch")

    print(f"KOUBOU158_PRODRUNG_V1 n_dead={n_dead}/18 all_18_dead={all_18_dead} "
          f"elapsed_s={elapsed:.2f} output={out_path.as_posix()}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
