## search/pchi1_v1.g -- P-CHI-1' (裁定803[3], docs/notes/hunting_chapter_v1_addendum_a.md SS2.4).
## Predicate/domain per the addendum (verbatim, DOMAIN-PIN-compliant -- explicit):
##   Domain: census ALL 46 members (the same 23 pairs x 2 members used in search/hcen_ab_v1.g,
##   id_group list reused verbatim from that already-committed/cross-checked script -- NOT
##   re-derived from the source certs a third time in THIS script; hcen_ab_v1.g's own join was
##   independently cross-checked by crosscheck/check_hcen_ab.py already).
##   Predicate: for each G, take a ChiefSeries(G); for every chief factor W = N1/N2 (N1,N2
##   consecutive terms) that has PRIME order p (i.e. W ~= F_p as an abelian group, a
##   "1-dimensional F_p composition factor"), G acts on W by conjugation, inducing a character
##   chi_W: G -> Aut(W) = Aut(C_p) = (Z/pZ)^* (cyclic of order p-1). Report ord(chi_W) = size of
##   the image of this action (computed via: for each generator g of G, find the multiplier
##   k_g in (Z/pZ)^* such that conjugation-by-g scales a fixed generator of W by k_g; the image's
##   order = lcm of OrderMod(k_g,p) over generators g, since (Z/pZ)^* is cyclic and a subgroup
##   generated by elements of orders d_1..d_n in a cyclic group has order lcm(d_1,...,d_n)).
## Frozen prediction (P-CHI-1', addendum SS2.4): ALL such orders are <=3, across all 46 members.
## A value >=5 would be the addendum's own stated significance threshold (raw report only, no
## verdict language written here -- interpretation is the commander's/mathematician's).
## M5 is NOT part of the 46-member census domain (per hcen_ab_v1.g's own explicit disclosure,
## M5 is "outside_the_23pair_prediction_set") -- NOT included, consistent with the addendum's
## own domain statement ("census 全46メンバー").
Read("search/probe/wac_v1/gap_output_prelude.g");
Read("search/gaplib_common.g");

## ============ 23-pair / 46-member target list (VERBATIM reuse of search/hcen_ab_v1.g's list) ============
PAIRS := [
  rec(pair_fiber:="lt384:idx24:pair0",  index:=24,  m0_id:=[24,3],   m1_id:=[24,3]),
  rec(pair_fiber:="lt384:idx72:pair2",  index:=72,  m0_id:=[72,3],   m1_id:=[72,3]),
  rec(pair_fiber:="lt384:idx120:pair6", index:=120, m0_id:=[120,15], m1_id:=[120,15]),
  rec(pair_fiber:="lt384:idx120:pair7", index:=120, m0_id:=[120,5],  m1_id:=[120,5]),
  rec(pair_fiber:="lt384:idx168:pair11",index:=168, m0_id:=[168,22], m1_id:=[168,22]),
  rec(pair_fiber:="lt384:idx216:pair16",index:=216, m0_id:=[216,3],  m1_id:=[216,3]),
  rec(pair_fiber:="lt384:idx264:pair24",index:=264, m0_id:=[264,12], m1_id:=[264,12]),
  rec(pair_fiber:="lt384:idx312:pair27",index:=312, m0_id:=[312,25], m1_id:=[312,25]),
  rec(pair_fiber:="lt384:idx336:pair30",index:=336, m0_id:=[336,208],m1_id:=[336,208]),
  rec(pair_fiber:="lt384:idx336:pair35",index:=336, m0_id:=[336,114],m1_id:=[336,114]),
  rec(pair_fiber:="lt384:idx360:pair38",index:=360, m0_id:=[360,14], m1_id:=[360,14]),
  rec(pair_fiber:="lt384:idx360:pair39",index:=360, m0_id:=[360,51], m1_id:=[360,51]),
  rec(pair_fiber:="idx384:608",         index:=384, m0_id:=[384,608],m1_id:=[384,608]),
  rec(pair_fiber:="idx750:pair0", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair1", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair2", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair3", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair4", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair5", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair6", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair7", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair8", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
  rec(pair_fiber:="idx750:pair9", index:=750, m0_id:=[750,6], m1_id:=[750,6]),
];;

## measure the twist orders for ALL prime-order (1-dim over F_p) chief factors of G
MeasureTwists := function(idpair)
  local G, cs, i, N1, N2, p, nat, Q, q0, n0, gens, kVals, g, n0g, q0g, k, kk, found,
        twOrd, twists;
  G := SmallGroup(idpair[1], idpair[2]);
  cs := ChiefSeries(G);   # descending: cs[1]=G ... cs[Length(cs)]=1
  twists := [];
  gens := GeneratorsOfGroup(G);
  for i in [1..Length(cs)-1] do
    N1 := cs[i];
    N2 := cs[i+1];
    p := Size(N1)/Size(N2);
    if IsPrimeInt(p) then
      nat := NaturalHomomorphismByNormalSubgroup(N1, N2);
      Q := Image(nat);
      q0 := First(Elements(Q), x -> x <> One(Q));
      n0 := PreImagesRepresentative(nat, q0);
      kVals := [];
      for g in gens do
        n0g := n0^g;              # valid: N1 normal in G, so n0^g in N1 for any g in G
        q0g := Image(nat, n0g);
        found := fail;
        for kk in [1..p-1] do
          if q0^kk = q0g then found := kk; break; fi;
        od;
        if found = fail then Error("could not find multiplier k for chief factor action"); fi;
        Add(kVals, found);
      od;
      if p = 2 then
        twOrd := 1;  # Aut(C_2) trivial
      else
        twOrd := Lcm(List(kVals, kk -> OrderMod(kk, p)));
      fi;
      Add(twists, rec(p:=p, twist_order:=twOrd));
    fi;
  od;
  return twists;
end;;

results := [];;
allTwistOrders := [];;
for pr in PAIRS do
  m0res := MeasureTwists(pr.m0_id);;
  m1res := MeasureTwists(pr.m1_id);;
  Add(results, rec(pair_fiber:=pr.pair_fiber, index:=pr.index, m0_id:=pr.m0_id, m0_twists:=m0res,
                    m1_id:=pr.m1_id, m1_twists:=m1res));
  Append(allTwistOrders, List(m0res, r -> r.twist_order));
  Append(allTwistOrders, List(m1res, r -> r.twist_order));
  Print(pr.pair_fiber, ": m0=", m0res, " m1=", m1res, "\n");
od;

maxTwistOrder := 0;;
if Length(allTwistOrders) > 0 then maxTwistOrder := Maximum(allTwistOrders); fi;
allLe3 := ForAll(allTwistOrders, x -> x <= 3);;
anyGe5 := ForAny(allTwistOrders, x -> x >= 5);;

Print("max_twist_order=", maxTwistOrder, " all_le_3=", allLe3, " any_ge_5=", anyGe5, "\n");

## ============ JSON output ============
JTwist := function(r)
  return Concatenation("{\"p\":", String(r.p), ",\"twist_order\":", String(r.twist_order), "}");
end;;

JMember := function(r)
  return Concatenation("{",
    "\"pair_fiber\":", JStr(r.pair_fiber), ",",
    "\"index\":", String(r.index), ",",
    "\"m0_id_group\":", JPair(r.m0_id[1], r.m0_id[2]), ",",
    "\"m0_twists\":[", JoinC(List(r.m0_twists, JTwist), ","), "],",
    "\"m1_id_group\":", JPair(r.m1_id[1], r.m1_id[2]), ",",
    "\"m1_twists\":[", JoinC(List(r.m1_twists, JTwist), ","), "]",
    "}");
end;;

out := Concatenation(
  "{",
  "\"schema\":\"shadow-atelier/pchi1_v1\",",
  "\"authority\":\"", "\\u88c1\\u5b9a803[3] -- docs/notes/hunting_chapter_v1_addendum_a.md \\u00a72.4 (P-CHI-1' \\u767a\\u6ce8)\",",
  "\"predicate_note\":\"for each G in the census 46-member domain, ChiefSeries(G) is taken; for every consecutive chief factor N1/N2 of PRIME order p, the conjugation action of G on N1/N2 induces a character chi_W:G->(Z/pZ)^*; twist_order=|image(chi_W)| is computed via lcm of OrderMod(k_g,p) over generator images (Z/pZ)^* is cyclic, so this equals the order of the generated subgroup). Domain=all 46 census members (23 pairs, id_group list reused verbatim from the already cross-checked search/hcen_ab_v1.g). M5 excluded (outside the 23-pair census domain per hcen_ab_v1.g's own disclosure).\",",
  "\"P_CHI_1_prime_prediction\":\"all twist orders across all 46 members are <=3\",",
  "\"members\":[", JoinC(List(results, JMember), ","), "],",
  "\"max_twist_order\":", String(maxTwistOrder), ",",
  "\"all_twist_orders_le_3\":", JB(allLe3), ",",
  "\"any_twist_order_ge_5\":", JB(anyGe5), ",",
  "\"no_verdict_note\":\"raw chief-factor primes, twist orders, and booleans only. \\u5224\\u5b9a\\u8a9e\\u306f\\u4e00\\u5207\\u66f8\\u304b\\u306a\\u3044 -- \\u767a\\u52b9\\u306f\\u53f8\\u4ee4\\u5854\\u5c02\\u6a29\\u3002\"",
  "}"
);;

WriteFile("search/certs/pchi1_v1_20260811.json", out);;
Print("Wrote search/certs/pchi1_v1_20260811.json\n");
Print("PCHI1_DONE\n");
QUIT;
