#!/usr/bin/env python3
"""
r6a_gen_gap_data.py -- transcribes search/certs/r6a_scope_freeze_v1_20260806.json
(the frozen R-6a scope cert) into a literal GAP data file
(search/r6a_frozen_members_data.g) for search/r6a_word_iota_v1.g to Read().

Pure transcription: byte-for-byte copy of uid/index/canonical_id_words out of
the already-frozen cert. No new selection, no filtering, no group theory.
"""
import json

FREEZE_PATH = "search/certs/r6a_scope_freeze_v1_20260806.json"
OUT_PATH = "search/r6a_frozen_members_data.g"


def gap_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    with open(FREEZE_PATH, encoding="utf-8") as f:
        d = json.load(f)

    # fiber = the group of members a given member's iota-image is allowed to
    # be matched against. For the 750-clique this is ALL 5 members (one
    # shared fiber); for lt384/L3 it is the member's OWN registered pair
    # (pair_uid) -- NOT the whole 45-pair / 13-pair set, per task scope
    # ("同じ凍結繊維内のどのmemberと一致するか").
    rows = []
    for m in d["set_i_750_clique"]:
        rows.append(("clique750:ALL", m["uid"], 750, m["canonical_id_words"]))
    for m in d["set_ii_lt384"]:
        rows.append((m["pair_uid"], m["uid"], m["index"], m["canonical_id_words"]))
    for m in d["set_iii_L3"]:
        rows.append((m["pair_uid"], m["uid"], m["index"], m["canonical_id_words"]))

    lines = []
    lines.append("## AUTO-GENERATED by search/r6a_gen_gap_data.py from")
    lines.append(f"## {FREEZE_PATH} (sha256 recorded there as frozen_selection_sha256).")
    lines.append("## DO NOT hand-edit. Defines FROZEN_MEMBERS and FROZEN_SELECTION_SHA256.")
    lines.append(f'FROZEN_SELECTION_SHA256 := "{d["frozen_selection_sha256"]}";;')
    lines.append("FROZEN_MEMBERS := [")
    for i, (fiber, uid, index, words) in enumerate(rows):
        words_gap = "[" + ",".join(gap_string(w) for w in words) + "]"
        comma = "," if i < len(rows) - 1 else ""
        lines.append(f'  rec(uid:={gap_string(uid)}, fiber:={gap_string(fiber)}, '
                      f'index:={index}, words:={words_gap}){comma}')
    lines.append("];;")

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH} ({len(rows)} members)")


if __name__ == "__main__":
    main()
