#############################################################################
## search/r6a_word_iota_v1.g -- R-6a word-level iota identification, GAP side
## (system A). sol/sol_reply_112_math38.md F112-5/R-6a; 裁定637 task 2.
##
## Reads the frozen scope cert (search/certs/r6a_scope_freeze_v1_20260806.json,
## produced by search/r6a_extract_and_freeze.py, committed BEFORE this driver
## runs) -- but since GAP has no JSON parser here, the frozen member list is
## re-embedded verbatim as a literal GAP record list below (see
## FROZEN_MEMBERS), generated by search/r6a_gen_gap_data.py from the SAME
## frozen cert (byte-for-byte transcription of canonical_id_words/uid/index;
## no new selection logic). A cross-check against the frozen cert's own
## sha256 is asserted at the top.
##
## THIS SCRIPT DOES NOT COMPUTE iota-equality directly. Per the campaign's
## two-system regime (docs/notes/twin_witness_prereg_iffirst_v1.md SS4.1
## 系統A/系統B), this driver's ONLY job is to export, for every frozen
## member N (as a subgroup of B3 given by its canonical_id_words), a
## permutation representation rho: B3 -> Sym(index) with ker(rho)=N (i.e.
## B3/N realized as a permutation group of degree = index, via
## IsomorphismPermGroup). s1_perm = Image(rho,a), s2_perm = Image(rho,b) are
## exported as plain permutation LISTS (1-indexed images), together with the
## member's own canonical_id_words (for the python side's independent sanity
## check that they map to the identity), the index, and the UID.
##
## ALL actual iota-matching logic (sign-flip the words to get iota(N)'s
## generators, evaluate against every same-fiber candidate's exported
## permutation representation, decide which candidate matches) is done
## INDEPENDENTLY in python (search/r6a_word_iota_checker.py), which does not
## import this file, does not call GAP, and reimplements permutation
## arithmetic and word evaluation from scratch --系統B.
##
## No GT-shadow predicate (hexagon/charming/SURJ/kernel_multiplicity/
## settled/isolated/GTSh/arithmeticity) is evaluated anywhere in this file.
## No TRUE/FALSE verdict is attached to any checker. No stage besides this
## word-level identification is touched.
#############################################################################
Read("search/gaplib_common.g");
Read("search/probe/wac_v1/gap_output_prelude.g");

#############################################################################
## B3 presentation, BYTE-IDENTICAL to search/lins-twin-census-v1.g (same
## generator order/names, same relator) -- the frozen census's canonical_id_
## words are only meaningful against this exact presentation.
#############################################################################
BF3 := FreeGroup("a", "b");;
a := BF3.1;;  b := BF3.2;;
brel := a * b * a * (b * a * b)^-1;;
B3 := BF3 / [brel];;
ga := B3.1;;  gb := B3.2;;
a := ga;;  b := gb;;   ## rebind a,b to the QUOTIENT group's generators so
                        ## EvalString(word_string) below evaluates each
                        ## frozen canonical_id_word (literal GAP syntax, e.g.
                        ## "a^2*b*a^-1*b") directly to a B3 element.

WordToElt := function(s)
  return EvalString(s);
end;;

#############################################################################
## FROZEN_MEMBERS: literal transcription of the frozen cert's three sets.
## Generated by search/r6a_gen_gap_data.py from search/certs/
## r6a_scope_freeze_v1_20260806.json; DO NOT hand-edit. Defines FROZEN_MEMBERS
## (a GAP list of records: uid, fiber, index, words [list of strings]) and
## FROZEN_SELECTION_SHA256 (string, for the cross-check below).
#############################################################################
Read("search/r6a_frozen_members_data.g");;

if FROZEN_SELECTION_SHA256 <> "9c909ef14cd70f9fca07bb99846a489dada9346c284dc47c7cdfb399bfc79ca3" then
  Error("FROZEN_SELECTION_SHA256 in r6a_frozen_members_data.g does not match the frozen cert's own recorded digest -- STOP, re-freeze required before running.");
fi;
Print("Frozen selection sha256 check: OK (", FROZEN_SELECTION_SHA256, ")\n");
Print("FROZEN_MEMBERS count: ", Length(FROZEN_MEMBERS), "\n");

#############################################################################
## Per-member: build N = Subgroup(B3, words), the natural quotient hom, and
## its permutation-group image (degree = index). Export rho(a),rho(b) as
## permutation LISTS (1..index) plus sanity fields.
#############################################################################
PermToList := function(p, n)
  return List([1..n], i -> i^p);
end;;

MemberResults := [];;
t0 := GAPLIB_WallElapsedMs();;
for rec_m in FROZEN_MEMBERS do
  elts := List(rec_m.words, WordToElt);;
  N := Subgroup(B3, elts);;
  hm := NaturalHomomorphismByNormalSubgroup(B3, N);;
  Q := Image(hm);;
  isoQ := IsomorphismPermGroup(Q);;
  Qp := Image(isoQ);;
  rho := CompositionMapping(isoQ, hm);;
  s1p := Image(rho, ga);;
  s2p := Image(rho, gb);;
  measuredIndex := Size(Qp);;
  ok := (measuredIndex = rec_m.index);;
  ## sanity: own words map to identity under rho (N <= ker(rho) by
  ## construction, but confirm the exported perm rep is self-consistent)
  ownWordsTrivial := ForAll(elts, e -> Image(rho, e) = ());;
  Add(MemberResults, rec(uid := rec_m.uid, fiber := rec_m.fiber, index := rec_m.index,
      measuredIndex := measuredIndex, indexOk := ok, ownWordsTrivial := ownWordsTrivial,
      s1_perm := PermToList(s1p, measuredIndex), s2_perm := PermToList(s2p, measuredIndex),
      words := rec_m.words));
  Print("  ", rec_m.uid, ": index=", measuredIndex, " (expect ", rec_m.index, ", ok=", ok,
        ") ownWordsTrivial=", ownWordsTrivial, "\n");
od;
t1 := GAPLIB_WallElapsedMs();;
Print("All members processed. elapsed_ms=", t1-t0, "\n");

ALL_INDEX_OK := ForAll(MemberResults, r -> r.indexOk);;
ALL_OWN_TRIVIAL := ForAll(MemberResults, r -> r.ownWordsTrivial);;
Print("ALL_INDEX_OK=", ALL_INDEX_OK, " ALL_OWN_TRIVIAL=", ALL_OWN_TRIVIAL, "\n");
if not (ALL_INDEX_OK and ALL_OWN_TRIVIAL) then
  Error("Sanity check failed -- STOP before export.");
fi;

#############################################################################
## Write export JSON (permutation reps + own words + UIDs only -- no
## matching/verdict logic here, that is 系統B's job).
#############################################################################
MemberJson := function(r)
  return Concatenation("{\"uid\":", JStr(r.uid), ",\"fiber\":", JStr(r.fiber),
    ",\"index\":", String(r.index), ",\"s1_perm\":", JArr(List(r.s1_perm,String)),
    ",\"s2_perm\":", JArr(List(r.s2_perm,String)),
    ",\"own_words\":", JArr(List(r.words, JStr)), "}");
end;;

report := Concatenation(
"{\n",
"\"schema\":\"r6a-word-iota-gap-export/v1\",\n",
"\"note\":\"System A export ONLY -- permutation representations (rho: B3 -> Sym(index), ker(rho)=N) for every frozen member, plus each member's own canonical_id_words for a python-side sanity re-check. NO iota-matching/equality logic is performed in this file; that is done independently in search/r6a_word_iota_checker.py (系統B, GAP-helper-free).\",\n",
"\"authorization\":\"sol/sol_reply_112_math38.md F112-5/R-6a; 裁定637 task 2\",\n",
"\"frozen_cert\":\"search/certs/r6a_scope_freeze_v1_20260806.json\",\n",
"\"frozen_selection_sha256\":", JStr(FROZEN_SELECTION_SHA256), ",\n",
"\"member_count\":", String(Length(MemberResults)), ",\n",
"\"all_index_ok\":", JB(ALL_INDEX_OK), ",\"all_own_words_trivial\":", JB(ALL_OWN_TRIVIAL), ",\n",
"\"elapsed_ms\":", String(t1-t0), ",\n",
"\"members\":", JArr(List(MemberResults, MemberJson)), "\n",
"}\n");;

OUT_PATH := "search/certs/r6a_word_iota_gap_export_v1_20260806.json";;
WriteFile(OUT_PATH, report);;
Print("Wrote ", OUT_PATH, "\n");
Print("\nR6A_WORD_IOTA_GAP_EXPORT_DONE\n");
QUIT;
