"""
search/u3_model_v1.py -- [U3-1] Z[1/S]-モデルの構成(裁定1118・実装係タスク3・工房分)

正本: docs/notes/r2_r3_unram_execution_spec_v1.md §9 [U3-1]
分担: §14 の表により [U3-1](係数整理)は工房。[U3-2](平滑/エタール・Groebner)・
      [U3-3](判別式->S)は Sol 分担(便123走行中・触らない)。

⚠ prereg 規律(裁定1118 実行指示): 本 script は [U3-1] の範囲(係数行列・モデルの
   記述・Jacobian イデアルの *生成元の記録*)に留める。イデアルの零点集合(特異点の
   実座標)や判別式の *因数分解* は [U3-2]/[U3-3](Sol 分担)の仕事であり、ここでは
   計算しない(§12 の prereg 危険 -- U3-3 の S が P-K9U-1 を先取りする恐れ -- を
   避けるため、そちら側の仕事に踏み込まない)。
   Delta(E)=-216=-2^3*3^3 は既公開値(宣言 v4 + r2r3_model_invariants.py で既出)の
   再掲であり新規計算ではない。
"""
import hashlib
import json
import sympy as sp

X, Y, w = sp.symbols('X Y w')


def main():
    print("=== [U3-1] Z[1/S]-モデルの構成 ===\n")

    # -----------------------------------------------------------------
    # [1-1] E_Z over Z
    # -----------------------------------------------------------------
    a1, a2, a3, a4, a6 = 3, 0, 2, 0, 0
    b2 = a1 ** 2 + 4 * a2
    b4 = 2 * a4 + a1 * a3
    b6 = a3 ** 2 + 4 * a6
    b8 = a1 ** 2 * a6 + 4 * a2 * a6 - a1 * a3 * a4 + a2 * a3 ** 2 - a4 ** 2
    Delta = -b2 ** 2 * b8 - 8 * b4 ** 3 - 27 * b6 ** 2 + 9 * b2 * b4 * b6
    c4 = b2 ** 2 - 24 * b4
    F_E = sp.expand(Y ** 2 + a1 * X * Y + a3 * Y - (X ** 3 + a2 * X ** 2 + a4 * X + a6))
    print(f"[1-1] E_Z : {F_E} = 0   (a1,a2,a3,a4,a6)=({a1},{a2},{a3},{a4},{a6})")
    print(f"      b2={b2} b4={b4} b6={b6} b8={b8}  Delta={Delta}={sp.factorint(Delta)}  c4={c4}")
    delta_matches_public = (Delta == -216 and sp.factorint(Delta) == {-1: 1, 2: 3, 3: 3})

    # -----------------------------------------------------------------
    # [1-2] W_Z over Z
    # -----------------------------------------------------------------
    F_W = sp.expand(X ** 2 * w ** 3 - 27 * Y * (w + 1))
    W_poly = sp.Poly(F_W, X, Y, w)
    W_monomials = [{"monom": list(m), "coeff": str(c)} for m, c in zip(W_poly.monoms(), W_poly.coeffs())]
    print(f"\n[1-2] W_Z : {F_W} = 0")
    print(f"      monomials (X,Y,w)-exponents: {W_monomials}")

    # -----------------------------------------------------------------
    # [1-3] t over Z[1/2]
    # -----------------------------------------------------------------
    t_expr = -Y ** 2 / 4
    print(f"\n[1-3] t := {t_expr}   over Z[1/2]  (denominator ideal generated by 2)")
    print("      alternate t' := -Y^2 lives over Z but moves the branch point to t'=-4;")
    print("      keeping {0,1,inf} normalization means allowing 1/2 (per spec note).")

    # -----------------------------------------------------------------
    # [1-4] coefficient matrix / Jacobian ideal generators (recorded, NOT solved)
    # -----------------------------------------------------------------
    dW_dX = sp.diff(F_W, X)
    dW_dY = sp.diff(F_W, Y)
    dW_dw = sp.diff(F_W, w)
    dE_dX = sp.diff(F_E, X)
    dE_dY = sp.diff(F_E, Y)
    print("\n[1-4] Jacobian ideal generators (recorded only -- solving the zero locus / discriminant")
    print("      factorization is [U3-2]/[U3-3] (Sol 分担・便123 走行中), out of scope here):")
    print(f"      W    = {F_W}")
    print(f"      dW/dX= {dW_dX}   dW/dY = {dW_dY}   dW/dw = {dW_dw}")
    print(f"      E    = {F_E}")
    print(f"      dE/dX= {dE_dX}   dE/dY = {dE_dY}")
    print(f"      known public lower bound (already established, not new): Delta(E)=-216=-2^3*3^3 ==> S contains {{2,3}} (lower bound only; upper bound is U3-3's job)")

    # -----------------------------------------------------------------
    # cert
    # -----------------------------------------------------------------
    script_path = "search/u3_model_v1.py"
    with open(script_path, "rb") as f:
        script_sha256 = hashlib.sha256(f.read()).hexdigest()

    cert = {
        "schema": "shadow-atelier/u3_model/v1",
        "generated_by": {"tool": f"python3+sympy {sp.__version__}", "script": script_path,
                          "order": "裁定1118(実装係タスク3・工房分[U3-1])"},
        "spec_ref": "docs/notes/r2_r3_unram_execution_spec_v1.md §9 [U3-1]",
        "u3_1_model": {
            "E_Z": {"equation": str(F_E) + " = 0", "a_invariants": [a1, a2, a3, a4, a6],
                     "b2": int(b2), "b4": int(b4), "b6": int(b6), "b8": int(b8),
                     "Delta": int(Delta), "Delta_factored": {str(k): v for k, v in sp.factorint(Delta).items()},
                     "c4": int(c4), "delta_matches_known_public_value_m216": bool(delta_matches_public)},
            "W_Z": {"equation": str(F_W) + " = 0", "monomials_XYw_exponents": W_monomials},
            "t": {"expr": str(t_expr), "denominator_ideal_generator": 2, "ring": "Z[1/2]",
                  "alternate_note": "t' := -Y^2 lives over Z but moves branch point to t'=-4; keeping {0,1,inf} normalization means allowing 1/2"},
        },
        "u3_1_jacobian_ideal_recorded_not_solved": {
            "W": str(F_W), "dW_dX": str(dW_dX), "dW_dY": str(dW_dY), "dW_dw": str(dW_dw),
            "E": str(F_E), "dE_dX": str(dE_dX), "dE_dY": str(dE_dY),
            "note": "生成元の記録のみ。零点集合(特異点の実座標)・判別式の因数分解は[U3-2]/[U3-3](Sol分担・便123走行中)の仕事であり本scriptでは計算しない。",
        },
        "known_public_lower_bound_note": "Delta(E)=-216=-2^3*3^3 は既公開(宣言v4+r2r3_model_invariants.py)⟹ S含む{2,3}の下限は既知(§12末尾の公開値であり新規計算・prereg抵触ではない)。上限(S<=...)の決定はU3-3の仕事。",
        "u_touched": False,
        "c_touched": False,
        "d_no_interpretation": "machine values only; verdict は司令塔",
        "provenance": {"script_sha256": script_sha256},
    }
    out_path = "search/certs/u3_model_v1_20260813.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(cert, f, ensure_ascii=False, indent=2)
    print(f"\nwrote {out_path}")
    print(f"script sha256 = {script_sha256}")


if __name__ == "__main__":
    main()
