#############################################################################
## wall-miner-v1.g -- 壁キャンペーン採掘トラック(裁定156)採掘器 v1
##
## 方針(司令塔指示どおり): 雑でよい・バグ許容・完成度不要。ここで作るのは
## 「候補リードの列挙」だけ。出力は台帳主張にならない(証明書儀式なし)。
## 窓ごとの失敗は skip して log に残すだけで続行する。
##
## 対象A(W-A帯): lins で B3 の正規部分群(指数<=192)を列挙 -> PB3 内の N を
##   抽出し A := PB3/N を作って安価な不変量+2つのプロキシ判定を回す。
## 対象B(W-C帯の先鋒): congruence 窓 N5 = ker(B3 -> S3 x SL(2,F5))。
##   B3 -> SL(2,Z) の標準表現(s1=[[1,1],[0,1]], s2=[[1,0],[-1,1]])を mod2,
##   mod5 に還元して S3 x SL(2,F5) へ CRT で埋め込む。A := PB3/N5 の像
##   (Goursat により SL(2,F5) 全体になるはず -- 数値で確認する)。
##   p=7 は事前探査で IsomorphismPermGroup(SL(2,7)) 経由の構成が 2 分超で
##   終わらなかったため今回は SKIP(司令塔指示 "余力があれば" の範囲内の判断
##   -- 宇宙を広げも縮めもしない。単に今回のリソース内で回さないだけ)。
##
## 出力: search/certs/wall_miner_leads_20260729.json
#############################################################################

Read("search/gaplib_common.g");
Read("search/week3-battery-common.g");

if LoadPackage("lins") <> true then
  Error("Failed to load GAP package LINS.");
fi;

LEADS := [];;
WINDOW_RECORDS := [];;
SKIPLOG := [];;

RecordSkip := function(id, reason)
  Add(SKIPLOG, rec(window_id := id, reason := reason));
  Print("[SKIP] ", id, " :: ", reason, "\n");
end;;

# ================= H_N proxy (Sol A2 style, crude) =================
# power-form maps x -> x^u, y -> f^-1 y^u f for a handful of sampled u
# (odd, up to 9) and f (first few elements of [A,A]); the identity map is
# always included so the generated subgroup is never empty. Returns the
# solvability/nilpotency of the GAP-group generated by the successfully
# constructed bijective self-maps, as a crude Aut(A)-subgroup stand-in.
HNProxy := function(A, ximg, yimg)
  local D, Delems, fsample, autoList, u, f, hom, uCandidates, G2, sizeA, idhom;
  sizeA := Size(A);
  D := DerivedSubgroup(A);
  Delems := Elements(D);
  fsample := Delems{[1 .. Minimum(5, Length(Delems))]};
  uCandidates := Filtered([1 .. Minimum(sizeA, 9)], k -> k mod 2 = 1);
  if Length(uCandidates) = 0 then uCandidates := [1]; fi;
  autoList := [];
  idhom := GroupHomomorphismByImages(A, A, [ximg, yimg], [ximg, yimg]);
  if idhom <> fail then Add(autoList, idhom); fi;
  for u in uCandidates do
    for f in fsample do
      hom := GroupHomomorphismByImages(A, A, [ximg, yimg], [ximg^u, f^-1 * yimg^u * f]);
      if hom <> fail and Size(Image(hom)) = sizeA then
        Add(autoList, hom);
      fi;
    od;
  od;
  G2 := Group(autoList);
  return rec(sampled_u := Length(uCandidates), sampled_f := Length(fsample),
             valid_auto_count := Length(autoList), subgroup_order := Size(G2),
             solvable := IsSolvable(G2), nilpotent := IsNilpotent(G2));
end;;

# ================= JSON serialization for the fixed-shape sub-records =================
HnProxyJson := function(h)
  return Concatenation("{\"sampled_u\":", String(h.sampled_u),
    ",\"sampled_f\":", String(h.sampled_f),
    ",\"valid_auto_count\":", String(h.valid_auto_count),
    ",\"subgroup_order\":", String(h.subgroup_order),
    ",\"solvable\":", JB(h.solvable),
    ",\"nilpotent\":", JB(h.nilpotent), "}");
end;;

KerchiProxyJson := function(k)
  return Concatenation("{\"status\":", JStr(k.status),
    ",\"reason\":", JStr(k.reason),
    ",\"h10_fail\":", String(k.h10_fail),
    ",\"h11_fail\":", String(k.h11_fail),
    ",\"generation_fail\":", String(k.generation_fail),
    ",\"candidate_total\":", String(k.candidate_total),
    ",\"shadow_total\":", String(k.shadow_total), "}");
end;;

WindowJson := function(r)
  return Concatenation("  {\n",
    "    \"window_id\":", JStr(r.window_id), ",\n",
    "    \"band\":", JStr(r.band), ",\n",
    "    \"b3_index\":", String(r.b3_index), ",\n",
    "    \"abs_A\":", String(r.abs_A), ",\n",
    "    \"A_struct\":", JStr(r.A_struct), ",\n",
    "    \"c_in_N\":", JB(r.c_in_N), ",\n",
    "    \"Z_A_order\":", String(r.Z_A_order), ",\n",
    "    \"A_solvable\":", JB(r.A_solvable), ",\n",
    "    \"A_nilpotent\":", JB(r.A_nilpotent), ",\n",
    "    \"xy_generate_A\":", JB(r.xy_generate_A), ",\n",
    "    \"hn_proxy\":", HnProxyJson(r.hn_proxy), ",\n",
    "    \"kerchi_proxy\":", KerchiProxyJson(r.kerchi_proxy), ",\n",
    "    \"leads\":", JArr(List(r.leads, JStr)), ",\n",
    "    \"is_lead\":", JB(r.is_lead), "\n",
    "  }");
end;;

# ================= common per-window processing =================
# A, ximg, yimg, cimg: the quotient group and images of x=a^2,y=b^2,c=(aba)^2.
# windowId/band/b3index: bookkeeping only.
ProcessWindow := function(windowId, band, b3index, A, ximg, yimg, cimg)
  local r, genOK, cInN, zA, solvA, nilpA, hnp, kerchi, iso, Ap, ximgp, yimgp,
        zEltCheck, thetaCheck, tauCheck, hexres;
  r := rec();
  r.window_id := windowId;
  r.band := band;
  r.b3_index := b3index;
  r.abs_A := Size(A);
  r.A_struct := StructureDescription(A);
  cInN := (cimg = Identity(A));
  r.c_in_N := cInN;
  zA := Size(Center(A));
  r.Z_A_order := zA;
  solvA := IsSolvable(A);
  nilpA := IsNilpotent(A);
  r.A_solvable := solvA;
  r.A_nilpotent := nilpA;
  genOK := Size(Group(ximg, yimg)) = Size(A);
  r.xy_generate_A := genOK;
  r.leads := [];

  # ---- lead (c): A non-solvable AND nontrivial center ----
  if (not solvA) and zA > 1 then
    Add(r.leads, "A_nonsolvable_with_center");
  fi;

  # ---- H_N proxy (#2) ----
  if genOK then
    hnp := HNProxy(A, ximg, yimg);
    r.hn_proxy := hnp;
    if (not hnp.solvable) then
      Add(r.leads, "HN_proxy_nonsolvable");
    fi;
  else
    r.hn_proxy := rec(sampled_u := 0, sampled_f := 0, valid_auto_count := 0,
                       subgroup_order := 0, solvable := true, nilpotent := true);
    RecordSkip(windowId, "HN_proxy skipped: <x,y> != A");
  fi;

  # ---- ker chi-tilde proxy (#3), c-in-N windows only, per commander spec ----
  if cInN and genOK then
    iso := IsomorphismPermGroup(A);
    Ap := Image(iso);
    ximgp := Image(iso, ximg);
    yimgp := Image(iso, yimg);
    zEltCheck := (ximgp * yimgp)^-1;
    thetaCheck := GroupHomomorphismByImages(Ap, Ap, [ximgp, yimgp], [yimgp, ximgp]);
    tauCheck := GroupHomomorphismByImages(Ap, Ap, [ximgp, yimgp], [yimgp, zEltCheck]);
    if thetaCheck = fail or tauCheck = fail then
      r.kerchi_proxy := rec(status := "skipped", reason := "theta/tau hom construction failed",
                             h10_fail := 0, h11_fail := 0, generation_fail := 0,
                             candidate_total := 0, shadow_total := 0);
      RecordSkip(windowId, "kerchi_proxy: theta/tau construction failed despite c_in_N");
    else
      hexres := EnumerateReducedHexagon(rec(x := ximgp, y := yimgp, G := Ap), [0]);
      r.kerchi_proxy := rec(status := "computed", reason := "",
                             h10_fail := hexres.h10_fail, h11_fail := hexres.h11_fail,
                             generation_fail := hexres.generation_fail,
                             candidate_total := hexres.candidate_total,
                             shadow_total := hexres.shadow_total);
      if hexres.h10_fail > 0 or hexres.h11_fail > 0 then
        Add(r.leads, "kerchi_proxy_noncommutative");
      fi;
    fi;
  else
    r.kerchi_proxy := rec(status := "skipped", reason := "LEAD-UNSCREENED (c not in N, or x,y do not generate A)",
                           h10_fail := 0, h11_fail := 0, generation_fail := 0,
                           candidate_total := 0, shadow_total := 0);
    RecordSkip(windowId, "kerchi_proxy: LEAD-UNSCREENED (c_in_N=false or gen fail)");
  fi;

  r.is_lead := Length(r.leads) > 0;
  return r;
end;;

#############################################################################
## ---------------------- shared B3 / PB3 setup ----------------------------
#############################################################################
BF3 := FreeGroup("a", "b");;
aa := BF3.1;;  bb := BF3.2;;
brel := aa * bb * aa * (bb * aa * bb)^-1;;
B3 := BF3 / [brel];;
ga := B3.1;;  gb := B3.2;;

S3can := SymmetricGroup(3);;
phiCan := GroupHomomorphismByImages(B3, S3can, [ga, gb], [(1,2), (2,3)]);;
if phiCan = fail then Error("canonical B3 -> S3 map failed sanity check"); fi;
PB3 := Kernel(phiCan);;

x0 := ga^2;;  y0 := gb^2;;  c0 := (ga * gb * ga)^2;;

#############################################################################
## ---------------------- Task A: W-A band (lins, index<=192) --------------
#############################################################################
Print("=== Task A: LINS normal subgroups of B3, index <= 192 ===\n");
t0A := GAPLIB_WallElapsedMs();
grA := LowIndexNormalSubgroupsSearch(B3, 192);;
nodesA := ComputedNormalSubgroups(grA);;
Print("LINS nodes total: ", Length(nodesA), "\n");

serialByIdx := rec();;
countProcessedA := 0;;
countSkippedNotInPB3 := 0;;

for ndA in nodesA do
  NA := Grp(ndA);
  idxA := Index(ndA);
  if idxA = 1 then
    continue;  # N = B3 itself, PB3/N is meaningless(A trivial anyway, not interesting)
  fi;
  if not IsSubset(PB3, NA) then
    countSkippedNotInPB3 := countSkippedNotInPB3 + 1;
    continue;
  fi;
  # serial numbering per repeated index value (structure can repeat at same index)
  if IsBound(serialByIdx.(String(idxA))) then
    serialByIdx.(String(idxA)) := serialByIdx.(String(idxA)) + 1;
  else
    serialByIdx.(String(idxA)) := 1;
  fi;
  windowIdA := Concatenation("W-A-B3idx", String(idxA), "-s", String(serialByIdx.(String(idxA))));

  if not IsNormal(PB3, NA) then
    RecordSkip(windowIdA, "N not normal in PB3 (unexpected -- should be normal in B3)");
    continue;
  fi;

  nhomP := NaturalHomomorphismByNormalSubgroup(PB3, NA);;
  AA := Image(nhomP);;
  ximgA := Image(nhomP, x0);;
  yimgA := Image(nhomP, y0);;
  cimgA := Image(nhomP, c0);;

  # convert to permutation group for speed / to make BFSWords-style code viable
  isoA := IsomorphismPermGroup(AA);;
  AAp := Image(isoA);;
  ximgAp := Image(isoA, ximgA);;
  yimgAp := Image(isoA, yimgA);;
  cimgAp := Image(isoA, cimgA);;

  recA := ProcessWindow(windowIdA, "W-A", idxA, AAp, ximgAp, yimgAp, cimgAp);
  Add(WINDOW_RECORDS, recA);
  countProcessedA := countProcessedA + 1;

  if GAPLIB_CheckCap(500.0, "Task A loop") then
    Print("[CAP WARNING] stopping Task A early at window ", windowIdA, "\n");
    break;
  fi;
od;

t1A := GAPLIB_WallElapsedMs();
Print("Task A done: processed=", countProcessedA, " skipped_not_in_PB3=", countSkippedNotInPB3,
      " elapsed_ms=", t1A - t0A, "\n");

#############################################################################
## ---------------------- Task B: W-C band, N5cong = ker(B3->S3xSL(2,F5)) --
## (NOTE 裁定170, 2026-07-29: window_id below renamed "W-C-N5" -> "W-C-N5cong"
## to avoid collision with week1-定義ノート.md's own, DIFFERENT N5 = ker(beta_5)
## [S3 x C5, order 30] -- this script's N5/N5cong has always been the
## SL(2,F5)-based construction, order 720; only the label changed, not the math.)
#############################################################################
Print("=== Task B: congruence window N5 = ker(B3 -> S3 x SL(2,F5)) ===\n");
t0B := GAPLIB_WallElapsedMs();

M1_2 := [[1,1],[0,1]] * One(GF(2));;
M2_2 := [[1,0],[1,1]] * One(GF(2));;   # -1 mod 2 = 1
M1_5 := [[1,1],[0,1]] * One(GF(5));;
M2_5 := [[1,0],[4,1]] * One(GF(5));;   # -1 mod 5 = 4

Gmat2 := Group(M1_2, M2_2);;
Gmat5 := Group(M1_5, M2_5);;
psi2 := IsomorphismPermGroup(Gmat2);;
psi5 := IsomorphismPermGroup(Gmat5);;
P2perm := Image(psi2);;
P5perm := Image(psi5);;
Print("|SL(2,2)|=", Size(P2perm), " |SL(2,5)|=", Size(P5perm), "\n");

DP5 := DirectProduct(P2perm, P5perm);;
emb1 := Embedding(DP5, 1);;
emb2 := Embedding(DP5, 2);;
xDP5 := Image(emb1, Image(psi2, M1_2)) * Image(emb2, Image(psi5, M1_5));;
yDP5 := Image(emb1, Image(psi2, M2_2)) * Image(emb2, Image(psi5, M2_5));;
Print("braid relation holds in S3 x SL(2,F5)? ", xDP5*yDP5*xDP5 = yDP5*xDP5*yDP5, "\n");
Print("|B3/N5| = ", Size(DP5), "\n");

homB3DP5 := GroupHomomorphismByImages(B3, DP5, [ga, gb], [xDP5, yDP5]);;
if homB3DP5 = fail then
  RecordSkip("W-C-N5cong", "GroupHomomorphismByImages B3->S3xSL(2,F5) failed unexpectedly");
else
  A_N5 := Image(homB3DP5, PB3);;
  ximg_N5 := Image(homB3DP5, x0);;
  yimg_N5 := Image(homB3DP5, y0);;
  cimg_N5 := Image(homB3DP5, c0);;
  Print("|PB3/N5| = ", Size(A_N5), "  StructureDescription = ", StructureDescription(A_N5), "\n");
  recN5 := ProcessWindow("W-C-N5cong", "W-C", Size(DP5), A_N5, ximg_N5, yimg_N5, cimg_N5);
  Add(WINDOW_RECORDS, recN5);
fi;

t1B := GAPLIB_WallElapsedMs();
Print("Task B (N5) done, elapsed_ms=", t1B - t0B, "\n");

# p=7 (SL(2,F7), expected index 2016 / |PB3/N7|=|SL(2,7)|=336): attempted in a
# pre-flight probe and abandoned after IsomorphismPermGroup(SL(2,7)) + the
# GroupHomomorphismByImages check on the resulting ~342-degree direct product
# did not finish within a 2-minute budget. This is the "spare capacity"
# clause in the commander's spec, not a required target -- skipping it here
# and logging the decision rather than silently omitting it.
RecordSkip("W-C-N7", "SKIPPED (not attempted in the committed run): pre-flight probe of SL(2,F7) direct-product construction exceeded a 2-minute budget; p=7 was marked optional (spare-capacity clause) in the spec, so this was not pursued further this pass.");

#############################################################################
## ---------------------- write output --------------------------------------
#############################################################################
leadRecords := Filtered(WINDOW_RECORDS, r -> r.is_lead);;
Print("\n=== SUMMARY ===\n");
Print("Total windows processed: ", Length(WINDOW_RECORDS), "\n");
Print("Leads found: ", Length(leadRecords), "\n");
Print("Skip log entries: ", Length(SKIPLOG), "\n");

outParts := [];;
Add(outParts, "{\n");
Add(outParts, "  \"generated_by\": \"search/wall-miner-v1.g\",\n");
Add(outParts, "  \"note\": \"wall-mining track (rough lead enumeration, NOT a ledger claim, no cross-check performed)\",\n");
Add(outParts, Concatenation("  \"task_a_processed\": ", String(countProcessedA), ",\n"));
Add(outParts, Concatenation("  \"task_a_skipped_not_in_pb3\": ", String(countSkippedNotInPB3), ",\n"));
Add(outParts, Concatenation("  \"total_windows\": ", String(Length(WINDOW_RECORDS)), ",\n"));
Add(outParts, Concatenation("  \"total_leads\": ", String(Length(leadRecords)), ",\n"));
Add(outParts, "  \"windows\": [\n");
for i in [1 .. Length(WINDOW_RECORDS)] do
  Add(outParts, WindowJson(WINDOW_RECORDS[i]));
  if i < Length(WINDOW_RECORDS) then Add(outParts, ",\n"); else Add(outParts, "\n"); fi;
od;
Add(outParts, "  ],\n");
Add(outParts, "  \"skip_log\": [\n");
for i in [1 .. Length(SKIPLOG)] do
  Add(outParts, Concatenation("    {\"window_id\":", JStr(SKIPLOG[i].window_id),
                               ",\"reason\":", JStr(SKIPLOG[i].reason), "}"));
  if i < Length(SKIPLOG) then Add(outParts, ",\n"); else Add(outParts, "\n"); fi;
od;
Add(outParts, "  ]\n");
Add(outParts, "}\n");

WriteFile("search/certs/wall_miner_leads_20260729.json", Concatenation(outParts));
Print("Wrote search/certs/wall_miner_leads_20260729.json\n");
Print("ALL_DONE\n");
