#############################################################################
## falsifier independent adjudication of the PB_4 gate (ruling 367)
## NO probe helper is used: no FreeGroup, no Rev(), no BuildQ, no cof[].
## Everything is rebuilt from 2008.00066 (A.2)(A.4)(A.5)(A.18) verbatim.
##
## Key simplification (proved in the report): for an anti-homomorphism Psi
## the image Psi(F) equals the subgroup generated by the generator images,
## so Q_P = < Psi(x12), Psi(x23), Psi(c) > as a 5-tuple subgroup of E^5.
## We therefore never need the free group / Rev machinery at all.
#############################################################################

## ---- shared setup (target group E and the B_3 representation) ----
n := 5;; tt := (1,2,3);; aa := (1,4,5);;
XX := aa*tt^-1;; ss := tt*XX^3;; b1 := tt;; a1 := ss;;
aE := a1*(n+1,n+3);; bE := b1*(n+1,n+3,n+2);;
s1 := bE^-1*aE;; s2 := aE*bE^2;;
Eg := Group(aE,bE);;
cc := (s1*s2)^3;;

Print("### 0. setup sanity ###\n");
Print("  |E| = ",Size(Eg),"   ord(s1)=",Order(s1),"  ord(s2)=",Order(s2),"\n");
Print("  braid  s1 s2 s1 = s2 s1 s2 ? ",s1*s2*s1 = s2*s1*s2,"\n");
Print("  (s1 s2)^3 = (s2 s1)^3 ? ",(s1*s2)^3 = (s2*s1)^3,
      "   ord(c) = ",Order(cc),"   c=1 ? ",cc=One(Eg),"\n");
Print("  |<s1^2,s2^2>| = ",Size(Group(s1^2,s2^2)),"\n");

## ---- 1. uniqueness of the B_4 extension (independent brute force) ----
Print("\n### 1. B_4 extensions sigma_3 |-> t ###\n");
ext := Filtered(AsList(Eg), z -> s2*z*s2 = z*s2*z and s1*z = z*s1);;
Print("  #{t : braid(s2,t) and [s1,t]=1} = ",Length(ext),
      "   t = ",List(ext,String),"\n");
if Length(ext)=1 then
  Print("  t = s1 ? ",ext[1]=s1,"    ord(t)=",Order(ext[1]),"\n");
fi;
t := ext[1];;

## ---- 2. canonical x_ij words (A.2)/(A.4), both orientations ----
##  forward  pi  : sigma_j -> s_j   (homomorphism)
##  reversed rho : sigma_j -> s_j   (ANTI-homomorphism, rho(w)=pi(Rev w))
sig := [s1,s2,t];;
## pi(x_ij) with x_ij = s_{j-1}...s_{i+1} s_i^2 s_{i+1}^-1 ... s_{j-1}^-1
PiX := function(i,j)
  local w,k;
  w := sig[i]^2;
  for k in [i+1..j-1] do w := sig[k]*w*sig[k]^-1; od;
  return w;
end;;
## rho(x_ij) : reverse the letter sequence of the same word
RhoX := function(i,j)
  local w,k;
  w := sig[i]^2;
  for k in [i+1..j-1] do w := sig[k]^-1*w*sig[k]; od;
  return w;
end;;

Print("\n### 2. canonical generator images in E ###\n");
Print("  pi : x12=",String(PiX(1,2))," x23=",String(PiX(2,3)),
      " x13=",String(PiX(1,3)),"\n");
Print("       x34=",String(PiX(3,4))," x24=",String(PiX(2,4)),
      " x14=",String(PiX(1,4)),"\n");
Print("  rho: x12=",String(RhoX(1,2))," x23=",String(RhoX(2,3)),
      " x13=",String(RhoX(1,3)),"\n");
Print("       x34=",String(RhoX(3,4))," x24=",String(RhoX(2,4)),
      " x14=",String(RhoX(1,4)),"\n");

## probe's window (from pent_settled_struct / gtpi)
xb := s1^2;; yb := s2^2;;
PX12 := xb;; PX23 := yb;; PX13 := yb^-1*xb^-1;;
PX34 := xb;; PX24 := s1^-1*yb*s1;; PX14 := s1^-1*PX13*s1;;
Print("\n  probe: x12=",String(PX12)," x23=",String(PX23),
      " x13=",String(PX13),"\n");
Print("         x34=",String(PX34)," x24=",String(PX24),
      " x14=",String(PX14),"\n");

Print("\n### 3. probe vs rho (the Rev hypothesis), generator by generator ###\n");
Print("  x12 : probe=rho ? ",PX12=RhoX(1,2),"   probe=pi ? ",PX12=PiX(1,2),"\n");
Print("  x23 : probe=rho ? ",PX23=RhoX(2,3),"   probe=pi ? ",PX23=PiX(2,3),"\n");
Print("  x34 : probe=rho ? ",PX34=RhoX(3,4),"   probe=pi ? ",PX34=PiX(3,4),"\n");
Print("  x24 : probe=rho ? ",PX24=RhoX(2,4),"   probe=pi ? ",PX24=PiX(2,4),"\n");
Print("  x13 : probe=rho ? ",PX13=RhoX(1,3),"   probe=pi ? ",PX13=PiX(1,3),"\n");
Print("  x14 : probe=rho ? ",PX14=RhoX(1,4),"   probe=pi ? ",PX14=PiX(1,4),"\n");

## the c-kill test: rho(x13) = rho(x23)^-1 rho(c) rho(x12)^-1 ; probe drops rho(c)
Print("\n  rho(c) = (s2 s1)^3 = ",String((s2*s1)^3),"  ord=",Order((s2*s1)^3),"\n");
Print("  rho(x13) =?= yb^-1 * rho(c) * xb^-1 : ",
      RhoX(1,3) = yb^-1*(s2*s1)^3*xb^-1,"\n");
Print("  probe x13 =?= yb^-1 * 1 * xb^-1     : ",
      PX13 = yb^-1*One(Eg)*xb^-1,"\n");
Print("  probe x13 = rho(x13) * rho(c)^-1 ?   ",
      PX13 = RhoX(1,3)*((s2*s1)^3)^-1, "   (c central in E-image? ",
      (s2*s1)^3*RhoX(1,3) = RhoX(1,3)*(s2*s1)^3,")\n");
Print("  pi(x13)  =?= xb^-1 * pi(c) * yb^-1  : ",
      PiX(1,3) = xb^-1*(s1*s2)^3*yb^-1,"\n");

## ---- 4. the five-fold construction, rebuilt from (A.18) ----
##  phi_123    : x12->x12,      x23->x23,     x13->x13
##  phi_234    : x12->x23,      x23->x34,     x13->x24
##  phi_12,3,4 : x12->x13 x23,  x23->x34,     x13->x14 x24
##  phi_1,23,4 : x12->x12 x13,  x23->x24 x34, x13->x14
##  phi_1,2,34 : x12->x12,      x23->x23 x24, x13->x13 x14
##  ord = "fwd": images of products are taken in the canonical order
##  ord = "rev": images of products are reversed (anti-hom convention)
D5 := DirectProduct(Eg,Eg,Eg,Eg,Eg);;
emb := List([1..5], i -> Embedding(D5,i));;
Pk := function(l) return Product(List([1..5],i->Image(emb[i],l[i]))); end;;

## G = record with fields x12,x23,x13,x14,x24,x34  (elements of E)
Build := function(G, ord, killc)
  local mul, tri, P,Q,R,C, i, PXt,PYt,PCt, QP, QF, wd, zc;
  if ord = "rev" then mul := function(u,v) return v*u; end;
                 else mul := function(u,v) return u*v; end; fi;
  ## triples ( Psi_i(x12), Psi_i(x23), Psi_i(x13) )
  tri := [ [ G.x12, G.x23, G.x13 ],
           [ G.x23, G.x34, G.x24 ],
           [ mul(G.x13,G.x23), G.x34, mul(G.x14,G.x24) ],
           [ mul(G.x12,G.x13), mul(G.x24,G.x34), G.x14 ],
           [ G.x12, mul(G.x23,G.x24), mul(G.x13,G.x14) ] ];
  ## Psi_i(c) from (A.5): c = x12 x13 x23
  C := List([1..5], i -> mul(mul(tri[i][1],tri[i][3]),tri[i][2]));
  if killc then C := List([1..5], i -> One(Eg)); fi;
  PXt := Pk(List([1..5],i->tri[i][1]));
  PYt := Pk(List([1..5],i->tri[i][2]));
  PCt := Pk(C);
  QP := Group(PXt,PYt,PCt);
  QF := Group(PXt,PYt);
  ## well-definedness of Psi as a map out of PB3 = F2 x <c> :
  ##   Psi_i(c) must commute with Psi_i(x12) and Psi_i(x23) for each i
  wd := ForAll([1..5], i -> C[i]*tri[i][1]=tri[i][1]*C[i] and
                            C[i]*tri[i][2]=tri[i][2]*C[i]);
  ## also check the second canonical expression c = x23 x12 x13 agrees
  zc := ForAll([1..5], i ->
        mul(mul(tri[i][2],tri[i][1]),tri[i][3]) = C[i]);
  return rec(sz:=Size(QP), der:=Size(DerivedSubgroup(QP)),
             ders:=StructureDescription(DerivedSubgroup(QP)),
             z:=Size(Centre(QP)), f2:=Size(QF),
             cord:=List(C,Order), wd:=wd, zc:=zc,
             sd:=StructureDescription(QP));
end;;

Show := function(name,r)
  Print("  ",name,"\n");
  Print("      |Q_P| = ",r.sz,"   |[Q,Q]| = ",r.der," (",r.ders,")",
        "   |Z(Q)| = ",r.z,"\n");
  Print("      |<Psi(x),Psi(y)>| (F2 part) = ",r.f2,
        "   ord(Psi_i(c)) = ",r.cord,"\n");
  Print("      Psi well-defined on PB3 (c central in each cpt) ? ",r.wd,
        "   two c-words agree ? ",r.zc,"\n");
  Print("      StructureDescription(Q_P) = ",r.sd,"\n");
end;;

Gprobe := rec(x12:=PX12,x23:=PX23,x13:=PX13,x14:=PX14,x24:=PX24,x34:=PX34);;
Grho   := rec(x12:=RhoX(1,2),x23:=RhoX(2,3),x13:=RhoX(1,3),
              x14:=RhoX(1,4),x24:=RhoX(2,4),x34:=RhoX(3,4));;
Gpi    := rec(x12:=PiX(1,2),x23:=PiX(2,3),x13:=PiX(1,3),
              x14:=PiX(1,4),x24:=PiX(2,4),x34:=PiX(3,4));;
## canonical generators with c KILLED inside the x13 formula only
## (rho version: x13 := rho(x23)^-1 rho(x12)^-1 ; x14 := t^-1 x13 t)
Grhoc1 := rec(x12:=RhoX(1,2),x23:=RhoX(2,3),
              x13:=RhoX(2,3)^-1*RhoX(1,2)^-1,
              x14:=t^-1*(RhoX(2,3)^-1*RhoX(1,2)^-1)*t,
              x24:=RhoX(2,4),x34:=RhoX(3,4));;
## (pi version: x13 := pi(x12)^-1 pi(x23)^-1 ; x14 := t x13 t^-1)
Gpic1  := rec(x12:=PiX(1,2),x23:=PiX(2,3),
              x13:=PiX(1,2)^-1*PiX(2,3)^-1,
              x14:=t*(PiX(1,2)^-1*PiX(2,3)^-1)*t^-1,
              x24:=PiX(2,4),x34:=PiX(3,4));;

Print("\n### 4. the five-fold construction ###\n");
Print("\n-- (a) probe window, rev row order (= the probe's own convention) --\n");
Show("probe / rev", Build(Gprobe,"rev",false));
Print("\n-- (b) canonical rho window (pure Rev convention, c KEPT) --\n");
Show("rho / rev  ", Build(Grho,"rev",false));
Print("\n-- (c) canonical pi window, fwd row order (the honest canon) --\n");
Show("pi / fwd   ", Build(Gpi,"fwd",false));
Print("\n-- (d) canonical pi window, REV row order (what the gate script did) --\n");
Show("pi / rev   ", Build(Gpi,"rev",false));
Print("\n-- (e) rho window + c killed in x13 only (= probe's x13 rule) --\n");
Show("rho-c1/rev ", Build(Grhoc1,"rev",false));
Print("\n-- (f) pi window + c killed in x13 only --\n");
Show("pi-c1 /fwd ", Build(Gpic1,"fwd",false));
Print("\n-- (g) canonical rho window, Psi(c) forced to 1 in ALL 5 cpts --\n");
Show("rho/rev c=1", Build(Grho,"rev",true));
Print("\n-- (h) canonical pi window, Psi(c) forced to 1 in ALL 5 cpts --\n");
Show("pi/fwd  c=1", Build(Gpi,"fwd",true));

## ---- 5. what does the probe's window generate inside PB4-image? ----
Print("\n### 5. subgroup generated by the six window elements ###\n");
Print("  |<probe X_ij>| = ",
  Size(Group([PX12,PX13,PX14,PX23,PX24,PX34])),"\n");
Print("  |<rho  x_ij>|  = ",
  Size(Group([RhoX(1,2),RhoX(1,3),RhoX(1,4),RhoX(2,3),RhoX(2,4),RhoX(3,4)])),"\n");
Print("  |<pi   x_ij>|  = ",
  Size(Group([PiX(1,2),PiX(1,3),PiX(1,4),PiX(2,3),PiX(2,4),PiX(3,4)])),"\n");
Print("  |<s1^2,s2^2>| (P_N) = ",Size(Group(xb,yb)),"\n");

Print("\n== DONE ==\n");
QUIT;
