"""Tower check: W_n -> V(=P^1_m) -> P^1_lambda for the K^(n) window H_{2,1,0}."""
from kn_window import window, Q, mul, inv
from itertools import product

def ctype(p):
    seen=set(); t=[]
    for i in range(len(p)):
        if i in seen: continue
        l=0;x=i
        while x not in seen: seen.add(x); x=p[x]; l+=1
        t.append(l)
    return tuple(sorted(t,reverse=True))

for n in (3,7,9):
    w=window(n,1); pX,pY,pZ=w['perms']; d=2*n
    # block system from the index-2 subgroup A.<q2>: parity hom  G -> Q/<q2> = C2
    # on cosets: block = image under (X->1, Y->0, Z->1) word length parity.
    # find it combinatorially: orbits of <pY, pX^2, ...> ; simplest: blocks of the
    # normal subgroup generated by Y and X^2 in the monodromy group.
    # do it by orbit of point 0 under <pY, pX*pX>
    def comp(p,q): return tuple(p[q[i]] for i in range(len(q)))
    gens=[pY, comp(pX,pX)]
    orb={0}; fr=[0]
    while fr:
        nf=[]
        for x in fr:
            for g in gens:
                if g[x] not in orb: orb.add(g[x]); nf.append(g[x])
        fr=nf
    B0=sorted(orb); B1=sorted(set(range(d))-orb)
    assert len(B0)==n and len(B1)==n, (len(B0),len(B1))
    # X swaps the blocks (since X has a single 2n-cycle)
    assert set(pX[i] for i in B0)==set(B1)
    # restrict to B0: monodromy of W -> V.  Local monodromies over m=0,inf,1,-1:
    #  m=0  : X^2 on B0 ;  m=inf : Z^2 on B0 ; m=+-1 : Y on B0 and on B1
    idx={v:i for i,v in enumerate(B0)}
    idx1={v:i for i,v in enumerate(B1)}
    X2=comp(pX,pX); Z2=comp(pZ,pZ)
    rX2=tuple(idx[X2[v]] for v in B0)
    rZ2=tuple(idx[Z2[v]] for v in B0)
    rY0=tuple(idx[pY[v]] for v in B0)
    rY1=tuple(idx1[pY[v]] for v in B1)
    # monodromy group of degree-n cover
    grp={tuple(range(n))}; fr=list(grp)
    while fr:
        nf=[]
        for p in fr:
            for g in (rX2,rY0):
                r=comp(g,p)
                if r not in grp: grp.add(r); nf.append(r)
        fr=nf
    rh=-2*n+ (n-len(ctype(rX2))) + (n-len(ctype(rZ2))) + (n-len(ctype(rY0))) + (n-len(ctype(rY1)))
    print(f"n={n}: W->V deg {n}; types over m=0,inf,1,-1 = "
          f"{ctype(rX2)},{ctype(rZ2)},{ctype(rY0)},{ctype(rY1)}  |mon(W/V)|={len(grp)} (2n={2*n})"
          f"  RH: 2g-2={rh} -> g={(rh+2)//2}")
