"""K^(n) window (H_{2,alpha,0}) covering data. Pure integer arithmetic.
G_n = A rtimes Q,  A=(Z/n)^3, Q=C_2^2 = even-parity sign vectors.
q_j: e_i -> +e_i iff i=j else -e_i.
X = a_1 q_1, Y = a_1a_2a_3 q_2, Z=(XY)^{-1}.
H_{j,alpha,beta} = U_{j,alpha} rtimes <(beta e_1) q_j>,  U_{2,alpha}=<e_2, alpha e_1+e_3>.
"""
from itertools import product

Q = [(1,1,1),(1,-1,-1),(-1,1,-1),(-1,-1,1)]  # 1, q1, q2, q3
QI = {q:i for i,q in enumerate(Q)}

def mul(g,h,n):
    a,e = g; b,f = h
    return (tuple((a[i]+e[i]*b[i])%n for i in range(3)), tuple(e[i]*f[i] for i in range(3)))
def inv(g,n):
    a,e = g
    return (tuple((-e[i]*a[i])%n for i in range(3)), e)

def window(n, alpha, beta=0, j=2):
    jp = 5-j
    e1=(1,0,0); e2=(0,1,0); e3=(0,0,1)
    X = ((1,0,0), Q[1]); Y = ((1,1,1), Q[2])
    XY = mul(X,Y,n); Z = inv(XY,n)
    # U_{j,alpha} = < e_j , alpha e_1 + e_{j'} >
    gj = [0,0,0]; gj[j-1]=1
    gk = [0,0,0]; gk[0]=alpha%n; gk[jp-1]=1
    U = set()
    for s,t in product(range(n),repeat=2):
        U.add(tuple((s*gj[i]+t*gk[i])%n for i in range(3)))
    hj = ((beta%n,0,0), Q[j])
    H = set()
    for u in U:
        H.add((u,(1,1,1)))
        H.add(mul((u,(1,1,1)),hj,n))
    assert len(H)==2*n*n, len(H)
    # cosets gH
    Gall=[ (a,e) for a in product(range(n),repeat=3) for e in Q ]
    cos=[]; which={}
    for g in Gall:
        if g in which: continue
        c=frozenset(mul(g,h,n) for h in H)
        idx=len(cos); cos.append(c)
        for x in c: which[x]=idx
    assert len(cos)==2*n, len(cos)
    def perm(g):
        return tuple(which[mul(g,next(iter(cos[i])),n)] for i in range(2*n))
    def ctype(p):
        seen=set(); t=[]
        for i in range(len(p)):
            if i in seen: continue
            l=0; x=i
            while x not in seen:
                seen.add(x); x=p[x]; l+=1
            t.append(l)
        return tuple(sorted(t,reverse=True))
    pX,pY,pZ = perm(X),perm(Y),perm(Z)
    # monodromy group generated by pX,pY
    def comp(p,q): return tuple(p[q[i]] for i in range(len(q)))
    idp=tuple(range(2*n)); grp={idp}; frontier=[idp]
    while frontier:
        nf=[]
        for p in frontier:
            for g in (pX,pY):
                r=comp(g,p)
                if r not in grp: grp.add(r); nf.append(r)
        frontier=nf
    d=2*n
    ram=sum(d-len(set_cycles(p)) for p in (pX,pY,pZ)) if False else None
    def ncyc(p): return len(ctype(p))
    rh = -2*d + sum(d-ncyc(p) for p in (pX,pY,pZ))
    return dict(n=n,alpha=alpha,deg=d,types=(ctype(pX),ctype(pY),ctype(pZ)),
                mon_order=len(grp), genus=(rh+2)//2, rh2g2=rh,
                perms=(pX,pY,pZ))

for n in (3,5,7,9):
    for alpha in range(1,(n+1)//2+ (0 if n%2 else 0)):
        if alpha> (n-1)//2: break
        w=window(n,alpha)
        print(f"n={n} alpha={alpha}: deg={w['deg']} types={w['types']} |mon|={w['mon_order']} "
              f"g={w['genus']} (4n^2={4*n*n})")
