#!/usr/bin/env python
# crosscheck/check_pdisc1.py
# Independent checker for search/certs/pdisc1_v1_20260812.json (P-DISC-1, 裁定823/827).
#
# CROSSCHECK, NOT VERIFICATION. Does NOT call GAP, does NOT import search/pdisc1_v1.g.
#
# G=C11:C10 (order 110) is small enough that this checker independently reconstructs it in
# pure Python (as permutations of {0..10}) and brute-force checks ALL 110^2=12100 pairs (a,b)
# for the braid relation a*b*a=b*a*b AND full generation -- a DIRECT, full re-derivation of
# GQuotients(B3,G)'s emptiness (an epimorphism B3->>G exists iff SOME braid-relation-satisfying
# generating pair exists in G), not merely a downstream/provenance check. This is possible here
# specifically because of G's small size (same situation as
# crosscheck/check_w691_scan_canary.py).
import json


def perm_apply(p, x):
    return p[x]


def perm_compose(p, q):
    # (p*q)(x) = p(q(x)) -- apply q first, then p (standard function composition convention;
    # since we only need CONSISTENT composition for checking a*b*a=b*a*b, either convention
    # works as long as used uniformly)
    return tuple(p[q[i]] for i in range(len(q)))


def perm_identity(n):
    return tuple(range(n))


N = 11


def build_translation():
    return tuple((x + 1) % N for x in range(N))


def build_multiplication(g):
    return tuple((x * g) % N for x in range(N))


def perm_order(p):
    ident = perm_identity(N)
    cur = p
    order = 1
    while cur != ident:
        cur = perm_compose(cur, p)
        order += 1
        if order > 50:
            raise ValueError("order search exceeded bound")
    return order


def is_primitive_root(g, p):
    order = p - 1
    if pow(g, order, p) != 1:
        return False
    n = order
    q = 2
    factors = set()
    while q * q <= n:
        while n % q == 0:
            factors.add(q)
            n //= q
        q += 1
    if n > 1:
        factors.add(n)
    for q in factors:
        if pow(g, order // q, p) == 1:
            return False
    return True


def generate_group(gens):
    ident = perm_identity(N)
    closure = {ident}
    for g in gens:
        closure.add(g)
    changed = True
    while changed:
        changed = False
        new_elts = set()
        for x in closure:
            for g in gens:
                y = perm_compose(x, g)
                if y not in closure:
                    new_elts.add(y)
        if new_elts:
            closure |= new_elts
            changed = True
    return closure


CERT_PATH = "search/certs/pdisc1_v1_20260812.json"

fails = []
def fail(msg):
    fails.append(msg); print("[FAIL]", msg)
def ok(msg):
    print("[PASS]", msg)


def main():
    cert = json.load(open(CERT_PATH, encoding="utf-8"))

    if cert.get("schema") != "shadow-atelier/pdisc1_v1":
        fail("schema mismatch")
    else:
        ok("schema = shadow-atelier/pdisc1_v1")

    if cert.get("chi_semantics") != "section":
        fail(f"chi_semantics = {cert.get('chi_semantics')}, want 'section'")
    else:
        ok("chi_semantics = 'section'")

    g_root = 2
    if not is_primitive_root(g_root, N):
        fail(f"g={g_root} is not a primitive root mod {N} -- cert's choice invalid")
    else:
        ok(f"g={g_root} independently verified to be a primitive root mod {N}")

    trans = build_translation()
    mult = build_multiplication(g_root)
    trans_ord = perm_order(trans)
    mult_ord = perm_order(mult)

    if trans_ord != cert.get("translation_order"):
        fail(f"translation_order rederived={trans_ord} cert={cert.get('translation_order')}")
    else:
        ok(f"translation_order = {trans_ord}")
    if mult_ord != cert.get("multiplication_order"):
        fail(f"multiplication_order rederived={mult_ord} cert={cert.get('multiplication_order')}")
    else:
        ok(f"multiplication_order = {mult_ord}")

    G = generate_group([trans, mult])
    g_order = len(G)
    if g_order != cert.get("g_order"):
        fail(f"g_order rederived={g_order} cert={cert.get('g_order')}")
    else:
        ok(f"g_order = {g_order} rederived independently (pure Python group closure)")
    if g_order != 110:
        fail(f"g_order = {g_order}, want 110 (AGL(1,11))")

    # C11 normal in G: check g * trans^k * g^-1 in C11 for all g in G (equivalently, since C11
    # is generated by trans, check conjugates of trans stay within <trans>)
    C11 = generate_group([trans])
    # need inverse of each element for conjugation check; compute via brute force (small group)
    def inv(p):
        for q in G:
            if perm_compose(p, q) == perm_identity(N):
                return q
        raise ValueError("inverse not found")

    c11_normal = True
    for g in G:
        gi = inv(g)
        for c in C11:
            conj = perm_compose(perm_compose(g, c), gi)
            if conj not in C11:
                c11_normal = False
                break
        if not c11_normal:
            break
    if c11_normal != cert.get("c11_normal_in_g"):
        fail(f"c11_normal_in_g rederived={c11_normal} cert={cert.get('c11_normal_in_g')}")
    else:
        ok(f"c11_normal_in_g = {c11_normal} (independently re-derived via conjugation check)")

    # ---- direct GQuotients(B3,G) re-derivation: brute-force ALL 110^2 pairs ----
    G_list = list(G)
    found_gen_pair = False
    braid_pair_count = 0
    for a in G_list:
        for b in G_list:
            aba = perm_compose(perm_compose(a, b), a)
            bab = perm_compose(perm_compose(b, a), b)
            if aba == bab:
                braid_pair_count += 1
                if not found_gen_pair:
                    if len(generate_group([a, b])) == g_order:
                        found_gen_pair = True

    gquotients_empty_rederived = not found_gen_pair
    if gquotients_empty_rederived != cert.get("gquotients_empty"):
        fail(f"gquotients_empty rederived={gquotients_empty_rederived} "
             f"cert={cert.get('gquotients_empty')} (braid_pair_count={braid_pair_count}, "
             f"found_gen_pair={found_gen_pair})")
    else:
        ok(f"gquotients_empty = {gquotients_empty_rederived} -- DIRECTLY re-derived via brute-"
           f"force search over ALL {g_order}^2={g_order*g_order} pairs (not a downstream check: "
           f"this independently confirms/refutes GQuotients(B3,G)'s emptiness from first "
           f"principles, braid_pair_count={braid_pair_count})")

    print()
    if fails:
        print(f"RESULT: FAIL ({len(fails)} mismatches)")
        return 1
    else:
        print("RESULT: PASS (cross-checked, not verified -- 検証は Lean 専有; NOTE: this is a "
              "FULL independent re-derivation of the core claim, not limited to "
              "provenance/downstream logic, thanks to G's small size)")
        return 0

if __name__ == "__main__":
    import sys
    sys.exit(main())
