#!/usr/bin/env node
// crosscheck/check.mjs -- WP2b 独立照合器 (node 標準ライブラリのみ, 依存ゼロ)
//
// 独立性の規律 (CLAUDE.md / wp2-workorders.md):
//   - search/ の .g ファイルは一切読んでいない・移植していない。
//   - 本ファイルの数学的根拠は次の文書のみ:
//       docs/wp2-transversal-model.md (12 規則 + 証明書スキーマ + 検査項目 1-10)
//       docs/wp2-workorders.md
//       docs/week1-定義ノート.md (hexagon (3.3)(3.4), charming, 合成 (3.53), 逆射 (3.54), Thm 4.3/4.6)
//       docs/notes/2405.11725-抽出ノート_v1.md (Thm 4.3/4.6 の式, (4.19)(4.20), LS witness item (G))
//       sol/sol_reply_01_definition_gate.md 6 節 (罠12件)
//   - D_n の元・積・作用は自分で導出し、起動時自己検査で braid / sigma^2 / c-check / 群位数較正 を通す。
//
// 未解決の仕様ギャップ (実装者からの申し送り. 司令塔へ確認要):
//   (A) 検査項目 6 「kernel_cert の (4.11) 等式」: 入手した文書には (h1,h2,h3) の構成式は
//       あるが、(4.11) の literal な等式そのものは転記されていない。本実装は
//       「(h1,h2,h3) による共役が T^{PB3} の x,y 像を psi_n の x,y 像に写す」という
//       marked-factor-map の自然な解釈を PROVISIONAL に実装した (verdict に
//       provisional_interpretation:true を明記)。確定式が届き次第、差し替えが必要。
//   (B) 検査項目 10 「ls_witness の (5.1) 両式」: 抽出ノートには witness g,h の明示式
//       (item G) はあるが、(5.1) 自体 (LS 条件が何を要求する式か) の literal な式は
//       転記されていない。本実装は「g,h が f の被覆条件を満たす」という一般的な
//       Lochak-Schneps covering condition の教科書的定式化を PROVISIONAL に実装した。
//       これも確定式が届くまで provisional 扱い。
//
'use strict';

import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CERT_DIR = join(ROOT, 'certificates');
const VERDICT_DIR = join(ROOT, 'crosscheck', 'verdicts');

// ---------- 基礎ユーティリティ ----------

function mod(a, n) { return ((a % n) + n) % n; }
function gcd(a, b) { a = Math.abs(a); b = Math.abs(b); while (b) { [a, b] = [b, a % b]; } return a; }
function lcm(a, b) { return Math.abs(a * b) / gcd(a, b); }

// ---------- 群インターフェース ----------
// 各 Group は { id, elements(), mul(a,b), inv(a), eq(a,b), key(a), pow(a,k) } を持つ。

function makeDn(n) {
  // D_n = <r,s | r^n, s^2, s r s^-1 = r^-1>, 元 = [a,e] = r^a s^e
  // 積: (a,e)(b,f) = (a + (-1)^e b mod n, e+f mod 2)  -- 自前導出 (仕様 conventions と一致)
  const id = { a: 0, e: 0 };
  const mul = (g, h) => ({ a: mod(g.a + (g.e === 0 ? 1 : -1) * h.a, n), e: (g.e + h.e) % 2 });
  const inv = (g) => (g.e === 0 ? { a: mod(-g.a, n), e: 0 } : { a: mod(g.a, n), e: 1 });
  const key = (g) => `${mod(g.a, n)},${g.e}`;
  const eq = (g, h) => key(g) === key(h);
  const elements = () => { const out = []; for (let a = 0; a < n; a++) for (let e = 0; e < 2; e++) out.push({ a, e }); return out; };
  const pow = (g, k) => {
    if (k === 0) return id;
    const base = k < 0 ? inv(g) : g;
    let res = id;
    for (let i = 0; i < Math.abs(k); i++) res = mul(res, base);
    return res;
  };
  return { n, id, mul, inv, key, eq, elements, pow };
}

function makeCyclic(m) {
  const id = 0;
  const mul = (a, b) => mod(a + b, m);
  const inv = (a) => mod(-a, m);
  const key = (a) => `${mod(a, m)}`;
  const eq = (a, b) => key(a) === key(b);
  const elements = () => { const out = []; for (let a = 0; a < m; a++) out.push(a); return out; };
  const pow = (a, k) => mod(a * k, m);
  return { m, id, mul, inv, key, eq, elements, pow };
}

// 直積 (成分ごとに同じ or 違う Group の配列)
function makeProduct(groups) {
  const id = groups.map((g) => g.id);
  const mul = (xs, ys) => xs.map((x, i) => groups[i].mul(x, ys[i]));
  const inv = (xs) => xs.map((x, i) => groups[i].inv(x));
  const key = (xs) => xs.map((x, i) => groups[i].key(x)).join('|');
  const eq = (xs, ys) => key(xs) === key(ys);
  const pow = (xs, k) => xs.map((x, i) => groups[i].pow(x, k));
  return { id, mul, inv, key, eq, pow };
}

// ---------- 語の評価 ----------
// token = [gen, power]  (gen: 文字, power: 整数)
// phi: { [gen]: G-element }
function evalWord(G, phi, tokens) {
  let res = G.id;
  for (const [gen, p] of tokens) {
    const g = phi[gen];
    res = G.mul(res, G.pow(g, p));
  }
  return res;
}

// ---------- 部分群の生成 (BFS closure) ----------
function subgroupClosure(G, gens) {
  const genList = [];
  for (const g of gens) { genList.push(g); genList.push(G.inv(g)); }
  const seen = new Map();
  seen.set(G.key(G.id), G.id);
  const frontier = [G.id];
  while (frontier.length) {
    const elem = frontier.pop();
    for (const g of genList) {
      const cand = G.mul(elem, g);
      const k = G.key(cand);
      if (!seen.has(k)) { seen.set(k, cand); frontier.push(cand); }
    }
  }
  return seen; // Map key -> element
}

function commutator(G, g, h) {
  return G.mul(G.mul(G.inv(g), G.inv(h)), G.mul(g, h));
}

// derived subgroup of the subgroup generated by (X,Y): 正規閉包 of [X,Y] を BFS で計算
function derivedSubgroupOfTwoGen(G, GnMap, X, Y) {
  const c0 = commutator(G, X, Y);
  const conjugates = [];
  for (const g of GnMap.values()) {
    conjugates.push(G.mul(G.mul(g, c0), G.inv(g)));
  }
  return subgroupClosure(G, conjugates);
}

// ---------- dihedral Gn (= Im(psi_n) <= Dn^3) ----------
function buildGn(n) {
  const Dn = makeDn(n);
  const r = { a: 1, e: 0 };
  const s = { a: 0, e: 1 };
  const rs = Dn.mul(r, s);
  const Triple = makeProduct([Dn, Dn, Dn]);
  const phiTriple = { x: [r, s, s], y: [rs, r, rs], c: [Dn.id, Dn.id, Dn.id] };
  const X = phiTriple.x, Y = phiTriple.y;
  const GnMap = subgroupClosure(Triple, [X, Y]);
  const derived = derivedSubgroupOfTwoGen(Triple, GnMap, X, Y);
  return { Dn, Triple, phiTriple, GnMap, derived, X, Y };
}

function expectedGnOrder(n) {
  return (n % 2 === 1) ? 4 * n ** 3 : 4 * (n / 2) ** 3;
}

// ---------- Thm 4.3 の閉じた式 ----------
function kappa(m) { return (m % 2 === 1) ? m + 1 : -m; }

function xn(Nord) {
  const out = [];
  for (let m = 0; m < Nord; m++) if (gcd(2 * m + 1, Nord) === 1) out.push(m);
  return out;
}

function thm43ShadowSet(n) {
  const Nord = lcm(n, 2);
  const n1 = n / gcd(n, 2); // ord(r^2)
  const Xn = xn(Nord);
  const fourDividesN = (n % 4 === 0);
  const result = [];
  for (const m of Xn) {
    const kap = kappa(m);
    for (let k = 0; k < n1; k++) {
      if (fourDividesN) {
        if (kap % 2 !== 0) continue; // 想定外 (guard)
        const need = mod(kap / 2, 2);
        if (mod(k, 2) !== need) continue;
      }
      const triple = [[mod(2 * k, n), 0], [mod(-2 * k, n), 0], [mod(kap, n), 0]];
      result.push({ m, triple });
    }
  }
  return { Nord, n1, Xn, shadows: result };
}

function tripleKey(triple) {
  return triple.map(([a, e]) => `${a},${e}`).join('|');
}

// ---------- Q x T transversal モデル (12 規則) ----------
// t0..t5 = t1..t6 = e, s1, s2, s1s2, s2s1, Delta
const RULES = [
  /* t0=e        */ { s1: { p: [], t: 1 }, s2: { p: [], t: 2 } },
  /* t1=s1       */ { s1: { p: [['x', 1]], t: 0 }, s2: { p: [], t: 3 } },
  /* t2=s2       */ { s1: { p: [], t: 4 }, s2: { p: [['y', 1]], t: 0 } },
  /* t3=s1s2     */ { s1: { p: [], t: 5 }, s2: { p: [['y', -1], ['x', -1], ['c', 1]], t: 1 } },
  /* t4=s2s1     */ { s1: { p: [['x', -1], ['y', -1], ['c', 1]], t: 2 }, s2: { p: [], t: 5 } },
  /* t5=Delta    */ { s1: { p: [['y', 1]], t: 3 }, s2: { p: [['x', 1]], t: 4 } },
];

function buildTransversalModel(Q, phi) {
  const qElems = Q.elements();
  const qN = qElems.length;
  const qIndex = new Map();
  qElems.forEach((e, i) => qIndex.set(Q.key(e), i));
  const N = qN * 6;
  const idx = (qi, ti) => qi * 6 + ti;

  function buildPerm(which) {
    const perm = new Array(N);
    for (let qi = 0; qi < qN; qi++) {
      for (let ti = 0; ti < 6; ti++) {
        const rule = RULES[ti][which];
        const pElem = evalWord(Q, phi, rule.p);
        const newQ = Q.mul(qElems[qi], pElem);
        const newQi = qIndex.get(Q.key(newQ));
        if (newQi === undefined) throw new Error('transversal model: Q closure broken');
        perm[idx(qi, ti)] = idx(newQi, rule.t);
      }
    }
    return perm;
  }

  const perm1 = buildPerm('s1');
  const perm2 = buildPerm('s2');
  return { Q, phi, qElems, qIndex, N, idx, perm1, perm2 };
}

function invPerm(perm) {
  const inv = new Array(perm.length);
  for (let i = 0; i < perm.length; i++) inv[perm[i]] = i;
  return inv;
}
function composeRight(a, b) { // apply a then b
  const out = new Array(a.length);
  for (let i = 0; i < a.length; i++) out[i] = b[a[i]];
  return out;
}
function composeAll(perms) {
  let res = perms[0];
  for (let i = 1; i < perms.length; i++) res = composeRight(res, perms[i]);
  return res;
}
function identityPerm(n) { const p = new Array(n); for (let i = 0; i < n; i++) p[i] = i; return p; }
function permEq(a, b) { if (a.length !== b.length) return false; for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false; return true; }
function permPow(perm, k) {
  const N = perm.length;
  if (k === 0) return identityPerm(N);
  const base = k < 0 ? invPerm(perm) : perm;
  let res = identityPerm(N);
  for (let i = 0; i < Math.abs(k); i++) res = composeRight(res, base);
  return res;
}

// x = sigma1^2, y = sigma2^2, Delta = s1 s2 s1, c = Delta^2
function modelDerivedPerms(model) {
  const x_perm = composeRight(model.perm1, model.perm1);
  const y_perm = composeRight(model.perm2, model.perm2);
  const delta_perm = composeAll([model.perm1, model.perm2, model.perm1]);
  const c_perm = composeRight(delta_perm, delta_perm);
  return { x_perm, y_perm, delta_perm, c_perm };
}

// F2 語 (x,y のみ) を sigma-permutation へ: x^k -> s1^{2k}, y^k -> s2^{2k}
function xyWordToPerm(model, tokens) {
  const N = model.N;
  let res = identityPerm(N);
  for (const [gen, k] of tokens) {
    const base = gen === 'x' ? model.perm1 : model.perm2;
    res = composeRight(res, permPow(base, 2 * k));
  }
  return res;
}

// ---------- 自己検査 ----------
function selfCheck() {
  const log = [];
  let ok = true;

  // (0) Dn 群の公理 (単位元・逆元・簡単な結合則スポットチェック)
  {
    const Dn = makeDn(7);
    const els = Dn.elements();
    let axFail = 0;
    for (const g of els) {
      if (!Dn.eq(Dn.mul(g, Dn.id), g)) axFail++;
      if (!Dn.eq(Dn.mul(g, Dn.inv(g)), Dn.id)) axFail++;
    }
    // 結合則スポットチェック (全 343 通りは重いので簡易サンプル)
    const sample = els.slice(0, 6);
    for (const a of sample) for (const b of sample) for (const c of sample) {
      const l = Dn.mul(Dn.mul(a, b), c);
      const r = Dn.mul(a, Dn.mul(b, c));
      if (!Dn.eq(l, r)) axFail++;
    }
    log.push(`D7 群公理 (単位元/逆元/結合則サンプル): ${axFail === 0 ? 'PASS' : 'FAIL(' + axFail + ')'}`);
    if (axFail !== 0) ok = false;
  }

  // (1),(2),(3) braid / sigma^2 / c-check / 群位数較正 を n=5,8 で実施
  for (const n of [5, 8]) {
    const Dn = makeDn(n);
    const r = { a: 1, e: 0 }, s = { a: 0, e: 1 };
    const phi = { x: s, y: Dn.mul(r, s), c: Dn.id };
    const model = buildTransversalModel(Dn, phi);
    const { x_perm, y_perm, delta_perm, c_perm } = modelDerivedPerms(model);

    // braid: s1 s2 s1 == s2 s1 s2
    const lhsBraid = composeAll([model.perm1, model.perm2, model.perm1]);
    const rhsBraid = composeAll([model.perm2, model.perm1, model.perm2]);
    const braidOk = permEq(lhsBraid, rhsBraid);
    log.push(`n=${n}: braid s1s2s1=s2s1s2 : ${braidOk ? 'PASS' : 'FAIL'}`);
    if (!braidOk) ok = false;

    // sigma_i^2 は t 成分を固定し、t=t1(=e) では q -> q*phi(x or y)
    let tFixOk = true, expectAtE_x = true, expectAtE_y = true;
    for (let qi = 0; qi < model.qElems.length; qi++) {
      for (let ti = 0; ti < 6; ti++) {
        const p = model.idx(qi, ti);
        const dx = x_perm[p], dy = y_perm[p];
        if (dx % 6 !== ti) tFixOk = false;
        if (dy % 6 !== ti) tFixOk = false;
      }
      const p0 = model.idx(qi, 0);
      const expQ_x = model.qIndex.get(Dn.key(Dn.mul(model.qElems[qi], phi.x)));
      const expQ_y = model.qIndex.get(Dn.key(Dn.mul(model.qElems[qi], phi.y)));
      if (Math.floor(x_perm[p0] / 6) !== expQ_x) expectAtE_x = false;
      if (Math.floor(y_perm[p0] / 6) !== expQ_y) expectAtE_y = false;
    }
    log.push(`n=${n}: sigma_i^2 が t 成分を固定 : ${tFixOk ? 'PASS' : 'FAIL'}`);
    log.push(`n=${n}: sigma1^2|_{t=e} = q*phi(x) : ${expectAtE_x ? 'PASS' : 'FAIL'}`);
    log.push(`n=${n}: sigma2^2|_{t=e} = q*phi(y) : ${expectAtE_y ? 'PASS' : 'FAIL'}`);
    if (!tFixOk || !expectAtE_x || !expectAtE_y) ok = false;

    // c-check: c = Delta^2 は全点で q -> q*phi(c) を一様に与え、t 成分を固定 (c は PB3 中心)
    let cUniformOk = true;
    for (let qi = 0; qi < model.qElems.length; qi++) {
      for (let ti = 0; ti < 6; ti++) {
        const p = model.idx(qi, ti);
        if (c_perm[p] % 6 !== ti) cUniformOk = false;
        const expQ = model.qIndex.get(Dn.key(Dn.mul(model.qElems[qi], phi.c)));
        if (Math.floor(c_perm[p] / 6) !== expQ) cUniformOk = false;
      }
    }
    log.push(`n=${n}: c-hat = phi(c) が全点で一様 : ${cUniformOk ? 'PASS' : 'FAIL'}`);
    if (!cUniformOk) ok = false;

    // 群位数較正: |<sigma1,sigma2>| = 6|Gn| (n=5: 3000, n=8: 1536) -- wp2-transversal-model.md 検算記録より
    const expectedGnOrd = expectedGnOrder(n);
    const expectedGroupOrder = 6 * expectedGnOrd;
    const inv1 = invPerm(model.perm1), inv2 = invPerm(model.perm2);
    const gens = [model.perm1, model.perm2, inv1, inv2];
    const seen = new Map();
    const id0 = identityPerm(model.N);
    seen.set(id0.join(','), true);
    const frontier = [id0];
    let cap = 20000; // 安全キャップ (期待値 <=1536 なので十分)
    while (frontier.length && seen.size < cap) {
      const e = frontier.pop();
      for (const g of gens) {
        const cand = composeRight(e, g);
        const k = cand.join(',');
        if (!seen.has(k)) { seen.set(k, true); frontier.push(cand); }
      }
    }
    const groupOrder = seen.size;
    const orderOk = (groupOrder === expectedGroupOrder);
    log.push(`n=${n}: |<sigma1hat,sigma2hat>| = ${groupOrder} (期待 ${expectedGroupOrder} = 6*|G_${n}|=6*${expectedGnOrd}) : ${orderOk ? 'PASS' : 'FAIL'}`);
    if (!orderOk) ok = false;
  }

  return { ok, log };
}

// ---------- 主要判定ロジック (証明書ごと) ----------

function dihedralPhi(n) {
  const Dn = makeDn(n);
  const r = { a: 1, e: 0 }, s = { a: 0, e: 1 };
  return { Q: Dn, phi: { x: s, y: Dn.mul(r, s), c: Dn.id } };
}

function controlN5Phi() {
  const C5 = makeCyclic(5);
  return { Q: C5, phi: { x: 2, y: 2, c: 1 } };
}

function tripleFromCertFormat(arr) {
  // 証明書の f_triple: [[a,e],[a,e],[a,e]]
  return arr.map(([a, e]) => ({ a, e }));
}

function checkHexagon(model, shadow) {
  const { perm1, perm2 } = model;
  const inv1 = invPerm(perm1), inv2 = invPerm(perm2);
  const { x_perm, y_perm, c_perm } = modelDerivedPerms(model);
  const invX = invPerm(x_perm), invY = invPerm(y_perm), invC = invPerm(c_perm);
  const m = shadow.m;
  const fPerm = xyWordToPerm(model, shadow.f_word);
  const invF = invPerm(fPerm);

  // (3.3): s1^{2m+1} f^-1 s2^{2m+1} f == f^-1 s1 s2 x^-m c^m
  const lhs33 = composeAll([permPow(perm1, 2 * m + 1), invF, permPow(perm2, 2 * m + 1), fPerm]);
  const rhs33 = composeAll([invF, perm1, perm2, permPow(x_perm, -m), permPow(c_perm, m)]);
  const ok33 = permEq(lhs33, rhs33);

  // (3.4): f^-1 s2^{2m+1} f s1^{2m+1} == s2 s1 y^-m c^m f
  const lhs34 = composeAll([invF, permPow(perm2, 2 * m + 1), fPerm, permPow(perm1, 2 * m + 1)]);
  const rhs34 = composeAll([perm2, perm1, permPow(y_perm, -m), permPow(c_perm, m), fPerm]);
  const ok34 = permEq(lhs34, rhs34);

  return { ok33, ok34, ok: ok33 && ok34 };
}

function checkFWordVsTriple(Gn, n, shadow) {
  const { Triple, phiTriple } = Gn;
  const computed = evalWord(Triple, phiTriple, shadow.f_word);
  const given = tripleFromCertFormat(shadow.f_triple);
  const eq = Triple.eq(computed, given);
  return { ok: eq, computed_key: Triple.key(computed), given_key: Triple.key(given) };
}

function checkCharmingAndSurjective(Gn, n, shadow) {
  const { Triple, phiTriple, GnMap, derived, X, Y } = Gn;
  const m = shadow.m;
  const fTriple = tripleFromCertFormat(shadow.f_triple);
  // charming: f in [Gn,Gn]
  const charming = derived.has(Triple.key(fTriple));

  // surjective: <x^{2m+1}, f^-1 y^{2m+1} f> == Gn
  const g1 = Triple.pow(X, 2 * m + 1);
  const invF = Triple.inv(fTriple);
  const g2 = Triple.mul(Triple.mul(invF, Triple.pow(Y, 2 * m + 1)), fTriple);
  const gen = subgroupClosure(Triple, [g1, g2]);
  const surjective = gen.size === GnMap.size;

  return { charming, surjective, ok: charming && surjective };
}

function checkThm43(Gn, n, cert) {
  const expected = thm43ShadowSet(n);
  const expectedKeys = new Set(expected.shadows.map((s) => `${s.m}|${tripleKey(s.triple)}`));
  const certKeys = new Set();
  const dupCount = { count: 0 };
  for (const sh of cert.shadows) {
    const k = `${mod(sh.m, expected.Nord)}|${tripleKey(sh.f_triple)}`;
    if (certKeys.has(k)) dupCount.count++;
    certKeys.add(k);
  }
  let missingInCert = 0, extraInCert = 0;
  for (const k of expectedKeys) if (!certKeys.has(k)) missingInCert++;
  for (const k of certKeys) if (!expectedKeys.has(k)) extraInCert++;
  const setEqual = (missingInCert === 0 && extraInCert === 0 && certKeys.size === expectedKeys.size);
  return {
    ok: setEqual,
    expected_count: expectedKeys.size,
    cert_count: certKeys.size,
    missing_in_cert: missingInCert,
    extra_in_cert: extraInCert,
    duplicates_in_cert: dupCount.count,
  };
}

// --- 検査項目 6 (kernel_cert / (4.11)) : PROVISIONAL ---
// h = [u,v] アフィン表記 (Z/n 上, j -> u*j + v mod n) と解釈。
// b := (j -> (2m+1) j). h1 = r^{-2k-m} b すなわち j -> (2m+1)j - (2k+m)。
// h2 = b すなわち j -> (2m+1) j。
// h3 = b (m 偶): j -> (2m+1) j。 h3 = b s (m 奇, s(j)=-j 適用後に b): j -> -(2m+1) j。
// 検証 (本実装の解釈): (h1,h2,h3) による共役で T^{PB3}(x), T^{PB3}(y) の各座標を
//   psi_n(x)=(r,s,s), psi_n(y)=(rs,r,rs) の対応座標に写す。
//   affine j->u*j+v は Dn の中で r^v * (r^u の "linear part" にあたる自己同型) に対応するため、
//   ここでは共役先の Dn 元を r^a s^e -> (h の j->uj+v が r,s の作用にどう対応するか) で計算する。
//   具体的には、j->u*j+v は Sym(Z/n) の元とみなし、r=(j->j+1) は j->j+1, s=(j->-j) に対応させ、
//   Dn の元 r^a s^e を "j -> ((-1)^e) j + a" に写像するホモトピー phi_perm(a,e) := (u=(-1)^e, v=a) とみなす。
//   共役 h * phi_perm(r^a s^e) * h^-1 を affine 合成で計算し、それが対応する psi_n 座標の
//   affine 表現と一致するかを見る。
function affineOfDnElement(n, el) {
  // r^a s^e <-> j -> ((-1)^e) j + a  (Lemma 4.2: r(j)=j+1, s(j)=-j という左作用の規約)
  return { u: el.e === 0 ? 1 : -1, v: el.a };
}
function affineCompose(n, f, g) {
  // (f after g): j -> f(g(j)) = f(u_g j + v_g) = u_f (u_g j + v_g) + v_f = u_f u_g j + (u_f v_g + v_f)
  return { u: mod(f.u * g.u, n), v: mod(f.u * g.v + f.v, n) };
}
function affineInv(n, f) {
  // f: j -> u j + v.  f^-1: j -> u^-1 (j - v) = u^-1 j - u^-1 v.  u in {1,-1} なので u^-1=u。
  const uinv = f.u; // u^2=1 in {1,-1}
  return { u: uinv, v: mod(-uinv * f.v, n) };
}
function affineEq(n, f, g) { return mod(f.u, n) === mod(g.u, n) && mod(f.v, n) === mod(g.v, n); }

function checkKernelCert(n, shadow) {
  const kc = shadow.kernel_cert;
  if (!kc) return { ok: false, reason: 'kernel_cert 欠落', provisional_interpretation: true };
  if (kc.type === 'brute') {
    return { ok: null, reason: 'brute type は本チェッカーでは未対応 (control 用, 別ロジックが必要)', provisional_interpretation: true };
  }
  if (kc.type !== 'conjugator-triple') {
    return { ok: false, reason: `未知の kernel_cert.type: ${kc.type}`, provisional_interpretation: true };
  }
  const m = shadow.m;
  const hRaw = kc.h; // [[u,v],[u,v],[u,v]]
  if (!Array.isArray(hRaw) || hRaw.length !== 3) return { ok: false, reason: 'h が 3 要素でない', provisional_interpretation: true };
  const h = hRaw.map(([u, v]) => ({ u: mod(u, n), v: mod(v, n) }));

  // psi_n の座標: x -> (r,s,s), y -> (rs,r,rs)  それぞれの affine 表現
  const rAff = { u: 1, v: 1 };       // r: j->j+1
  const sAff = { u: -1, v: 0 };      // s: j->-j
  const rsAff = affineCompose(n, rAff, sAff); // rs: j -> r(s(j)) = -j+1 (左作用: s のち r)
  const psiX = [sAff, sAff, sAff];       // x -> (r,s,s) の 2405 記法だが x=phi(x)=s は 1 コピー目... 実際は (r,s,s) 全体
  // 訂正: psi_n(x) = (r,s,s), psi_n(y) = (rs,r,rs) -- 3 座標
  const psiXTriple = [rAff, sAff, sAff];
  const psiYTriple = [rsAff, rAff, rsAff];

  // T^{PB3}(x) の affine 表現 (3 座標): x^{2m+1} を各座標で計算
  //   座標 i の x 像は psi_n(x)_i の (2m+1) 乗 (affine の合成をその回数繰り返す)
  function affinePow(n, f, k) {
    if (k === 0) return { u: 1, v: 0 };
    const base = k < 0 ? affineInv(n, f) : f;
    let res = { u: 1, v: 0 };
    for (let i = 0; i < Math.abs(k); i++) res = affineCompose(n, res, base);
    return res;
  }
  const Tx = psiXTriple.map((f) => affinePow(n, f, 2 * m + 1));
  // T^{PB3}(y) は f (shadow の f_word) による共役が必要だが、affine 表現の同時対応は複雑なため、
  // ここでは h1,h2,h3 が Tx をそのまま psi_n(x) 座標へ写す等式のみを検査する (弱い検査、要確認)。
  let okX = true;
  for (let i = 0; i < 3; i++) {
    const conj = affineCompose(n, affineCompose(n, h[i], Tx[i]), affineInv(n, h[i]));
    if (!affineEq(n, conj, psiXTriple[i])) okX = false;
  }
  return {
    ok: okX,
    note: 'PROVISIONAL: (4.11) の literal な式が未入手のため x 座標の共役等式のみ検査。y 座標式は未実装 (要 司令塔確認)。',
    provisional_interpretation: true,
  };
}

// --- 検査項目 10 (ls_witness / (5.1)) : PROVISIONAL ---
function checkLsWitness(Gn, n, entry) {
  // entry: { m, k, g_word, h_word }
  // item (G) の witness 式 (抽出ノート): f = x^{2k} y^{-2k} z^{kappa(m)}
  //   g := x^{2k} z^{kappa(m)/2}          (4 | kappa(m))
  //      : y^{2k+2} z^{kappa(m)/2}        (4 not| kappa(m))
  //   h := x^{2k+m} y^{m}                 (m == 0 mod 6)
  //      : x^{2k-1} z^{-m-2}              (m == 2 mod 6)
  //      : x^{-2k-m+1} y^{-m}             (m == 3 mod 6)
  //      : x^{-2k} z^{-m}                 (m == 5 mod 6)
  // z = (xy)^-1  (2401 定義)
  // 本実装は「与えられた g_word, h_word が上記の明示式に一致するか」を再計算で検証する。
  // (5.1) 自体 (LS 条件が g,h に要求する式) の literal な式は未入手のため、
  // ここでは「証明書の g_word/h_word が item(G) の式に一致するか」のみを PROVISIONAL に検査する。
  const { m, k } = entry;
  const kap = kappa(m);
  const mm6 = mod(m, 6);
  let expectedG;
  if (kap % 4 === 0) expectedG = [['x', 2 * k], ['z', kap / 2]];
  else expectedG = [['y', 2 * k + 2], ['z', kap / 2]];
  let expectedH = null;
  if (mm6 === 0) expectedH = [['x', 2 * k + m], ['y', m]];
  else if (mm6 === 2) expectedH = [['x', 2 * k - 1], ['z', -m - 2]];
  else if (mm6 === 3) expectedH = [['x', -2 * k - m + 1], ['y', -m]];
  else if (mm6 === 5) expectedH = [['x', -2 * k], ['z', -m]];
  if (expectedH === null) {
    return { ok: null, reason: `m mod 6 = ${mm6} は抽出ノートの item(G) に式が無いケース`, provisional_interpretation: true };
  }
  const wordEq = (a, b) => JSON.stringify(a) === JSON.stringify(b);
  const gOk = wordEq(entry.g_word, expectedG);
  const hOk = wordEq(entry.h_word, expectedH);
  return { ok: gOk && hOk, g_ok: gOk, h_ok: hOk, expectedG, expectedH, provisional_interpretation: true };
}

// --- 検査項目 7: composition_table via (3.53) + (4.19)(4.20) ---
function composeShadowWords(m1, f1Tokens, m2, f2Tokens) {
  // E_{m1,f1}(x^k) = x^{k(2m1+1)}
  // E_{m1,f1}(y^k) = f1^-1 y^{k(2m1+1)} f1
  const u1 = 2 * m1 + 1;
  const invF1 = f1Tokens.slice().reverse().map(([g, p]) => [g, -p]);
  const eOfF2 = [];
  for (const [gen, p] of f2Tokens) {
    if (gen === 'x') {
      eOfF2.push(['x', p * u1]);
    } else if (gen === 'y') {
      for (const t of invF1) eOfF2.push(t);
      eOfF2.push(['y', p * u1]);
      for (const t of f1Tokens) eOfF2.push(t);
    }
  }
  const composedWord = f1Tokens.concat(eOfF2);
  const mNew = mod(2 * m1 * m2 + m1 + m2, Infinity); // reduce later with actual Nord
  return { mNewRaw: 2 * m1 * m2 + m1 + m2, composedWord };
}

function checkCompositionEntry(Gn, n, Nord, shadows, i, j, k) {
  const shA = shadows[i], shB = shadows[j], shC = shadows[k];
  const { mNewRaw, composedWord } = composeShadowWords(shA.m, shA.f_word, shB.m, shB.f_word);
  const mNew = mod(mNewRaw, Nord);
  const mOk = mNew === mod(shC.m, Nord);
  const { Triple, phiTriple } = Gn;
  const computedTriple = evalWord(Triple, phiTriple, composedWord);
  const givenTriple = tripleFromCertFormat(shC.f_triple);
  const tripleOk = Triple.eq(computedTriple, givenTriple);
  // (4.19): (2m1+1)(2m2+1) = 2mNewRaw+1  -- 代数的恒等式、常に真 (自己整合性チェック)
  const u1 = 2 * shA.m + 1, u2 = 2 * shB.m + 1;
  const id419 = (u1 * u2) === (2 * mNewRaw + 1);
  // (4.20): kappa(m1)+kappa(m2)-2 kappa(m1) kappa(m2) = kappa(mNewRaw)  -- mod 適用前の整数関係として確認は
  // kappa が mod Nord 依存のため、mod Nord 上の代表で比較する
  const k1 = kappa(mod(shA.m, Nord)), k2 = kappa(mod(shB.m, Nord)), kNew = kappa(mNew);
  const lhs420 = mod(k1 + k2 - 2 * k1 * k2, n);
  const rhs420 = mod(kNew, n);
  // 注: kappa は本来 Dn の r 冪の指数として mod n で解釈するのが自然なので mod n で比較
  const id420 = lhs420 === rhs420;
  return { ok: mOk && tripleOk, mOk, tripleOk, id419, id420 };
}

// --- 検査項目 8: inverse via composition round-trip ---
function checkInverseEntry(Gn, n, Nord, shadows, i, iInv) {
  const shA = shadows[i], shB = shadows[iInv];
  // shA ∘ shB should be identity (0, f=1) and shB ∘ shA should be identity too
  const c1 = checkCompositionEntry(Gn, n, Nord, [shA, shB, { m: 0, f_word: [], f_triple: identityTripleFormat() }], 0, 1, 2);
  const c2 = checkCompositionEntry(Gn, n, Nord, [shB, shA, { m: 0, f_word: [], f_triple: identityTripleFormat() }], 0, 1, 2);
  return { ok: c1.ok && c2.ok, forward: c1, backward: c2 };
}
function identityTripleFormat() { return [[0, 0], [0, 0], [0, 0]]; }

// --- 検査項目 9: reduction ---
function checkReductionEntry(n, redEntry, sourceShadows, targetCert) {
  if (!targetCert) return { ok: null, reason: `目標証明書 ${redEntry.to} が見つからない` };
  const targetN = targetCert.target.n;
  const GnTarget = buildGn(targetN);
  const targetNord = lcm(targetN, 2);
  const results = [];
  const coveredTargetIdx = new Set();
  for (let i = 0; i < sourceShadows.length; i++) {
    const sh = sourceShadows[i];
    const mReduced = mod(sh.m, targetNord);
    const tripleReduced = evalWord(GnTarget.Triple, GnTarget.phiTriple, sh.f_word);
    const claimedIdx = redEntry.image[i];
    const claimedShadow = targetCert.shadows[claimedIdx];
    const okM = claimedShadow ? mod(claimedShadow.m, targetNord) === mReduced : false;
    const okTriple = claimedShadow ? GnTarget.Triple.eq(tripleReduced, tripleFromCertFormat(claimedShadow.f_triple)) : false;
    results.push({ i, claimedIdx, okM, okTriple });
    if (claimedShadow) coveredTargetIdx.add(claimedIdx);
  }
  const allOk = results.every((r) => r.okM && r.okTriple);
  const surjectiveOk = coveredTargetIdx.size === targetCert.shadows.length;
  return { ok: allOk && (redEntry.surjective ? surjectiveOk : true), results, surjectiveOk };
}

// ---------- 証明書1件の検査 ----------
function checkCertificate(cert, certsById) {
  const verdict = { id: cert.target.id, family: cert.target.family, schema: cert.schema, items: {} };
  const isDihedral = cert.target.family === 'dihedral';
  const n = cert.target.n;

  const { Q, phi } = isDihedral ? dihedralPhi(n) : controlN5Phi();
  const model = buildTransversalModel(Q, phi);
  const Gn = isDihedral ? buildGn(n) : null;

  // item 1: counts 整合
  {
    const c = cert.counts || {};
    const monotone = (c.raw_candidates >= c.hexagon_pass) && (c.hexagon_pass >= c.charming_pass) && (c.charming_pass >= c.surjective_pass);
    const matchesShadowLen = c.surjective_pass === cert.shadows.length;
    let matchesThm43 = null;
    if (isDihedral) {
      const t43 = thm43ShadowSet(n);
      matchesThm43 = (c.surjective_pass === t43.shadows.length);
    }
    verdict.items['1_counts'] = { ok: monotone && matchesShadowLen && (matchesThm43 !== false), monotone, matchesShadowLen, matchesThm43 };
  }

  // item 2: full hexagon per shadow
  {
    let allOk = true; const fails = [];
    for (let i = 0; i < cert.shadows.length; i++) {
      const r = checkHexagon(model, cert.shadows[i]);
      if (!r.ok) { allOk = false; fails.push({ i, r }); }
    }
    verdict.items['2_hexagon'] = { ok: allOk, checked: cert.shadows.length, fails };
  }

  // item 3: f_word <-> f_triple (dihedral only, needs psi_n)
  if (isDihedral) {
    let allOk = true; const fails = [];
    for (let i = 0; i < cert.shadows.length; i++) {
      const r = checkFWordVsTriple(Gn, n, cert.shadows[i]);
      if (!r.ok) { allOk = false; fails.push({ i, r }); }
    }
    verdict.items['3_f_word_vs_triple'] = { ok: allOk, checked: cert.shadows.length, fails };
  }

  // item 4: charming + surjective (dihedral only)
  if (isDihedral) {
    let allOk = true; const fails = [];
    for (let i = 0; i < cert.shadows.length; i++) {
      const r = checkCharmingAndSurjective(Gn, n, cert.shadows[i]);
      if (!r.ok) { allOk = false; fails.push({ i, r }); }
    }
    verdict.items['4_charming_surjective'] = { ok: allOk, checked: cert.shadows.length, fails };
  }

  // item 5: Thm 4.3 set equality (dihedral only)
  if (isDihedral) {
    verdict.items['5_thm43_set'] = checkThm43(Gn, n, cert);
  }

  // item 6: kernel_cert (4.11) -- PROVISIONAL
  {
    let allOk = true; const fails = []; let anyProvisional = false;
    for (let i = 0; i < cert.shadows.length; i++) {
      const sh = cert.shadows[i];
      const r = isDihedral ? checkKernelCert(n, sh) : { ok: null, reason: 'control family: 別ロジック未実装' };
      if (r.provisional_interpretation) anyProvisional = true;
      if (r.ok === false) { allOk = false; fails.push({ i, r }); }
    }
    verdict.items['6_kernel_cert'] = { ok: allOk, provisional_interpretation: anyProvisional, checked: cert.shadows.length, fails, note: '(4.11) 未確定式のため PROVISIONAL' };
  }

  // item 7: composition_table via (3.53)(4.19)(4.20)
  if (isDihedral && cert.composition_table) {
    const Nord = lcm(n, 2);
    let allOk = true; const fails = [];
    for (const [i, j, k] of cert.composition_table) {
      const r = checkCompositionEntry(Gn, n, Nord, cert.shadows, i, j, k);
      if (!r.ok) { allOk = false; fails.push({ i, j, k, r }); }
    }
    verdict.items['7_composition_table'] = { ok: allOk, checked: cert.composition_table.length, fails };
  }

  // item 8: inverse via (3.54) round-trip
  if (isDihedral && cert.inverse_map) {
    const Nord = lcm(n, 2);
    let allOk = true; const fails = [];
    for (const [i, iInv] of cert.inverse_map) {
      const r = checkInverseEntry(Gn, n, Nord, cert.shadows, i, iInv);
      if (!r.ok) { allOk = false; fails.push({ i, iInv, r }); }
    }
    verdict.items['8_inverse_map'] = { ok: allOk, checked: cert.inverse_map.length, fails };
  }

  // item 9: reduction
  if (isDihedral && cert.reduction) {
    let allOk = true; const fails = [];
    for (const redEntry of cert.reduction) {
      const targetCert = certsById.get(redEntry.to);
      const r = checkReductionEntry(n, redEntry, cert.shadows, targetCert);
      if (r.ok !== true) { allOk = false; fails.push({ to: redEntry.to, r }); }
    }
    verdict.items['9_reduction'] = { ok: allOk, checked: cert.reduction.length, fails };
  }

  // item 10: ls_witness (5.1) -- PROVISIONAL
  if (isDihedral && cert.ls_witness) {
    let allOk = true; const fails = []; let anyProvisional = false;
    for (const entry of cert.ls_witness) {
      const r = checkLsWitness(Gn, n, entry);
      if (r.provisional_interpretation) anyProvisional = true;
      if (r.ok === false) { allOk = false; fails.push({ entry, r }); }
    }
    verdict.items['10_ls_witness'] = { ok: allOk, provisional_interpretation: anyProvisional, checked: cert.ls_witness.length, fails, note: '(5.1) 未確定式のため PROVISIONAL' };
  }

  const allItemsOk = Object.values(verdict.items).every((it) => it.ok === true);
  verdict.all_pass = allItemsOk;
  verdict.cross_checked = allItemsOk; // 用語規律: cross-checked (verified は Lean 専有)
  return verdict;
}

// ---------- main ----------
function main() {
  console.log('=== WP2b node 照合器: 起動時自己検査 ===');
  const sc = selfCheck();
  for (const line of sc.log) console.log(' - ' + line);
  if (!sc.ok) {
    console.log('\n自己検査 FAIL: 証明書の検査には進みません。仕様の再確認が必要です。');
    process.exitCode = 1;
    return;
  }
  console.log('\n自己検査: ALL PASS\n');

  console.log('=== Thm 4.3 閉じた式の自前生成 (n=3..16) ===');
  for (let n = 3; n <= 16; n++) {
    const Gn = buildGn(n);
    const expectedOrd = expectedGnOrder(n);
    const actualOrd = Gn.GnMap.size;
    const t43 = thm43ShadowSet(n);
    const derivedOrd = Gn.derived.size;
    console.log(`n=${n}: |G_n| actual=${actualOrd} expected=${expectedOrd} match=${actualOrd === expectedOrd} | N_ord=${t43.Nord} n1=${t43.n1} |X_n|=${t43.Xn.length} |GT(K^(${n}))|_expected=${t43.shadows.length} | |[Gn,Gn]|=${derivedOrd}`);
  }

  console.log('\n=== 証明書の検査 ===');
  if (!existsSync(CERT_DIR)) {
    console.log(`certificates/ ディレクトリが存在しません (${CERT_DIR})。WP2a (探索器) 待ち — 本実行では自己検査と Thm4.3 生成のみ完了。`);
    return;
  }
  const files = readdirSync(CERT_DIR).filter((f) => f.endsWith('.json'));
  if (files.length === 0) {
    console.log('certificates/ は存在するが *.json が 0 件。WP2a 待ち。');
    return;
  }

  const certs = files.map((f) => JSON.parse(readFileSync(join(CERT_DIR, f), 'utf8')));
  const certsById = new Map();
  for (const c of certs) certsById.set(c.target.id, c);

  if (!existsSync(VERDICT_DIR)) mkdirSync(VERDICT_DIR, { recursive: true });

  for (const cert of certs) {
    console.log(`\n--- ${cert.target.id} (n=${cert.target.n ?? 'n/a'}, family=${cert.target.family}) ---`);
    let verdict;
    try {
      verdict = checkCertificate(cert, certsById);
    } catch (err) {
      verdict = { id: cert.target.id, error: String(err && err.stack || err), all_pass: false, cross_checked: false };
    }
    const outPath = join(VERDICT_DIR, `${cert.target.id}.v1.verdict.json`);
    writeFileSync(outPath, JSON.stringify(verdict, null, 2));
    console.log(`verdict -> ${outPath}`);
    if (verdict.items) {
      for (const [k, v] of Object.entries(verdict.items)) {
        console.log(`  ${k}: ${v.ok === true ? 'PASS' : v.ok === false ? 'FAIL' : 'N/A'}${v.provisional_interpretation ? ' [PROVISIONAL]' : ''}`);
      }
    }
    console.log(`  ALL PASS (cross-checked): ${verdict.all_pass ? 'YES' : 'NO'}`);
  }
}

main();
