#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PRE-1 (docs/notes/nw7_mainrun_predictions_iffirst_v1.md sec.5, table row PRE-1;
authorized by 裁定 554).

Computes Psi = [(tau_bullet + tau_bullet^2)(h3)]_{deg4} in gr_4(F2), h3 = u1+u2
(the rank-2 free Lie algebra basis fixed by
search/probe/hsp7_v1/hs_prop7_hexagon_vs_pentagon.py: A=[x,y], u1=[A,x], u2=[A,y],
v1=[u1,x], v2=[u1,y], v3=[u2,y]), and decides branch B-1 of the prediction
ticket:

    boxed criterion (ticket sec.4.1):
        |A| = 49  <=>  Psi in F_7 (v1+v2+v3)
        |A| = 7   otherwise

tau_bullet is the FILTERED (non-graded) automorphism x -> y -> z -> x on F2,
z=(xy)^-1, i.e. tau(A) = subst(A, y -> ZED) applied directly to the stored
tensor-algebra vector of the Lie element A (an algebra endomorphism, hence
also a Lie endomorphism on brackets). This is a non-homogeneous extension of
the existing hexagon-vs-pentagon probe: that script only ever applies tau to
f = exp(F) (group elements); here we apply tau directly to a bare Lie element
of degree 3 (h3) and look at what spills into degree 4 -- exactly Psi.

Scope discipline: rank-2 free Lie algebra linear algebra only, degrees <= 4.
No window, no candidate, no GAP. 705,894-candidate universe is NOT touched.
Numbers below are machine-generated by this script (stdout is the record).
"""
from fractions import Fraction
from itertools import product

DEG = 4
LET = 2
words = [()]
for d in range(1, DEG + 1):
    words += [w for w in product(range(LET), repeat=d)]
widx = {w: i for i, w in enumerate(words)}
NW = len(words)
Z = lambda: [Fraction(0)] * NW


def mul(A, B):
    C = Z()
    for i, a in enumerate(A):
        if a == 0:
            continue
        wa = words[i]
        for j, b in enumerate(B):
            if b == 0:
                continue
            w = wa + words[j]
            if len(w) <= DEG:
                C[widx[w]] += a * b
    return C


def add(*Xs):
    C = Z()
    for X in Xs:
        for i, a in enumerate(X):
            C[i] += a
    return C


def smul(c, A):
    return [Fraction(c) * a for a in A]


def brk(A, B):
    return add(mul(A, B), smul(-1, mul(B, A)))


ONE = Z(); ONE[widx[()]] = Fraction(1)
X = Z(); X[widx[(0,)]] = Fraction(1)
Y = Z(); Y[widx[(1,)]] = Fraction(1)


def expo(A):
    out, term = ONE[:], ONE[:]
    for k in range(1, DEG + 1):
        term = smul(Fraction(1, k), mul(term, A))
        out = add(out, term)
    return out


def loga(A):
    U = add(A, smul(-1, ONE))
    out, term = Z(), ONE[:]
    for k in range(1, DEG + 1):
        term = mul(term, U)
        out = add(out, smul(Fraction((-1) ** (k + 1), k), term))
    return out


def inv(A):
    U = add(A, smul(-1, ONE))
    out, term = ONE[:], ONE[:]
    for k in range(1, DEG + 1):
        term = mul(term, U)
        out = add(out, smul(Fraction((-1) ** k), term))
    return out


def subst(A, ix, iy):
    C = Z()
    for i, a in enumerate(A):
        if a == 0:
            continue
        t = ONE[:]
        for l in words[i]:
            t = mul(t, ix if l == 0 else iy)
        C = add(C, smul(a, t))
    return C


ZED = loga(inv(mul(expo(X), expo(Y))))          # z = log((xy)^-1)
theta = lambda A: subst(A, Y, X)
tau = lambda A: subst(A, Y, ZED)

assert theta(theta(X)) == X and theta(theta(Y)) == Y
assert tau(tau(tau(X))) == X, "tau^3 != id on x"
assert tau(tau(tau(Y))) == Y, "tau^3 != id on y"
prod_xyz = mul(mul(expo(X), expo(Y)), expo(ZED))
assert prod_xyz == ONE, "xyz != 1"
print("setup checks: theta^2=id, tau^3=id, x*y*z=1  -> OK")

A_ = brk(X, Y)
u1, u2 = brk(A_, X), brk(A_, Y)
v1, v2, v3 = brk(u1, X), brk(u1, Y), brk(u2, Y)
assert brk(u2, X) == v2, "Hall relation fails"
print("gr_3(F2) basis u1,u2 fixed; gr_4(F2) basis v1,v2,v3 fixed (Hall relation OK)")

h3 = add(u1, u2)                      # ticket sec.1.3: h3 := u1+u2
h4 = add(v1, smul(4, v2), v3)         # ticket sec.1.3: h4 := v1+4v2+v3


def degpart(V, d):
    return [V[widx[w]] for w in words if len(w) == d]


def decompose_in_v(vec4):
    """Solve vec4 (16-dim, degree-4 word coords) = a*v1+b*v2+c*v3 exactly.
    Returns (a,b,c, residual_vector). residual should be all-zero if vec4
    genuinely lies in span(v1,v2,v3) (as PENT-HOM/D4-POWER predict)."""
    cols = [degpart(v1, 4), degpart(v2, 4), degpart(v3, 4)]
    rhs = vec4
    n = 3
    M = [[cols[k][r] for k in range(n)] + [rhs[r]] for r in range(len(rhs))]
    piv, r = [], 0
    for c in range(n):
        s = next((i for i in range(r, len(M)) if M[i][c] != 0), None)
        if s is None:
            continue
        M[r], M[s] = M[s], M[r]
        pv = M[r][c]
        M[r] = [q / pv for q in M[r]]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                fq = M[i][c]
                M[i] = [p - fq * q for p, q in zip(M[i], M[r])]
        piv.append(c); r += 1
    sol = [Fraction(0)] * n
    for rr, c in enumerate(piv):
        sol[c] = M[rr][n]
    # residual = vec4 - (a*v1+b*v2+c*v3)
    combo = add(smul(sol[0], v1), smul(sol[1], v2), smul(sol[2], v3))
    resid = [vec4[i] - degpart(combo, 4)[i] for i in range(len(vec4))]
    return sol[0], sol[1], sol[2], resid


def f7(frac):
    """reduce a Fraction to F7 (assumes denominator coprime to 7)."""
    num = frac.numerator % 7
    den = frac.denominator % 7
    if den == 0:
        raise ValueError("denominator divisible by 7: %s" % frac)
    return (num * pow(den, 5, 7)) % 7   # den^{-1} mod 7 = den^{7-2} mod 7


print("\n=== sanity check: PREC-1 general formula, and DUM-HEX (h4 case) ===")
for (al, be, ga) in [(1, 0, 0), (0, 1, 0), (0, 0, 1), (1, 4, 1), (2, 3, 5)]:
    elt = add(smul(al, v1), smul(be, v2), smul(ga, v3))
    s4 = degpart(add(elt, tau(elt), tau(tau(elt))), 4)
    expect_scalar = 2 * al - be + 2 * ga
    expect = smul(expect_scalar, add(v1, v2, v3))
    expect4 = degpart(expect, 4)
    ok = (s4 == expect4)
    print("  (a,b,c)=(%d,%d,%d): (1+tau*+tau*^2) elt |_deg4 == (2a-b+2c)(v1+v2+v3)? %s  [2a-b+2c=%d]"
          % (al, be, ga, ok, expect_scalar))
    assert ok, "PREC-1 general-form sanity check FAILED at (%d,%d,%d)" % (al, be, ga)
h4_deg4 = degpart(add(h4, tau(h4), tau(tau(h4))), 4)
print("  h4=(1,4,1): 2a-b+2c = %d -> (1+tau*+tau*^2)(h4)|_deg4 == 0 (DUM-HEX)? %s"
      % (2*1-4+2*1, all(x == 0 for x in h4_deg4)))

print("\n=== PRE-1: Psi = [(tau + tau^2)(h3)]_deg4 ===")
tau_h3 = tau(h3)
tau2_h3 = tau(tau(h3))
print("  deg-3 part of tau(h3):  ", [str(x) for x in degpart(tau_h3, 3)])
print("  deg-4 part of tau(h3):  ", [str(x) for x in degpart(tau_h3, 4)])
print("  deg-3 part of tau^2(h3):", [str(x) for x in degpart(tau2_h3, 3)])
print("  deg-4 part of tau^2(h3):", [str(x) for x in degpart(tau2_h3, 4)])

Psi_full = add(tau_h3, tau2_h3)
Psi4 = degpart(Psi_full, 4)
print("  Psi (deg4, 16 word coords):", [str(x) for x in Psi4])

a, b, c, resid = decompose_in_v(Psi4)
print("  Psi = a*v1 + b*v2 + c*v3 :  a=%s  b=%s  c=%s" % (a, b, c))
print("  residual (Psi - a*v1-b*v2-c*v3, should be all 0):", [str(x) for x in resid])
in_span = all(r == 0 for r in resid)
print("  Psi in span(v1,v2,v3) (gr_4(F2))? ", in_span)
if not in_span:
    raise SystemExit("PREREGISTRATION_FALSIFIED: Psi does not even lie in gr_4(F2) "
                      "as the ticket sec.2.2 PENT-HOM asserts -- stop, report.")

a7, b7, c7 = f7(a), f7(b), f7(c)
print("  (a,b,c) mod 7 = (%d,%d,%d)" % (a7, b7, c7))
proportional_to_111 = (a7 == b7 == c7)
print("  a==b==c (mod 7), i.e. Psi in F_7(v1+v2+v3)?  ", proportional_to_111)

print("\n=== BRANCH DECISION (B-1) ===")
if proportional_to_111:
    print("  Psi in F_7(v1+v2+v3)  ->  BRANCH B-1a : |A| = 49")
    branch = "B-1a"
else:
    print("  Psi NOT in F_7(v1+v2+v3)  ->  BRANCH B-1b : |A| = 7")
    branch = "B-1b"

print("\nPRE1_RESULT branch=%s a=%s b=%s c=%s a7=%d b7=%d c7=%d proportional=%s"
      % (branch, a, b, c, a7, b7, c7, proportional_to_111))
