#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PRE-2 v2 corrected-lift verification (search/probe/hsp7_v1/pre2_g1_verify_20260805.py)

Commissioned by 司令塔 per 裁定 559, responding to Sol F106-2.4
(sol/sol_reply_106_math33.md): the OLD PRE-2
(search/probe/hsp7_cond4_laneP/pre2_xi_b2_20260805.g) measured the raw Hall-
commutator group element

    r := Comm(Comm(x,y),x) * Comm(Comm(x,y),y)

and treated D(r) as xi = D(g1) for g1 in A = hex(0). Sol's audit point: the
ACTUAL group commutator r (built with GAP's Comm(a,b)=a^-1 b^-1 a b
convention, i.e. with full BCH corrections at every nesting level -- NOT the
formal Lie bracket h3 = u1+u2 used by PRE-1) has

    log(r) = h3 + (v1+v2+v3)   mod gamma_5

so r is NOT an element of A = hex(0) (it fails hexagon condition (3.11) at
degree 4). The correct lift is g1 := r * s^-1 where s is the gamma_4(P)
group-commutator word representing v1+v2+v3 (gamma_4(P) is central, so order
of the product is immaterial).

This script performs the TWO verification points 司令塔 asked for, entirely
independently of Sol's derivation and of the OLD PRE-2 script -- by building
r, s, g1 as HONEST group elements in the truncated (degree<=4) tensor algebra
via the actual group-commutator formula (mul/inv/loga machinery already used
by search/probe/hsp7_v1/hs_prop7_hexagon_vs_pentagon.py and
search/probe/hsp7_v1/pre1_psi_b1_20260805.py), not by assuming any linear
formula for the degree-4 spillover:

  (a) independent confirmation that raw jh3 = r has a nonzero degree-4
      hexagon-condition-(3.11) defect equal to 3*(v1+v2+v3) (mod 7, matches
      Sol's claimed value; here it is *computed*, not looked up)
  (b) confirmation that g1 = r*s^-1 has ZERO degree-4 defect of the same
      condition (i.e. g1 IS in hex(0) up to degree 4 -- realizes an exact
      lift of h3)

Scope discipline: rank-2 free Lie algebra / truncated tensor algebra linear
algebra only, degrees <= 4. No window, no candidate, no GAP process. The
705,894-candidate universe is NOT touched. Numbers below are machine-
generated by this script (stdout is the record).
"""
from fractions import Fraction
from itertools import product

DEG = 4
LET = 2
words = [()]
for d in range(1, DEG + 1):
    words += [w for w in product(range(LET), repeat=d)]
widx = {w: i for i, w in enumerate(words)}
NW = len(words)
Z = lambda: [Fraction(0)] * NW


def mul(A, B):
    C = Z()
    for i, a in enumerate(A):
        if a == 0:
            continue
        wa = words[i]
        for j, b in enumerate(B):
            if b == 0:
                continue
            w = wa + words[j]
            if len(w) <= DEG:
                C[widx[w]] += a * b
    return C


def add(*Xs):
    C = Z()
    for X in Xs:
        for i, a in enumerate(X):
            C[i] += a
    return C


def smul(c, A):
    return [Fraction(c) * a for a in A]


def brk(A, B):
    return add(mul(A, B), smul(-1, mul(B, A)))


ONE = Z(); ONE[widx[()]] = Fraction(1)
X = Z(); X[widx[(0,)]] = Fraction(1)
Y = Z(); Y[widx[(1,)]] = Fraction(1)


def expo(A):
    out, term = ONE[:], ONE[:]
    for k in range(1, DEG + 1):
        term = smul(Fraction(1, k), mul(term, A))
        out = add(out, term)
    return out


def loga(A):
    U = add(A, smul(-1, ONE))
    out, term = Z(), ONE[:]
    for k in range(1, DEG + 1):
        term = mul(term, U)
        out = add(out, smul(Fraction((-1) ** (k + 1), k), term))
    return out


def inv(A):
    U = add(A, smul(-1, ONE))
    out, term = ONE[:], ONE[:]
    for k in range(1, DEG + 1):
        term = mul(term, U)
        out = add(out, smul(Fraction((-1) ** k), term))
    return out


def subst(A, ix, iy):
    C = Z()
    for i, a in enumerate(A):
        if a == 0:
            continue
        t = ONE[:]
        for l in words[i]:
            t = mul(t, ix if l == 0 else iy)
        C = add(C, smul(a, t))
    return C


ZED = loga(inv(mul(expo(X), expo(Y))))          # z = log((xy)^-1)
theta = lambda A: subst(A, Y, X)
tau = lambda A: subst(A, Y, ZED)

assert theta(theta(X)) == X and theta(theta(Y)) == Y
assert tau(tau(tau(X))) == X, "tau^3 != id on x"
assert tau(tau(tau(Y))) == Y, "tau^3 != id on y"
prod_xyz = mul(mul(expo(X), expo(Y)), expo(ZED))
assert prod_xyz == ONE, "xyz != 1"
print("setup checks: theta^2=id, tau^3=id, x*y*z=1  -> OK")

A_ = brk(X, Y)
u1, u2 = brk(A_, X), brk(A_, Y)
v1, v2, v3 = brk(u1, X), brk(u1, Y), brk(u2, Y)
assert brk(u2, X) == v2, "Hall relation fails"
print("gr_3(F2) basis u1,u2 fixed; gr_4(F2) basis v1,v2,v3 fixed (Hall relation OK)")

h3 = add(u1, u2)                      # ticket sec.1.3: h3 := u1+u2


def degpart(V, d):
    return [V[widx[w]] for w in words if len(w) == d]


def decompose_in_v(vec4):
    cols = [degpart(v1, 4), degpart(v2, 4), degpart(v3, 4)]
    rhs = vec4
    n = 3
    M = [[cols[k][r] for k in range(n)] + [rhs[r]] for r in range(len(rhs))]
    piv, r = [], 0
    for c in range(n):
        s = next((i for i in range(r, len(M)) if M[i][c] != 0), None)
        if s is None:
            continue
        M[r], M[s] = M[s], M[r]
        pv = M[r][c]
        M[r] = [q / pv for q in M[r]]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                fq = M[i][c]
                M[i] = [p - fq * q for p, q in zip(M[i], M[r])]
        piv.append(c); r += 1
    sol = [Fraction(0)] * n
    for rr, c in enumerate(piv):
        sol[c] = M[rr][n]
    combo = add(smul(sol[0], v1), smul(sol[1], v2), smul(sol[2], v3))
    resid = [vec4[i] - degpart(combo, 4)[i] for i in range(len(vec4))]
    return sol[0], sol[1], sol[2], resid


def f7(frac):
    num = frac.numerator % 7
    den = frac.denominator % 7
    if den == 0:
        raise ValueError("denominator divisible by 7: %s" % frac)
    return (num * pow(den, 5, 7)) % 7


def hexagon_defect2(F):
    """condition (3.11): tau^2(f) tau(f) f - 1, f=exp(F). Returns the raw
    (truncated tensor-algebra) defect vector (not yet restricted to a degree)."""
    f = expo(F)
    d11 = mul(mul(tau(tau(f)), tau(f)), f)
    return add(d11, smul(-1, ONE))


print("\n=== honest GROUP-commutator construction (GAP Comm(a,b)=a^-1 b^-1 a b) ===")


def GComm(a, b):
    return mul(mul(inv(a), inv(b)), mul(a, b))


gx = expo(X)
gy = expo(Y)
assert loga(gx) == X and loga(gy) == Y, "expo/loga round-trip failed on generators"

c1 = GComm(gx, gy)                      # actual group element "Comm(x,y)"
print("log(Comm(x,y)) deg2 part:", [str(t) for t in degpart(loga(c1), 2)],
      " (compare formal bracket [X,Y] deg2:", [str(t) for t in degpart(A_, 2)], ")")
print("log(Comm(x,y)) deg3 part (BCH spillover beyond the formal bracket):",
      [str(t) for t in degpart(loga(c1), 3)])
print("log(Comm(x,y)) deg4 part (BCH spillover beyond the formal bracket):",
      [str(t) for t in degpart(loga(c1), 4)])

d1 = GComm(c1, gx)                      # Comm(Comm(x,y),x)  (honest group elt)
d2 = GComm(c1, gy)                      # Comm(Comm(x,y),y)  (honest group elt)

r = mul(d1, d2)                         # raw jh3 = r, exactly as in GAP scripts
log_r = loga(r)
print("\n--- log(r), r = Comm(Comm(x,y),x)*Comm(Comm(x,y),y) (honest group elt) ---")
print("deg1 part (expect all 0):", [str(t) for t in degpart(log_r, 1)])
print("deg2 part (expect all 0):", [str(t) for t in degpart(log_r, 2)])
deg3_r = degpart(log_r, 3)
deg3_h3 = degpart(h3, 3)
print("deg3 part == h3 (formal u1+u2) exactly?", deg3_r == deg3_h3)
assert degpart(log_r, 1) == degpart(Z(), 1)
assert degpart(log_r, 2) == degpart(Z(), 2)
assert deg3_r == deg3_h3, "PRE2_STOP: log(r) deg3 != h3 -- premise (pi_3(r)=h3) itself fails"

deg4_r = degpart(log_r, 4)
a_r, b_r, c_r, resid_r = decompose_in_v(deg4_r)
print("deg4 part of log(r), decomposed in (v1,v2,v3): (a,b,c) =", (a_r, b_r, c_r))
print("residual (should be all 0, i.e. deg4 part genuinely in span(v1,v2,v3)):",
      [str(t) for t in resid_r])
assert all(t == 0 for t in resid_r), "PRE2_STOP: log(r) deg4 part not in span(v1,v2,v3)"
print("Sol's claimed correction (a,b,c)=(1,1,1)? ", (a_r, b_r, c_r) == (Fraction(1), Fraction(1), Fraction(1)))

# --- verification point (a): independent hexagon-(3.11) degree-4 defect of raw r ---
def4_r = degpart(hexagon_defect2(log_r), 4)
print("\n[point (a)] hexagon condition (3.11) degree-4 defect of RAW r (log_r = h3+corr):",
      [str(t) for t in def4_r])
da, db, dc, dresid = decompose_in_v(def4_r)
print("  decomposed in (v1,v2,v3): (a,b,c) =", (da, db, dc), " residual:", [str(t) for t in dresid])
assert all(t == 0 for t in dresid)
da7, db7, dc7 = f7(da), f7(db), f7(dc)
print("  mod 7: (%d,%d,%d)" % (da7, db7, dc7))
nonzero_defect_r = not (da7 == 0 and db7 == 0 and dc7 == 0)
print("  raw r's hexagon-(3.11) degree-4 defect is NONZERO mod 7 (r is NOT in hex(0))?", nonzero_defect_r)
print("  expected form 3*(v1+v2+v3) (Sol): matches?", (da7, db7, dc7) == (3, 3, 3))
assert nonzero_defect_r, "PRE2_STOP: expected raw r to FAIL hexagon(3.11) at deg4 per Sol F106-2.4, but defect is 0"

# --- build s: gamma_4(P) group-commutator word for v1+v2+v3, same nesting pattern as jh4 ---
print("\n=== building s (group word for v1+v2+v3, same construction pattern as jh4) ===")
s_v1part = GComm(d1, gx)   # Comm(Comm(Comm(x,y),x),x)  -> should realize v1
s_v2part = GComm(d1, gy)   # Comm(Comm(Comm(x,y),x),y)  -> should realize v2
s_v3part = GComm(d2, gy)   # Comm(Comm(Comm(x,y),y),y)  -> should realize v3

for name, part, expect in [("s_v1part", s_v1part, v1), ("s_v2part", s_v2part, v2), ("s_v3part", s_v3part, v3)]:
    lp = loga(part)
    print(" ", name, "deg<4 all zero?", all(t == 0 for d in (1, 2, 3) for t in degpart(lp, d)),
          " deg4 == expected basis vector exactly?", degpart(lp, 4) == degpart(expect, 4))
    assert all(t == 0 for d in (1, 2, 3) for t in degpart(lp, d)), "unexpected low-degree residue in %s" % name
    assert degpart(lp, 4) == degpart(expect, 4), "%s deg4 part does not match expected basis vector" % name

s_grp = mul(mul(s_v1part, s_v2part), s_v3part)   # s := Comm(Comm(Comm(x,y),x),x)*Comm(Comm(Comm(x,y),x),y)*Comm(Comm(Comm(x,y),y),y)
log_s = loga(s_grp)
print("log(s) deg<4 all zero?", all(t == 0 for d in (1, 2, 3) for t in degpart(log_s, d)))
print("log(s) deg4 == v1+v2+v3 exactly?", degpart(log_s, 4) == degpart(add(v1, v2, v3), 4))
assert all(t == 0 for d in (1, 2, 3) for t in degpart(log_s, d))
assert degpart(log_s, 4) == degpart(add(v1, v2, v3), 4)

# --- g1 = r * s^-1 (gamma_4(P) central -> order immaterial; honest group mult here) ---
g1 = mul(r, inv(s_grp))
log_g1 = loga(g1)
print("\n--- log(g1), g1 = r * s^-1 (honest group elt) ---")
print("deg1 (expect 0):", [str(t) for t in degpart(log_g1, 1)])
print("deg2 (expect 0):", [str(t) for t in degpart(log_g1, 2)])
deg3_g1 = degpart(log_g1, 3)
print("deg3 == h3 exactly?", deg3_g1 == deg3_h3)
deg4_g1 = degpart(log_g1, 4)
print("deg4 (expect all 0, i.e. correction cancelled):", [str(t) for t in deg4_g1])
assert degpart(log_g1, 1) == degpart(Z(), 1)
assert degpart(log_g1, 2) == degpart(Z(), 2)
assert deg3_g1 == deg3_h3, "PRE2_STOP: g1's deg3 part != h3"
g1_deg4_is_zero = all(t == 0 for t in deg4_g1)
print("g1's degree-4 part is exactly zero?", g1_deg4_is_zero)
assert g1_deg4_is_zero, "PRE2_STOP: g1 = r*s^-1 still has nonzero degree-4 residue -- construction of s is wrong"

# --- verification point (b): hexagon condition (3.11) degree-4 defect of g1 ---
def4_g1 = degpart(hexagon_defect2(log_g1), 4)
print("\n[point (b)] hexagon condition (3.11) degree-4 defect of g1 = r*s^-1:",
      [str(t) for t in def4_g1])
ea, eb, ec, eresid = decompose_in_v(def4_g1)
print("  decomposed in (v1,v2,v3): (a,b,c) =", (ea, eb, ec), " residual:", [str(t) for t in eresid])
assert all(t == 0 for t in eresid)
ea7, eb7, ec7 = f7(ea), f7(eb), f7(ec)
print("  mod 7: (%d,%d,%d)" % (ea7, eb7, ec7))
g1_hexagon_defect_zero = (ea7 == 0 and eb7 == 0 and ec7 == 0)
print("  g1's hexagon-(3.11) degree-4 defect is ZERO mod 7 (g1 IS in hex(0) up to deg4)?", g1_hexagon_defect_zero)
assert g1_hexagon_defect_zero, "PRE2_STOP: g1 still fails hexagon(3.11) at deg4 -- g1 not in A. STOP, report."

print("\n=== SUMMARY ===")
print("point_a_raw_r_defect_nonzero:", nonzero_defect_r,
      " value_mod7:", (da7, db7, dc7), " matches_Sol_3(v1+v2+v3):", (da7, db7, dc7) == (3, 3, 3))
print("point_b_g1_defect_zero:", g1_hexagon_defect_zero, " value_mod7:", (ea7, eb7, ec7))
print("g1_deg3_eq_h3:", deg3_g1 == deg3_h3, " g1_deg4_eq_zero:", g1_deg4_is_zero)
print("PRE2_VERIFY_DONE")
