# AUTO-GENERATED by search/d2_gate_v1_track.py -- do not hand-edit.
# permutations from numeric path-tracking (dps=50, n_line=150, n_circle=300)
sigma0_P1 := PermList([10, 11, 12, 13, 14, 15, 16, 18, 17, 4, 6, 5, 8, 7, 9, 2, 1, 3]);;
sigma1_P1 := PermList([4, 5, 6, 1, 2, 3, 7, 9, 8, 13, 14, 15, 10, 11, 12, 16, 18, 17]);;
sigmaInf_P1 := PermList([10, 12, 11, 17, 16, 18, 14, 15, 13, 4, 5, 6, 1, 2, 3, 7, 8, 9]);;
sigma0_P2 := PermList([10, 12, 11, 13, 14, 15, 17, 18, 16, 4, 5, 6, 8, 7, 9, 1, 2, 3]);;
sigma1_P2 := PermList([4, 5, 6, 1, 2, 3, 7, 9, 8, 13, 14, 15, 10, 11, 12, 18, 17, 16]);;
sigmaInf_P2 := PermList([10, 11, 12, 16, 17, 18, 14, 15, 13, 4, 5, 6, 1, 3, 2, 8, 7, 9]);;
