# Design-criterion feasibility: does there exist P = <xb,yb> (2-generated, ord(xb)=ord(yb))
# with C_P(yb) NONSOLVABLE ?  (necessary condition for a nonsolvable G_N, by the Hol sieve)
Print("=== A_13 generated by two 7-cycles with disjoint-but-one supports ===\n");
n := 13;;
A := AlternatingGroup(n);;
yb := (1,2,3,4,5,6,7);;
xb := (7,8,9,10,11,12,13);;
P := Subgroup(A,[xb,yb]);;
Print("|<xb,yb>| = ", Size(P), "   = |A_13| ? ", Size(P) = Size(A), "\n");
Print("ord(xb) = ", Order(xb), "  ord(yb) = ", Order(yb), "\n");
Cy := Centralizer(P, yb);;
Cx := Centralizer(P, xb);;
Print("|C_P(yb)| = ", Size(Cy), "  solvable = ", IsSolvableGroup(Cy), "\n");
Print("|C_P(xb)| = ", Size(Cx), "  solvable = ", IsSolvableGroup(Cx), "\n");
Print("composition factors of C_P(yb): ",
      List(CompositionSeries(Cy), Size), "\n");
# theta : an automorphism of P swapping xb and yb ?
g := PermList(List([1..13], i -> ((7 - i) mod 13) + 1));;  # candidate: reversal-ish
Print("exists g in S_13 with xb^g = yb and yb^g = xb ? ");
found := fail;;
Sn := SymmetricGroup(n);;
reps := 0;;
for t in [1..200000] do
  h := Random(Sn);
  if xb^h = yb and yb^h = xb then found := h; break; fi;
od;
Print(found <> fail, "  (random search)\n");
# deterministic construction: map supports across
h := PermList([7,6,5,4,3,2,1,13,12,11,10,9,8]);;
Print("explicit h = ", h, "   xb^h = ", xb^h, "   yb^h = ", yb^h, "\n");
Print("   xb^h = yb ? ", xb^h = yb, "   yb^h = xb ? ", yb^h = xb, "\n");
# Stab_{Aut(P)}(xb) for P = A_13 :  Aut = S_13, stabiliser = C_{S_13}(xb)
Csx := Centralizer(Sn, xb);;
Print("Stab_{Aut(A_13)}(xb) = C_{S_13}(xb) : order ", Size(Csx),
      "  solvable = ", IsSolvableGroup(Csx), "\n");
Print("\n=> criterion status: C_P(yb) nonsolvable = ", not IsSolvableGroup(Cy),
      " ; Stab_Aut(xb) nonsolvable = ", not IsSolvableGroup(Csx), "\n");
QUIT;
