#############################################################################
## passport_probe_v1.g -- mathematician (Opus 5), 2026-08-29
## GATE 1 of the reopen design: does the roof window's degree-9 block realise
## a 9T27 Belyi passport, and WHICH one?
## The roof M is PB3/M = G9(deg 27) x PSL(2,8)(deg 9); its degree-9 block is
## generated by X4,Y4 (drophunt_checker_producer_v2.g L79-84).  Since
## PB3 = F2 x Z with F2 = <x,y> the loops around 0 and 1, the degree-9 block
## IS a monodromy representation F2 -> PSL(2,8), i.e. a Belyi map with triple
## (sigma_0, sigma_1, sigma_inf) = (X4, Y4, (X4 Y4)^{-1})  up to conventions.
#############################################################################
Read("search/drophunt_checker_producer_v2.g");;

CT := function(p) return SortedList(List(Orbits(Group(p),[1..9]), Length)); end;;
PPX := DCP2X4;; PPY := DCP2Y4;;
Print("PP_BLOCK_ORDER ", Size(Group(PPX,PPY)), "  degree ", LargestMovedPoint(Group(PPX,PPY)), "\n");
Print("PP_ORDERS  X=", Order(PPX), "  Y=", Order(PPY), "  XY=", Order(PPX*PPY),
      "  YX=", Order(PPY*PPX), "\n");
Print("PP_CT_X        ", CT(PPX), "\n");
Print("PP_CT_Y        ", CT(PPY), "\n");
Print("PP_CT_XY_INV   ", CT((PPX*PPY)^-1), "\n");
Print("PP_CT_XY       ", CT(PPX*PPY), "\n");
Print("PP_PASSPORT_[X,Y,(XY)^-1] ", [CT(PPX),CT(PPY),CT((PPX*PPY)^-1)], "\n");
## the two natural orderings of the marked pair
Print("PP_PASSPORT_[Y,X,(YX)^-1] ", [CT(PPY),CT(PPX),CT((PPY*PPX)^-1)], "\n");
## LMFDB representative quoted by scout: lambda = [[7,1,1],[2,2,2,2,1],[3,3,3]]
LM := [[1,1,7],[1,2,2,2,2],[3,3,3]];;
Print("PP_LMFDB_REP_SORTED ", LM, "\n");
Print("PP_MATCH_XY  ", SortedList([CT(PPX),CT(PPY),CT((PPX*PPY)^-1)]) = SortedList(LM), "\n");
## transitivity / primitivity of the block action
G9b := Group(PPX,PPY);;
Print("PP_TRANSITIVE ", IsTransitive(G9b,[1..9]),
      "  PRIMITIVE ", IsPrimitive(G9b,[1..9]), "\n");
## genus via Riemann-Hurwitz:  2g-2 = -2*9 + sum (9 - #cycles)
rh := -2*9 + (9-Length(CT(PPX))) + (9-Length(CT(PPY))) + (9-Length(CT((PPX*PPY)^-1)));;
Print("PP_RIEMANN_HURWITZ 2g-2 = ", rh, "   genus = ", (rh+2)/2, "\n");
## how many 9T27 passports with THIS ramification exist, up to simultaneous conj?
S9 := SymmetricGroup(9);;
Print("PP_NORMALISER_ORDER ", Size(Normalizer(S9, G9b)), " (=1512 expected)\n");
QUIT;
