## search/probe/hsp7_mainrun/predicate_lib_laneV_cf.g
## Lane V CLOSED-FORM (CF) judgement predicate library -- NEW file, per 裁定527
## (docs/notes/hsp7_mainrun_conversion_v1.md SS2.3). Does NOT modify or replace
## predicate_lib_laneV.g / statemachine_lib.g (those remain the pinned baseline,
## read-only, unchanged).
##
## CF eliminates word expansion entirely: EvalFullHexagonFixed (baseline)
## consumes a FreeGroup(x,y) word and walks it letter-by-letter through the
## transversal-cocycle state machine. CF instead evaluates (3.3)/(3.4) as a
## direct group-element identity in Q, using two automorphisms of Q,
##   A1 := Ad(sigma1)|_Q : x |-> x,        y |-> y^-1 x^-1 c
##   A2 := Ad(sigma2)|_Q : x |-> x^-1 y^-1 c,  y |-> y
## (canonical (1.11)/(1.12)), with A12:=A1 o A2, A21:=A2 o A1,
## beta:=A1(y), alpha:=A2(x). The judgement:
##   (3.3) <=> x^m A1(f^-1) beta^m A12(f) = f^-1 A12(x^-m) c^m
##   (3.4) <=> f^-1 y^m A2(f) alpha^m      = A21(y^-m) c^m A21(f)
## f is consumed as a GROUP ELEMENT of Q (not a free word) -- no
## LetterRepAssocWord/ExpandXYLettersToSigma, no per-candidate ApplyGen chain.
## m-dependent quantities (x^m,beta^m,c^m,A12(x^-m),y^m,alpha^m,A21(y^-m)) are
## computed ONCE per m (BuildMDependent); per-candidate cost is exactly 4
## ImageElm calls + ~12 multiplications + 2 comparisons (SS2.3).
##
## Derivation + verification lineage: docs/notes/hsp7_mainrun_conversion_v1.md
## SS2.3 (mathematician, Opus 5), verified against literal group multiplication
## on two TOY windows by the mathematician's own scripts
## scratchpad/conv_check.g (main window, c->1, 162/162 points) and
## scratchpad/conv_check2.g (control window, c order 3, 486/486 points),
## zero mismatches in both. This file ports those two TOY self-tests verbatim
## (function bodies unchanged, only renamed for library use) as a permanent
## regression gate -- SelfTestCF_Main() / SelfTestCF_Control() below -- so
## that any driver using this library can gate on them before trusting CF on
## real fixtures (mirrors statemachine_lib.g's own
## TestToyFixtureLiteralVsFixed/TestToyFixtureExtended gate pattern).
Read("search/probe/wac_v1/gap_output_prelude.g");

## ============================================================================
## BuildHexAutos(Qgrp, phiX, phiY, phiC): construct A1, A2 as automorphisms of
## Qgrp (Qgrp must be GENERATED by {phiX, phiY, phiC} -- true for both the N
## window (Qgrp=P, phiC=Identity(P) is a redundant generator) and the N0
## window (Qgrp=N0grp=DirectProduct(P,C7), phiC=chat0 the C7 factor)).
## Returns rec(A1,A2,beta,alpha) where A1,A2 are GAP group homomorphisms
## (so ImageElm(A1,q) / ImageElm(A2,q) evaluate them) and beta:=A1(y),
## alpha:=A2(x) are precomputed once (they do not depend on m or the
## candidate).
## ============================================================================
BuildHexAutos := function(Qgrp, phiX, phiY, phiC)
  local A1, A2, beta, alpha, sourceGenerated, image1Generated, image2Generated;
  sourceGenerated := (Subgroup(Qgrp, [phiX, phiY, phiC]) = Qgrp);
  if not sourceGenerated then
    Error("HEXAUTO_STOP: declared phiX/phiY/phiC do not generate Qgrp");
  fi;
  A1 := GroupHomomorphismByImages(Qgrp, Qgrp, [phiX, phiY, phiC],
                                   [phiX, phiY^-1 * phiX^-1 * phiC, phiC]);
  if A1 = fail then
    Error("HEXAUTO_STOP: A1 = Ad(sigma1)|_Q is not a well-defined automorphism of Q");
  fi;
  A2 := GroupHomomorphismByImages(Qgrp, Qgrp, [phiX, phiY, phiC],
                                   [phiX^-1 * phiY^-1 * phiC, phiY, phiC]);
  if A2 = fail then
    Error("HEXAUTO_STOP: A2 = Ad(sigma2)|_Q is not a well-defined automorphism of Q");
  fi;
  ## A homomorphism-by-images being well-defined is not yet the promised
  ## automorphism gate.  Check both that the declared images generate the
  ## codomain and that GAP certifies bijectivity.  These tests deliberately
  ## remain in the production constructor, not only in a calibration driver.
  image1Generated := (Subgroup(Qgrp,
    [ImageElm(A1, phiX), ImageElm(A1, phiY), ImageElm(A1, phiC)]) = Qgrp);
  image2Generated := (Subgroup(Qgrp,
    [ImageElm(A2, phiX), ImageElm(A2, phiY), ImageElm(A2, phiC)]) = Qgrp);
  if not image1Generated or not image2Generated then
    Error("HEXAUTO_STOP: A1/A2 declared images do not generate Qgrp");
  fi;
  if not IsBijective(A1) or not IsBijective(A2) then
    Error("HEXAUTO_STOP: A1/A2 failed the explicit bijectivity gate");
  fi;
  beta := ImageElm(A1, phiY);
  alpha := ImageElm(A2, phiX);
  return rec(A1 := A1, A2 := A2, beta := beta, alpha := alpha,
             source_generated := sourceGenerated,
             image1_generated := image1Generated,
             image2_generated := image2Generated,
             A1_bijective := true, A2_bijective := true);
end;;

## BuildMDependent(autos, phiX, phiY, phiC, m): precompute the m-dependent
## quantities ONCE for a given m. A12(q):=A1(A2(q)), A21(q):=A2(A1(q)).
BuildMDependent := function(autos, phiX, phiY, phiC, m)
  return rec(
    xm       := phiX^m,
    betam    := autos.beta^m,
    cm       := phiC^m,
    A12xminv := ImageElm(autos.A1, ImageElm(autos.A2, phiX^(-m))),
    ym       := phiY^m,
    alpham   := autos.alpha^m,
    A21yminv := ImageElm(autos.A2, ImageElm(autos.A1, phiY^(-m)))
  );
end;;

## EvalFullHexagonCF(mdep, autos, fElt): per-candidate judgement. fElt is a
## GROUP ELEMENT of Q (same group as phiX/phiY/phiC/autos were built from),
## NOT a free word. Cost: 4 ImageElm + ~12 multiplications + 2 comparisons,
## independent of m and of any word length.
EvalFullHexagonCF := function(mdep, autos, fElt)
  local a1finv, a2f, a12f, a21f, l33, r33, l34, r34;
  a1finv := ImageElm(autos.A1, fElt^-1);
  a2f    := ImageElm(autos.A2, fElt);
  a12f   := ImageElm(autos.A1, a2f);      ## A12(f) = A1(A2(f))  -- NOTE: recompute
                                            ## explicitly via f (not via a2f-reuse
                                            ## shortcut) is what A12 means; a2f is
                                            ## also directly A2(f), reused for hex34.
  a21f   := ImageElm(autos.A2, ImageElm(autos.A1, fElt));  ## A21(f) = A2(A1(f))
  l33 := mdep.xm * a1finv * mdep.betam * a12f;
  r33 := fElt^-1 * mdep.A12xminv * mdep.cm;
  l34 := fElt^-1 * mdep.ym * a2f * mdep.alpham;
  r34 := mdep.A21yminv * mdep.cm * a21f;
  return rec(hex33 := (l33 = r33), hex34 := (l34 = r34));
end;;

## ============================================================================
## TOY self-tests, ported from scratchpad/conv_check.g (main, c->1, 162 points)
## and scratchpad/conv_check2.g (control, c order 3, 486 points). Function
## bodies are the mathematician's verified constructions; only wrapped as
## library functions returning rec(ok, mismatches, total) for driver gating.
## ============================================================================
SelfTestCF_Main := function()
  local FreeB, s1, s2, xw, yw, Gfp, iso, S1, S2, GP, Xg, Yg, Cg, Qg, qs,
        autos, EvalLiteral, bad, tot, m, f, u;
  FreeB := FreeGroup("s1","s2");;
  s1 := FreeB.1;; s2 := FreeB.2;;
  xw := s1^2;; yw := s2^2;;
  Gfp := FreeB/[ s1*s2*s1*(s2*s1*s2)^-1, (s1*s2)^3,
                 xw^3, yw^3, Comm(xw,yw)^3, Comm(Comm(xw,yw),xw), Comm(Comm(xw,yw),yw) ];;
  if Size(Gfp) <> 162 then
    return rec(ok := false, reason := Concatenation("Size(B3/N) = ", String(Size(Gfp)), ", expected 162"));
  fi;
  iso := IsomorphismPermGroup(Gfp);;
  S1 := Image(iso, Gfp.1);;  S2 := Image(iso, Gfp.2);;
  GP := Group(S1,S2);;
  Xg := S1^2;;  Yg := S2^2;;  Cg := (S1*S2)^3;;
  Qg := Group(Xg,Yg,Cg);;
  autos := BuildHexAutos(Qg, Xg, Yg, Cg);;
  qs := Elements(Qg);;
  EvalLiteral := function(m, f)
    local u;  u := 2*m+1;
    return rec(hex33 := (S1^u * f^-1 * S2^u * f = f^-1 * S1 * S2 * Xg^(-m) * Cg^m),
               hex34 := (f^-1 * S2^u * f * S1^u = S2 * S1 * Yg^(-m) * Cg^m * f));
  end;;
  bad := 0;; tot := 0;;
  for m in [0..5] do
    for f in qs do
      tot := tot + 1;
      if EvalFullHexagonCF(BuildMDependent(autos, Xg, Yg, Cg, m), autos, f) <> EvalLiteral(m,f) then
        bad := bad + 1;
      fi;
    od;
  od;
  return rec(ok := true, mismatches := bad, total := tot, size_B3N := Size(Gfp));
end;;

SelfTestCF_Control := function()
  local FreeB, s1, s2, xw, yw, rels, Gfp, iso, S1, S2, GP, Xg, Yg, Cg, Qg, qs,
        autos, EvalLiteral, bad, tot, m, f;
  FreeB := FreeGroup("s1","s2");;
  s1 := FreeB.1;; s2 := FreeB.2;;
  xw := s1^2;; yw := s2^2;;
  rels := [ s1*s2*s1*(s2*s1*s2)^-1,
            xw^3, yw^3, Comm(xw,yw)^3, Comm(Comm(xw,yw),xw), Comm(Comm(xw,yw),yw) ];;
  Gfp := FreeB/rels;;
  if Size(Gfp) <> 486 then
    return rec(ok := false, reason := Concatenation("Size(control B3/N0) = ", String(Size(Gfp)), ", expected 486"));
  fi;
  iso := IsomorphismPermGroup(Gfp);;
  S1 := Image(iso, Gfp.1);;  S2 := Image(iso, Gfp.2);;
  GP := Group(S1,S2);;
  Xg := S1^2;;  Yg := S2^2;;  Cg := (S1*S2)^3;;
  if Order(Cg) <> 3 then
    return rec(ok := false, reason := Concatenation("Order(c) = ", String(Order(Cg)), ", expected 3"));
  fi;
  Qg := Group(Xg,Yg,Cg);;
  autos := BuildHexAutos(Qg, Xg, Yg, Cg);;
  qs := Elements(Qg);;
  EvalLiteral := function(m, f)
    local u;  u := 2*m+1;
    return rec(hex33 := (S1^u * f^-1 * S2^u * f = f^-1 * S1 * S2 * Xg^(-m) * Cg^m),
               hex34 := (f^-1 * S2^u * f * S1^u = S2 * S1 * Yg^(-m) * Cg^m * f));
  end;;
  bad := 0;; tot := 0;;
  for m in [0..5] do
    for f in qs do
      tot := tot + 1;
      if EvalFullHexagonCF(BuildMDependent(autos, Xg, Yg, Cg, m), autos, f) <> EvalLiteral(m,f) then
        bad := bad + 1;
      fi;
    od;
  od;
  return rec(ok := true, mismatches := bad, total := tot, size_control_B3N0 := Size(Gfp));
end;;
